### DISCUSSION TITLE
knative

### DISCUSSION THREAD

**Discussion by stormwalkerec** [vitobotta/hetzner-k3s#211] [General]
Trying to get knative working using hetzner-k3s, anyone succeed???

my issue is when they say to install their networking
"kubectl apply -f knative-networking.yaml"

It creates a lb, but never gets an external ip.

I have installed the cluster using ingress-nginx/ingress-nginx, which works 100%

but not finding any guides to either link the two, or set one or the other as the core lb....

any ideas would be appreciated !!

**Comment by vitobotta** [comment]
Hi @stormwalkerec I haven't checked knative in ages so I can't remember much. Can you check the logs of the cloud controller manager in `kube-system`? It should provide you with information as to why the load balancer is not being provisioned, if it's not. Do you see a load balancer in the Hetzner console?

**Comment by stormwalkerec** [comment]
Greetings @vitobotta ...

As I set master_pool instance_count to 3, it created a loadbalancer for that (test-api) that points only to the masters.

I am using the knative install guide from here:
https://knative.dev/docs/install/operator/knative-with-operators/#install-the-networking-layer

I have a yaml file that's using kourier (the one to select if your not sure)

NAME      TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)                      AGE
kourier   LoadBalancer   10.43.93.74   <pending>     80:30268/TCP,443:31080/TCP   15m

in the logs for the cloud controller manager I see this:

I0503 21:02:45.066544       1 load_balancers.go:109] "ensure Load Balancer" op="hcloud/loadBalancers.EnsureLoadBalancer" service="kourier" nodes=[test-cax11-master2 test-cax11-pool-small-worker3 test-cax11-pool-small-worker1 test-cax11-pool-small-worker2 test-cax11-master3 test-cax11-master1]
I0503 21:02:45.066776       1 event.go:294] "Event occurred" object="knative-serving/kourier" fieldPath="" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
E0503 21:02:45.226955       1 controller.go:289] error processing service knative-serving/kourier (will retry): failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.Create: neither load-balancer.hetzner.cloud/location nor load-balancer.hetzner.cloud/network-zone set
I0503 21:02:45.227028       1 event.go:294] "Event occurred" object="knative-serving/kourier" fieldPath="" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.Create: neither load-balancer.hetzner.cloud/location nor load-balancer.hetzner.cloud/network-zone set"

Guess they are not communicating properly.... or the knative kourier yaml doesn't have all the info it needs on how to ask for a lb....

I shall keep searching, someone must have a solution somewhere, else hack it till its working.

I'm really new to this (kubernetes), but been a dev for 20+ years, so not debugging isn't a chore .....

Thanks for any help/input in finding a potential solution

**Comment by vitobotta** [comment]
The key is this error "either load-balancer.hetzner.cloud/location nor load-balancer.hetzner.cloud/network-zone set". In order for the cloud controller manager to know where to create the load balancer for kourier you need to provide the service with some annotations in the manifest. Otherwise the lb will stay pending forever.  

So you need to edit the kourier manifest in this section

```yaml
apiVersion: v1
kind: Service
metadata:
  name: kourier
  namespace: kourier-system
  labels:
    networking.knative.dev/ingress-provider: kourier
    app.kubernetes.io/component: net-kourier
    app.kubernetes.io/version: "1.10.0"
    app.kubernetes.io/name: knative-serving
spec:
  ports:
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: 3scale-kourier-gateway
  type: LoadBalancer
```

and add at least this annotation:
```yaml
load-balancer.hetzner.cloud/location: <location>
```

See [this](https://github.com/vitobotta/hetzner-k3s#load-balancers) for other useful annotations.
