### DISCUSSION TITLE
nil pointer evaluating interface - When installing ingress-nginx for the first time

### DISCUSSION THREAD

**Discussion by hlaebe** [vitobotta/hetzner-k3s#222] [General]
Hi,

I'm following these [instructions](https://github.com/vitobotta/hetzner-k3s/blob/main/wiki/Setting%20up%20a%20cluster.md), cluster creation works fine but when I try to install ingress-nginx controller using
~~~
helm upgrade --install \
    ingress-nginx ingress-nginx/ingress-nginx \
     -f ./ingress-nginx-annotations.yaml  \
     --namespace ingress-nginx --create-namespace
~~~
I get the following error

~~~
Release "ingress-nginx" does not exist. Installing it now.
Error: template: ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml:1:18: executing "ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml" at <.Values.controller.admissionWebhooks.enabled>: nil pointer evaluating interface {}.admissionWebhooks
~~~

ingress-nginx-annotations.yaml

~~~
controller:
  kind: daemonset
  service:
    annotations:
      load-balancer.hetzner.cloud/location: fsn1
      load-balancer.hetzner.cloud/name: license_lb
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/uses-proxyprotocol: 'true'
      load-balancer.hetzner.cloud/hostname: mydomain.info
      load-balancer.hetzner.cloud/http-redirect-https: 'false'
~~~

cluster config

~~~
hetzner_token: ....
cluster_name: lic
kubeconfig_path: "./kubeconfig"
k3s_version: v1.26.1+k3s1
public_ssh_key_path: "~/.ssh/id_ed25519.pub"
private_ssh_key_path: "~/.ssh/id_ed25519"
use_ssh_agent: false
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
schedule_workloads_on_masters: false
masters_pool:
  instance_type: cax11
  instance_count: 3
  location: fsn1
worker_node_pools:
- name: small
  instance_type: cpx21
  instance_count: 3
  location: fsn1
  labels:
    - key: apps
      value: yes
- name: db
  instance_type: cax21
  instance_count: 3
  location: fsn1
  labels:
    - key: spilo
      value: yes
~~~

* Helm: 3.12.0
* hetzner_k3s: 1.1.2

Didn't find anything useful while googling, but maybe didn't know how to ask in the right way :-(

Any suggestions ?

Thanks in advance

**Comment by vitobotta** [comment]
I converted this into a discussion since it's not an issue with the tool. Not sure of what could cause the problem, never encountered it. What is in ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml:1:18 (if you open the helm chart)?

**Reply by hlaebe** [reply]
It says (with line numbers in front)

~~~
 1 {{- if and .Values.controller.admissionWebhooks.enabled .Values.controller.admissionWebhooks.patch.enabled (not .Values.controller.admissionWebhooks.certManager    .enabled) -}}
  2 apiVersion: v1
  3 kind: ServiceAccount
 ....
~~~

If I omit the annotations, it runs without error, but that makes no sense since we need the hetzner settings....

**Comment by derlinuxer** [comment]
Try this config:
```
controller:
  config:
    use-proxy-protocol: "true"
  service:
    type: LoadBalancer
    annotations:
      load-balancer.hetzner.cloud/name: nginx-controller-new
      load-balancer.hetzner.cloud/location: fsn1
      load-balancer.hetzner.cloud/use-private-ip: true
      load-balancer.hetzner.cloud/algorithm-type: least_connections
      load-balancer.hetzner.cloud/uses-proxyprotocol: true
      load-balancer.hetzner.cloud/hostname: example.com
```

helm install is running  and creates the hetzner load balancer.
I did use the installation so far, will be next.
