### DISCUSSION TITLE
How to setup k3s Cluster with disabled external Interfaces

### DISCUSSION THREAD

**Discussion by derlinuxer** [vitobotta/hetzner-k3s#252] [Show and tell]
## Some pre-condition:
- hetzner-k3s version >= 1.1.4 needed
- create private network in your hetzner project and use the name in cluster config `existing_network`
- I use a pfsense image in the private network to NAT the trafic from cluster into the world (other solutions possible)
- create a static route in hetzner private network: 0.0.0.0 -> pfSense-IP (or other NAT instance)
  - in this case we have also a fixed outgoing IP which is need for use to allow connections to customer systems to open there FW.

## Example config for test cluster:
```
hetzner_token: <your token>
cluster_name: rke2-test
kubeconfig_path: "./kubeconfig"
k3s_version: v1.26.5+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
use_ssh_agent: false
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
schedule_workloads_on_masters: false
private_network_subnet: 10.2.0.0/16
existing_network: net-kube-test
enable_public_net_ipv4: false
enable_public_net_ipv6: false
disable_flannel: false
cloud_controller_manager_manifest_url: "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.16.0/ccm-networks.yaml"
system_upgrade_controller_manifest_url: "https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml"
csi_driver_manifest_url: "https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.3.2/deploy/kubernetes/hcloud-csi.yml"
masters_pool:
  instance_type: cax11
  instance_count: 1
  location: fsn1
  image: 103908130
worker_node_pools:
- name: arm
  instance_type: cax21
  instance_count: 1
  location: fsn1
  image: 103908130
- name: x86
  instance_type: cx21
  instance_count: 1
  location: fsn1
  post_create_commands:
    - timedatectl set-timezone Europe/Berlin
    - >
      printf "network## {config## disabled}" |
      sed 's/##/:/g' > /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    - >
      printf "network##\n  version## 2\n  renderer## networkd\n  ethernets##\n    ens10##\n      dhcp4## true\n      nameservers##\n        addresses## [185.12.64.1, 185.12.64.2]\n      routes##\n        - to## default\n          via## 10.2.0.1" |
      sed 's/##/:/g' > /etc/netplan/50-cloud-init.yaml
    - netplan generate
    - netplan apply
    - apt update
    - apt upgrade -y
    - apt install nfs-common -y
    - apt autoremove -y
post_create_commands:
  - timedatectl set-timezone Europe/Berlin
  - >
    printf "network## {config## disabled}" |
    sed 's/##/:/g' > /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
  - >
    printf "network##\n  version## 2\n  renderer## networkd\n  ethernets##\n    enp7s0##\n      dhcp4## true\n      nameservers##\n        addresses## [185.12.64.1, 185.12.64.2]\n      routes##\n        - to## default\n          via## 10.2.0.1" |
    sed 's/##/:/g' > /etc/netplan/50-cloud-init.yaml
  - netplan generate
  - netplan apply
  - apt update
  - apt upgrade -y
  - apt install nfs-common -y
  - apt autoremove -y
``` 
## Some explanations:
- I run hetzner-k3s on a small machine inside the hetzner private network (also possible with configured VPN on your local machine)
- `post_create_commands` for cloud init will create own network configuration on VM creation
  - two section of it: one global for ARM Pools master and  worker-arm, second for worker-x86
  - this is needed because of different interface names
- the  sed command after printf is a bit confusing but if I set the `:` directly the yaml parser crashes. So I use `##` and replace it the end. _Didn't found anythink to mask the `:` (Maybe you found it ;-))_
- you have to be carefull this spaces for the yaml format in netconfig file 
- the corresponding netconfig file looks like this:
```
network:
  version: 2
  renderer: networkd
  ethernets:
    enp7s0:
      dhcp4: true
      nameservers:
        addresses: [185.12.64.1, 185.12.64.2]
      routes:
        - to: default
          via: 10.2.0.1
``` 
## Deployment grafik
Small graphic to get an overview (Network is different to example config): 
![kuberntes-deployment](https://github.com/vitobotta/hetzner-k3s/assets/8493524/90b0af2c-5269-4c6b-a507-d1d038115a9e)

**Comment by vitobotta** [comment]
To clarify, the tool installs k3s, not rke2 :)

**Reply by mgalesloot** [reply]
Successfully tested the derlinuxer script with a NAT Gateway as per https://community.hetzner.com/tutorials/how-to-set-up-nat-for-cloud-networks. I used a bastion host in the private network from where I could run the script and access the private hosts.

**Reply by derlinuxer** [reply]
Nice that it's working. :-) And thank for the link to setup a clean and easy NAT GW.

**Reply by easystartup-io** [reply]
Have verified this it works for me by setting up a new cluster along with the above provided nat gateway setup. Just one issue is when its a three node HA master cluster, the k8s api load balancer ip is still exposed to the public. Need to verify if the merged pr of @mgalesloot will help make the lb private and isolate all incoming connections to only the exposed application level load balancers.

**Comment by easystartup-io** [comment]
Do note that the interface need not be `ens10` for x86. Based on the instance type the network interface can also be  `enp7s0` as mentioned in the docs here. https://docs.hetzner.com/cloud/networks/server-configuration/#debian--ubuntu . You can ssh into your master/worker node and run `ip a` to find all attached interfaces.

**Comment by mgalesloot** [comment]
Try to access the k8s api via the private IP of the LB. This should work. Next you can disable public access of the hetzner LB. 
You can make it more fancy by setting a hostname for the LB, but this is not really required in order to make the cluster api private.

**Reply by easystartup-io** [reply]
Disabling the public network and manually editing kubeconfig file stops the worker nodes to be able to connect to the master and this also fails `hetzner-k3s create --config cluster_config.yaml`, so I need to try the hostname method

**Reply by easystartup-io** [reply]
hostname is working perfectly, an A record to the private ip of the load balancer is working perfectly as expected, thanks for your pr. I suppose setting the api_server_hostname directly to the private IP of the LB also might make it behave in exactly same manner. But I am sticking to DNS resolution for now.

**Comment by jampy** [comment]
Since the pfsense host is a potential single point of failure I guess this setup is not ideal for clusters (applications) that need to contact a lot of external APIs, am I right?

Would it be an alternative to block all **incoming** connections on the nodes using the **Hetzner** firewall that's available on the cloud servers and let the nodes talk to external hosts directly?

**Reply by pgruener** [reply]
As I noted in the past, the point is, that the hetzner workers cannot communicate to external hosts, when they dont have external IPs assigned. So if the workers should be kept only in an internal network, some NAT is necessary for them to talk to external hosts.

So as the pfSense is a single point of failure, it probably needs to be HA as well.

What I am considering is, if it would make sense to give Public IPs to ingress nodes (which could have ext ips) only and make them the NATs for the Workers.
What concerns what be against that structure?

**Reply by jampy** [reply]
What's the point of not giving the nodes an external IP when they need to contact external IPs?

**Reply by pgruener** [reply]
It's the topic of this explanation (implications are security, costs and hetzner resource limits). So if that's no point for you, you could skip it :)

**Reply by jampy** [reply]
I'm sorry but I don't get it. No offense please, I'm just trying to understand what I might be missing.

Cost: it's judt 0,50 €/month for each node for the external IP...

Limits: Doesn't Hetzner increase public IP limits along with server limits?

I find it particularily interesting that you mention security. Setting up a firewall with **all** ports closed seems reasonably secure for me for hosts that should be allowed to reach external IPs somehow. Again, what am I missing?

**Reply by vitobotta** [reply]
I kinda agree with @jampy to be honest. Cost wise it's not much in proportion to the cost of the servers and with the firewall I think it's ok also security wise.

**Reply by pgruener** [reply]
While the costs are >1,5€ each domain (here), I agree, that this won't be the huge impact or the reason to consider this scenario. My (unverified) info was, that you're limited (by 10 or 20) each project, but I really might be wrong?

It wasn't my intention to think about this setup like, this is the best way (hence I am only a reader ^^). It was just, that I noticed your very recent question, while I was aware of the answer: _Ext-IP is necessary, if the node should communicate to internet on its own._

For that specific point of reducing the single-point-of-failure, you could also spawn HA gateway pods. Depending on the scale, this could be more expensive than the costs of the IPs. But it would work (imho) for those, who like this kind of architecture.

Also in regards to security, you might be right, relying on the firewall. However, if you configure something wrong (or some of the processes do), or you miss something, you can make a mistake, while otherwise there is a lesser risk of mistakes.

In the meantime I understood this topic, about building this approach, not to make it the one and only solution for all k3s clusters.

**Reply by vitobotta** [reply]
@pgruener I have 1000 IPs available in my account. You can just request a raise to your account's limit for public IPs.

**Reply by pgruener** [reply]
Ah, wow, ok, thanks!

**Reply by mgalesloot** [reply]
A good reason for deploying a NAT gateway is when external APIs have a firewall. It is easier to request access for a single IP adress than for a range.

**Reply by aaahrens** [reply]
My thought on this (with Hetzner) is that's better to firewall than use a NAT gateway mainly because you can't assign private IPs explicitly to instances. You can get away with some hacky subnet stuff, but I digress

If you were to run PF/OPNsense in HA/CARP mode, you still would have massive downtime if the NAT failed because you can't immediately failover to a different default route. 

You could theoretically run unicast rpf on every node for a whole subnet dedicated to NAT, but there isn't a good TF provider for opnsense/pfsense and unicast comes with it's own issues.

**Reply by aaahrens** [reply]
from a security perspective they're functionally the same, and if you aren't running port and security monitoring on every node anyway you should be. 

The difference in my head is that terraform and monitoring will catch misconfigured firewalls. Monitoring will already catch bad pods with heavy networking requirements.

**Comment by axgkl** [comment]
shameless plug: See also #379 - has some additional infos on the topic

**Comment by vitobotta** [comment]
Can anyone help with testing v2 rc1? see https://github.com/vitobotta/hetzner-k3s/discussions/385

**Reply by derlinuxer** [reply]
Hey vitobotta,
I'am very busy, but yes I'll go for some test for v2.0.0 rcX in the next week.

**Comment by fjaeger-seibert** [comment]
Hey, I'm currently trying to boot a cluster in the private network with version 2.0.8. But for some reason the CloudInit step takes up to 7 minutes, until then the ‘create’ command cancels. If I use the same config with a public ipv4 address, the CloudInit step runs through within a few seconds. 

Am I missing something? Is my configuration wrong? Is it possible to set the timeout via a variable?

My config:

```yaml
cluster_name: test-cluster
kubeconfig_path: "~/.kube/config"
k3s_version: v1.26.4+k3s1
networking:
  ssh:
    port: 22
    use_agent: false # set to true if your key has a passphrase
    public_key_path: "~/.ssh/id_rsa.pub"
    private_key_path: "~/.ssh/id_rsa"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api:
      - 0.0.0.0/0
  public_network:
    ipv4: false
    ipv6: false
  private_network:
    enabled : true
    subnet: 10.12.8.0/22
    existing_network_name: "my-network"
disable_flannel: false # set to true if you want to install a different CNI
schedule_workloads_on_masters: false
masters_pool:
  instance_type: cpx31
  instance_count: 1
  location: nbg1
worker_node_pools:
- name: jira-node
  instance_type: ccx33
  instance_count: 1
  location: nbg1  
post_create_commands:
    - export IP=$(ip addr show enp7s0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
    - >
      printf "network## {config## disabled}" |
      sed 's/##/:/g' > /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    - >
      printf "network##\n  version## 2\n  renderer## networkd\n  ethernets##\n    enp7s0##\n      addresses##\n        - $IP/32\n      routes##\n        - to## default\n          via## xx.xx.xx.xx\n        - to## xx.xx.xx.xx/32\n          scope## link\n        - to## xx.xx.xx.xx/32\n          scope## link\n        - to## xx.xx.xx.xx/8\n          via## xx.xx.xx.xx\n          on-link## true\n        - to## xx.xx.xx.xx/12\n          via## xx.xx.xx.xx\n          on-link## true\n        - to## xx.xx.xx.xx/16\n          via## xx.xx.xx.xx\n          on-link## true\n" |
      sed 's/##/:/g' > /etc/netplan/50-cloud-init.yaml
    - netplan generate
    - netplan apply
```

And the resulting log:

```log
[Configuration] Validating configuration...
[Configuration] ...configuration seems valid.
[SSH key] SSH key already exists, skipping create
[Placement groups] Creating placement group test-cluster-masters...
[Placement groups] ...placement group test-cluster-masters created
[Placement groups] Creating placement group test-cluster-jira-node-2...
[Placement groups] ...placement group test-cluster-jira-node-2 created
[Instance test-cluster-master1] Creating instance test-cluster-master1 (attempt 1)...
[Instance test-cluster-master1] Instance status: starting
[Instance test-cluster-master1] Powering on instance (attempt 1)
[Instance test-cluster-master1] Waiting for instance to be powered on...
[Instance test-cluster-master1] Instance status: running
[Instance test-cluster-master1] Waiting for successful ssh connectivity with instance test-cluster-master1...
[Instance test-cluster-master1] Instance test-cluster-master1 already exists, skipping create
[Instance test-cluster-master1] Instance status: running
[Instance test-cluster-master1] Waiting for successful ssh connectivity with instance test-cluster-master1...
[Instance test-cluster-master1] Instance test-cluster-master1 already exists, skipping create
[Instance test-cluster-master1] Instance status: running
[Instance test-cluster-master1] Waiting for successful ssh connectivity with instance test-cluster-master1...
Error creating instance: timeout after 00:01:00
Instance creation for test-cluster-master1 failed. Try rerunning the create command.
```
