### DISCUSSION TITLE
ingres-nginx-controller External IP Stuck on Pending and Load Balancer Not creating

### DISCUSSION THREAD

**Discussion by thoth2357** [vitobotta/hetzner-k3s#373] [Q&A]
This is such a beautiful tool but i have issues having my ingress-nginx-container show an external IP, nor the load balancer create.
I dont know where i went wrong, as i've been religiously following the [wiki](https://github.com/vitobotta/hetzner-k3s/blob/main/wiki/Setting%20up%20a%20cluster.md) . On trying the 

On trying the  Step 11 of using helm to install ingress-nginx with the below command, 
```bash
helm upgrade --install \
ingress-nginx ingress-nginx/ingress-nginx \
-f ~/.kube/ingress-nginx-annotations.yaml \
--namespace ingress-nginx \
--create-namespace
```

but it kept giving the nil pointer error.  so i decided to use the old fashioned way of manually downloading the deploy.yaml and editing it , i.e Adding the annotations, ConfigMap, etc. 
But after applying the service/ingress-nginx-controller, the  External IP remains at <pending> and LB doesnt create. Please what else i'm i missing .

## My configs
hetzner-k3s_cluster_config.yaml
```yaml
---
hetzner_token: fO96B3.........
cluster_name: test
kubeconfig_path: "./kubeconfig"
k3s_version: v1.25.5+k3s1
public_ssh_key_path: "~/.ssh/OSI-LMS.pub"
private_ssh_key_path: "~/.ssh/OSI-LMS"
use_ssh_agent: false
ssh_allowed_networks:
- 0.0.0.0/0
api_allowed_networks:
- 0.0.0.0/0
schedule_workloads_on_masters: false
masters_pool:
  instance_type: cx21
  location: nbg1
  instance_count: 1
worker_node_pools:
- name: fsn-cpx21
  instance_type: cpx21
  location: fsn1
  instance_count: 2
- name: autoscaled-hel-cpx31
  instance_type: cpx31
  location: hel1
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 5
```

The ingress-nginx service section in the deploy.yaml  showing the annotations i added
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.10.1
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations: 
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/name: "lb1"
    load-balancer.hetzner.cloud/uses-proxyprotocol: 'true'
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
```

The ConfigMap section of the deploy.yaml showing the data  i added 
```yaml
apiVersion: v1
data:
  allow-snippet-annotations: "false"
  use-proxy-protocol: "true"
  use-forwarded-headers: "true"
  compute-full-forwarded-for: "true"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.10.1
  name: ingress-nginx-controller
  namespace: ingress-nginx
```

The stdout of my kubectl get all -A
```terminal
NAMESPACE       NAME                                            READY   STATUS    RESTARTS   AGE
ingress-nginx   pod/ingress-nginx-admission-create-w99g8        0/1     Pending   0          104m
ingress-nginx   pod/ingress-nginx-admission-patch-rgtl2         0/1     Pending   0          104m
ingress-nginx   pod/ingress-nginx-controller-675c47d5f8-4lsx6   0/1     Pending   0          104m
kube-system     pod/coredns-597584b69b-x246g                    0/1     Pending   0          6h42m

NAMESPACE       NAME                                         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
default         service/kubernetes                           ClusterIP      10.43.0.1       <none>        443/TCP                      6h42m
ingress-nginx   service/ingress-nginx-controller             LoadBalancer   10.43.87.12     <pending>     80:31683/TCP,443:30009/TCP   104m
ingress-nginx   service/ingress-nginx-controller-admission   ClusterIP      10.43.160.206   <none>        443/TCP                      104m
kube-system     service/kube-dns                             ClusterIP      10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP       6h42m

NAMESPACE       NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
ingress-nginx   deployment.apps/ingress-nginx-controller   0/1     1            0           104m
kube-system     deployment.apps/coredns                    0/1     1            0           6h42m

NAMESPACE       NAME                                                  DESIRED   CURRENT   READY   AGE
ingress-nginx   replicaset.apps/ingress-nginx-controller-675c47d5f8   1         1         0       104m
kube-system     replicaset.apps/coredns-597584b69b                    1         1         0       6h42m

NAMESPACE       NAME                                       COMPLETIONS   DURATION   AGE
ingress-nginx   job.batch/ingress-nginx-admission-create   0/1           104m       104m
ingress-nginx   job.batch/ingress-nginx-admission-patch    0/1           104m       104m
```
