### DISCUSSION TITLE
Upgrade of Nginx Ingress - External IP stuck on pending

### DISCUSSION THREAD

**Discussion by creib** [vitobotta/hetzner-k3s#401] [Q&A]
Hi,
I am trying to update my Nginx Ingress Helmchart to the latest version. After applying the new chart I get the error message in the cloudcontroller:
```
hcloud-cloud-controller-manager-855d57895-spffd I0802 22:48:32.141733       1 event.go:389] "Event occurred"
object="matomo/matomo" fieldPath="" kind="Service" apiVersion="v1" type="Warn
ing" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: hcloud/
loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.Create: neither
load-balancer.hetzner.cloud/location nor load-balancer.hetzner.cloud/network-zone set"


hcloud-cloud-controller-manager-58f955d958-mb2hh E0803 07:45:16.492049       1 controller.go:298] error processing service 
ingress-nginx/ingress-nginx-controller (retrying with exponential backoff): failed to
 ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.ReconcileHCLBTargets: hcops/providerIDToServerID: missing prefix hcloud://:
```

But I added the Loadbalancer location in the Annotations in the chart like this:

```
  service:
    # -- Enable controller services or not. This does not influence the creation of either the admission webhook or the metrics service.
    enabled: true
    external:
      # -- Enable the external controller service or not. Useful for internal-only deployments.
      enabled: true
    # -- Annotations to be added to the external controller service. See `controller.service.internal.annotations` for annotations to be added to the internal controller service.
    annotations:
      load-balancer.hetzner.cloud/location: nbg1
      load-balancer.hetzner.cloud/name: WORKERS_LOAD_BALANCER_NAME
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/uses-proxyprotocol: 'true'
      load-balancer.hetzner.cloud/hostname: matomo.doesnotmatter.com
      load-balancer.hetzner.cloud/http-redirect-https: 'false'
      load-balancer.hetzner.cloud/disable-private-ingress: 'false'
```

Any Idea?

I am using cloud-controller 1.18.0 and tested with 1.20.0 as well.
