### DISCUSSION TITLE
Adding WebSocket Support to Hetzner-k3s Cluster

### DISCUSSION THREAD

**Discussion by LarvePoire** [vitobotta/hetzner-k3s#436] [Q&A]
Hello everyone,

I'm currently trying to add WebSocket support to my Hetzner-k3s cluster. After reading the [Socket.io documentation](https://socket.io/docs/v4/using-multiple-nodes/), I attempted to add the necessary annotations to the Ingress of my application as follows:

**`ingress-app.yaml`**

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genesis-core
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set $forwarded_client_ip "";
      if ($http_x_forwarded_for ~ "^([^,]+)") {
        set $forwarded_client_ip $1;
      }
      set $client_ip $remote_addr;
      if ($forwarded_client_ip != "") {
        set $client_ip $forwarded_client_ip;
      }
    nginx.ingress.kubernetes.io/upstream-hash-by: "$client_ip"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - genesiscore.larvepoire.app
      secretName: genesiscore.larvepoire.app-tls
  rules:
    - host: genesiscore.larvepoire.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: genesis-core
                port:
                  number: 80

```

I also updated my **`config.yaml`** like this:

**`config.yaml`**

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  use-proxy-protocol: "true"
  enable-snippet: "true"

```

However, I'm not sure what changes, if any, I need to make in my **`ingress-nginx-annotation.yaml`** file.
```yaml
controller:
  kind: DaemonSet
  service:
    annotations:
      load-balancer.hetzner.cloud/location: nbg1
      load-balancer.hetzner.cloud/name: ingress-nginx-lb
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
      load-balancer.hetzner.cloud/hostname: k8s.larvepoire.app
      load-balancer.hetzner.cloud/http-redirect-https: "false"
```

When I try to apply my Ingress configuration, I encounter the following error:

```bash
kubectl apply -f ./ingress-genesis-core.yaml
Error from server (BadRequest): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.k8s.io/v1\",\"kind\":\"Ingress\",\"metadata\":{\"annotations\":{\"cert-manager.io/cluster-issuer\":\"letsencrypt-prod\",\"kubernetes.io/ingress.class\":\"nginx\",\"kubernetes.io/tls-acme\":\"true\",\"nginx.ingress.kubernetes.io/configuration-snippet\":\"set $forwarded_client_ip \\\"\\\";\\nif ($http_x_forwarded_for ~ \\\"^([^,]+)\\\") {\\n  set $forwarded_client_ip $1;\\n}\\nset $client_ip $remote_addr;\\nif ($forwarded_client_ip != \\\"\\\") {\\n  set $client_ip $forwarded_client_ip;\\n}\\n\",\"nginx.ingress.kubernetes.io/upstream-hash-by\":\"$client_ip\"},\"name\":\"genesis-core\",\"namespace\":\"default\"},\"spec\":{\"ingressClassName\":\"nginx\",\"rules\":[{\"host\":\"genesiscore.larvepoire.app\",\"http\":{\"paths\":[{\"backend\":{\"service\":{\"name\":\"genesis-core\",\"port\":{\"number\":80}}},\"path\":\"/\",\"pathType\":\"Prefix\"}]}}],\"tls\":[{\"hosts\":[\"genesiscore.larvepoire.app\"],\"secretName\":\"genesiscore.larvepoire.app-tls\"}]}}\n","nginx.ingress.kubernetes.io/configuration-snippet":"set $forwarded_client_ip \"\";\nif ($http_x_forwarded_for ~ \"^([^,]+)\") {\n  set $forwarded_client_ip $1;\n}\nset $client_ip $remote_addr;\nif ($forwarded_client_ip != \"\") {\n  set $client_ip $forwarded_client_ip;\n}\n","nginx.ingress.kubernetes.io/upstream-hash-by":"$client_ip"}}}
to:
Resource: "networking.k8s.io/v1, Resource=ingresses", GroupVersionKind: "networking.k8s.io/v1, Kind=Ingress"
Name: "genesis-core", Namespace: "default"
for: "./ingress-genesis-core.yaml": error when patching "./ingress-genesis-core.yaml": admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: nginx.ingress.kubernetes.io/configuration-snippet annotation cannot be used. Snippet directives are disabled by the Ingress administrator
```

It seems that the `nginx.ingress.kubernetes.io/configuration-snippet` annotation cannot be used because snippet directives are disabled by the Ingress administrator.

I'm a bit stuck on how to properly configure WebSocket support for my application. Any guidance on how to enable this or alternative approaches would be greatly appreciated.

Thank you in advance for your help!
