### DISCUSSION TITLE
Using 1.1.5 still (for testing)

### DISCUSSION THREAD

**Discussion by AnttiKarvinen** [vitobotta/hetzner-k3s#440] [Q&A] [answered]
I was going to test on our test cluster how 1.1.5 works and after that i'd upgrade to 2.0.8 and test how naming nodes work.
To make things more interesting we have altered server types straight to Hetzner (that CX -deal) so naming is kind of all over the place.

I tried to make cluster with 1.1.5 with old config 
```
hetzner_token: 
cluster_name: sse-test-cloud
kubeconfig_path: "./sse-kubeconfig"
k3s_version: v1.27.10+k3s1	
public_ssh_key_path: ".ssh/sse-test-cloud-key.pub"
private_ssh_key_path: ".ssh/sse-test-cloud-key"
use_ssh_agent: false
# ssh_port: 22
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
schedule_workloads_on_masters: false
private_network_subnet: 10.0.0.0/16
disable_flannel: false # set to true if you want to install a different CNI
image: ubuntu-20.04 # optional: default is ubuntu-22.04
# autoscaling_image: 103908130 # optional, defaults to the `image` setting
# snapshot_os: microos # otional: specified the os type when using a custom snapshot
cloud_controller_manager_manifest_url: "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.19.0/ccm-networks.yaml"
csi_driver_manifest_url: "https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.6.0/deploy/kubernetes/hcloud-csi.yml"
system_upgrade_controller_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/system-upgrade-controller.yaml"
system_upgrade_controller_crd_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/crd.yaml"
masters_pool:
  instance_type: cx22
  instance_count: 1
  location: nbg1
worker_node_pools:
- name: default
  instance_type: cx22
  instance_count: 2
  location: nbg1 
``` 
but this gets stuck on validating configuration.

This should work?
