### DISCUSSION TITLE
How to add labels for nodeselector

### DISCUSSION THREAD

**Discussion by abhishek-ch** [vitobotta/hetzner-k3s#460] [General]
I am trying to add the following

```
worker_node_pools:
- name: small
  instance_type: cpx11
  instance_count: 2
  location: fsn1
- name: medium
  instance_type: cpx21
  instance_count: 0
  location: nbg1
  labels:
    - key: instance_type
      value: medium
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 2
- name: high
  instance_type: cpx31
  instance_count: 0
  location: hel1
  labels:
    - key: instance_type
      value: high
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 2
  ```
  
  But when I am trying to create the cluster 
  
  ```
  [Node labels]
Adding labels to medium pool workers...
error: resource(s) were provided, but no name was specified
[Node labels] : error: resource(s) were provided, but no name was specified
```

Is this feature not available?

**Comment by vitobotta** [comment]
Last time I tested this for the 2.0 it worked just fine. Can you share your full config (minus the token) so I can try and reproduce?

**Comment by abhishek-ch** [comment]
Here is the code

```
cluster_name: test-stack
kubeconfig_path: "./kubeconfig"
k3s_version: v1.30.3+k3s1

networking:
  ssh:
    port: 22
    use_agent: false # set to true if your key has a passphrase
    public_key_path: "~/.ssh/ssh.pub"
    private_key_path: "~/.ssh/ssh"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api: # this will firewall port 6443 on the nodes; it will NOT firewall the API load balancer
      - 0.0.0.0/0
  public_network:
    ipv4: true
    ipv6: true
  private_network:
    enabled : true
    subnet: 10.0.0.0/16
    existing_network_name: ""
  cni:
    enabled: true
    encryption: false
    mode: cilium

  cluster_cidr: 10.244.0.0/16 # optional: a custom IPv4/IPv6 network CIDR to use for pod IPs
  service_cidr: 10.43.0.0/16 # optional: a custom IPv4/IPv6 network CIDR to use for service IPs. Warning, if you change this, you should also change cluster_dns!
  cluster_dns: 10.43.0.10 # optional: IPv4 Cluster IP for coredns service. Needs to be an address from the service_cidr range


  manifests:
    cloud_controller_manager_manifest_url: "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.20.0/ccm-networks.yaml"
    csi_driver_manifest_url: "https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.9.0/deploy/kubernetes/hcloud-csi.yml"
    system_upgrade_controller_deployment_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/system-upgrade-controller.yaml"
    system_upgrade_controller_crd_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/crd.yaml"
    cluster_autoscaler_manifest_url: "https://raw.githubusercontent.com/kubernetes/autoscaler/master/cluster-autoscaler/cloudprovider/hetzner/examples/cluster-autoscaler-run-on-master.yaml"

datastore:
  mode: etcd # etcd (default) or external
  external_datastore_endpoint: invalidurl

schedule_workloads_on_masters: false
masters_pool:
  instance_type: cpx11
  instance_count: 1
  location: nbg1

worker_node_pools:
- name: small
  instance_type: cpx11
  instance_count: 1
  location: fsn1
- name: medium
  instance_type: cpx21
  instance_count: 0
  location: nbg1
  labels:
    - key: instance_type
      value: medium
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 2
- name: high
  instance_type: cpx31
  instance_count: 0
  location: hel1
  labels:
    - key: instance_type
      value: high
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 2

embedded_registry_mirror:
  enabled: true
  ```
