### DISCUSSION TITLE
Multi zone masters on HA setup?

### DISCUSSION THREAD

**Discussion by GiovanniBarile** [vitobotta/hetzner-k3s#488] [Q&A]
Hello, is there a way to create a multi zone control plane? For example 
1x master in Helsinki, 1x in Falkenstein and 1x in Nuremberg ? 
So it can really be HA, this way if something happens in a specific datacenter, all the masters go down at the same time

Thank you

**Comment by vitobotta** [comment]
Hi, it’s on the plan, but it’s not available right now. By default, hetzner-k3s uses etcd for the control plane data storage, and etcd is really sensitive to latency issues. So, having masters in different regions wouldn’t work well without a lot of adjustments and tests. Based on my experience, etcd can be quite challenging in setups like this.

hetzner-k3s v2 lets you use a relational database, such as Postgres or MySQL, instead of etcd, which solves the latency problem. This part is already in place, but I still need to add support for configuration options that let you choose where to place the masters. I can’t give you an exact timeframe for this because I have a lot of other tasks and limited time.

**Reply by jobetinfosec** [reply]
Hello Vito,
I'm using the latest version of hetzner-k3s.
I tried to follow the instructions here: https://github.com/vitobotta/hetzner-k3s/blob/main/docs/Masters_in_different_locations.md but the script creates all 3 master nodes in a single location (Falkenstein).

This is my config:
```
masters_pool:
  instance_type: cpx21
  instance_count: 3
  location:
  - fns1
  - hel1
  - nbg1
```
Am I missing something?

**Reply by vitobotta** [reply]
Hi, it's `locations` plural :)

**Reply by jobetinfosec** [reply]
Hello Vito,
I changed that to `locations`, but now an error shows up and the script stops:
`[Configuration]  - All must be in valid locations and in the same same network zone when using a private network`

**Reply by vitobotta** [reply]
Can you share your full config?

**Reply by jobetinfosec** [reply]
Here you are:

```
hetzner_token: token
cluster_name: test-k3s
kubeconfig_path: "./kubeconfig"
k3s_version: v1.32.0+k3s1

networking:
  ssh:
    port: 22
    use_agent: false
    public_key_path: "~/.ssh/id_rsa.pub"
    private_key_path: "~/.ssh/id_rsa"
  allowed_networks:
    ssh:
      - xxx/32
    api:
      - 0.0.0.0/0
  public_network:
    ipv4: true
    ipv6: true
  private_network:
    enabled : true
    subnet: 10.3.0.0/16
    existing_network_name: ""
  cni:
    enabled: true
    encryption: false
    mode: flannel

masters_pool:
  instance_type: cpx21
  instance_count: 3
  locations:
  - fns1
  - hel1
  - nbg1

worker_node_pools:
- name: node
  instance_type: cpx21
  instance_count: 3
  location: fsn1

protect_against_deletion: false


```
