### DISCUSSION TITLE
kubernetes Fake Certificate

### DISCUSSION THREAD

**Discussion by saashqdev** [vitobotta/hetzner-k3s#501] [Q&A]
Hi Vito:

I followed this doc exactly: https://github.com/vitobotta/hetzner-k3s/blob/main/docs/Setting%20up%20a%20cluster.md For some reason I always get the K8s Fake Cert and not my Letsencrypt one.

I'm with Cloudflare and here my clusterissuer.yaml:
```
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: saashqdev@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - dns01:
        cloudflare:
          email: saashqdev@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-key
      selector:
        dnsZones:
        - 'saashq.org'
        - '*.saashq.org'
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-key: <cloudflare-api-key>
```
and here's my helloworld:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: rancher/hello-world
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: saashq.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world
            port:
              number: 80
  tls:
  - hosts:
    - saashq.org
    secretName: saashq-org-tls
```
It creates the cert and secret fine. But I keep getting the Kubernetes Fake Certificate. My services are as follows:
```
NAMESPACE       NAME                                 TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
cert-manager    cert-manager                         ClusterIP      10.43.78.234    <none>        9402/TCP                     28m
cert-manager    cert-manager-cainjector              ClusterIP      10.43.66.134    <none>        9402/TCP                     28m
cert-manager    cert-manager-webhook                 ClusterIP      10.43.150.212   <none>        443/TCP,9402/TCP             28m
default         hello-world                          ClusterIP      10.43.184.235   <none>        80/TCP                       14m
default         kubernetes                           ClusterIP      10.43.0.1       <none>        443/TCP                      41m
ingress-nginx   ingress-nginx-controller             LoadBalancer   10.43.212.233   saashq.org    80:30460/TCP,443:32358/TCP   38m
ingress-nginx   ingress-nginx-controller-admission   ClusterIP      10.43.209.17    <none>        443/TCP                      38m
kube-system     hcloud-csi-controller-metrics        ClusterIP      10.43.52.110    <none>        9189/TCP                     41m
kube-system     hcloud-csi-node-metrics              ClusterIP      10.43.91.108    <none>        9189/TCP                     41m
kube-system     kube-dns                             ClusterIP      10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP       41m
```
Everything looks fine but for some reason it won't go secure in the browser:
![sc1](https://github.com/user-attachments/assets/988e2b8e-de49-436d-b352-1fdf5f935506)

Is it that Letsencrypt going to port 80 on a Hetzner LB thing? My service is set do a domain name instead of an IP though like in your docs.

I created a test certificate and I got the following in the certificate logs (Issuing certificate as Secret does not exist):
```
...
    Status:                      False
    Type:                        Ready
  Next Private Key Secret Name:  saashq-org-tls-test-jj5nx
Events:
  Type    Reason     Age   From                                       Message
  ----    ------     ----  ----                                       -------
  Normal  Issuing    75s   cert-manager-certificates-trigger          Issuing certificate as Secret does not exist
  Normal  Generated  75s   cert-manager-certificates-key-manager      Stored new private key in temporary Secret resource "saashq-org-tls-test-jj5nx"
  Normal  Requested  75s   cert-manager-certificates-request-manager  Created new CertificateRequest resource "saashq-org-tls-test-1"
```

Cheers,
Dave
