### DISCUSSION TITLE
New Cluster creation throws error  Back-off pulling image "registry.k8s.io/autoscaling/cluster-autoscaler:v1.32.0"

### DISCUSSION THREAD

**Discussion by abhishek-ch** [vitobotta/hetzner-k3s#576] [General]
1. While trying to create new cluster throwing `
Back-off pulling image "registry.k8s.io/autoscaling/cluster-autoscaler:v1.32.0"`

2. Another error in hcloud-csi-node 

My hetzner-k3s --version 2.2.7

Error:
```

Liveness probe failed: Get "http://10.244.0.7:9808/healthz": dial tcp 10.244.0.7:9808: connect: connection refused

time=2025-04-04T09:27:03.132Z level=INFO source=/home/runner/work/csi-driver/csi-driver/cmd/node/main.go:49 msg="Fetched data from metadata service" id=62306891 location=nbg1
```

Do I need to change any config

```
kubeconfig_path: "./kubeconfig"
k3s_version: v1.31.4+k3s1

networking:
  ssh:
    port: 22
    use_agent: false # set to true if your key has a passphrase
    public_key_path: "~/.ssh/rsa.pub"
    private_key_path: "~/.ssh/rsa"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api: # this will firewall port 6443 on the nodes
      - 0.0.0.0/0
  public_network:
    ipv4: true
    ipv6: true
  private_network:
    enabled: true
    subnet: 10.0.0.0/16
    existing_network_name: ""
  cni:
    enabled: true
    encryption: false
    mode: flannel

  cluster_cidr: 10.244.0.0/16
  service_cidr: 10.43.0.0/16
  cluster_dns: 10.43.0.10


  manifests:
    cloud_controller_manager_manifest_url: "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.23.0/ccm-networks.yaml"
    csi_driver_manifest_url: "https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.12.0/deploy/kubernetes/hcloud-csi.yml"
    system_upgrade_controller_deployment_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.14.2/system-upgrade-controller.yaml"
    system_upgrade_controller_crd_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.14.2/crd.yaml"
    cluster_autoscaler_manifest_url: "https://raw.githubusercontent.com/kubernetes/autoscaler/master/cluster-autoscaler/cloudprovider/hetzner/examples/cluster-autoscaler-run-on-master.yaml"
    cluster_autoscaler_container_image_tag: "v1.32.0"

datastore:
  mode: etcd

schedule_workloads_on_masters: false

masters_pool:
  instance_type: cx32
  instance_count: 1 # for HA; you can also create a single master cluster for dev and testing (not recommended for production)
  locations: # You can choose a single location for single master clusters or if you prefer to have all masters in the same location. For regional clusters (which are only available in the eu-central network zone), each master needs to be placed in a separate location.
    - nbg1

worker_node_pools:
- name: medium-static
  instance_type: cx32
  instance_count: 1
  labels:
    - key: instance_type
      value: cx32
  location: hel1

- name: medium-autoscaled
  instance_type: cpx31
  location: fsn1
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 1

embedded_registry_mirror:
  enabled: false

protect_against_deletion: false

create_load_balancer_for_the_kubernetes_api: false 
```
