### ISSUE TITLE
Undefined method `[]`

### ISSUE THREAD

**Issue by Rinnray** [vitobotta/hetzner-k3s#10]
Hi. When I run the command `hetzner-k3s create-cluster --config-file cluster_config.yaml` I get a few of these errors:

```
Traceback (most recent call last):
        7: from /home/luna/.rvm/gems/ruby-2.6.0/gems/hetzner-k3s-0.3.5/lib/hetzner/k3s/cluster.rb:146:in `block (2 levels) in create_resources'
        6: from /home/luna/.rvm/gems/ruby-2.6.0/gems/hetzner-k3s-0.3.5/lib/hetzner/k3s/cluster.rb:448:in `wait_for_ssh'
        5: from /home/luna/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
        4: from /home/luna/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:33:in `catch'
        3: from /home/luna/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:33:in `catch'
        2: from /home/luna/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
        1: from /home/luna/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/home/luna/.rvm/gems/ruby-2.6.0/gems/hetzner-k3s-0.3.5/lib/hetzner/k3s/cluster.rb:449:in `block in wait_for_ssh': undefined method `[]' for nil:NilClass (NoMethodError)
```
Not sure how to fix or what to even do. The system I'm running it from is Manjaro. I updated hetzner-k3s to the latest and still had the issue.

Edit: Fixed the codeblock.

**Comment by vitobotta** [comment]
Hi! You may need to install some dependencies for your distro. Can you try with the Docker image as it's easier? See README for details :)

**Comment by Rinnray** [comment]
Alright I'll try that! I'll get back if it works or not.

**Comment by Rinnray** [comment]
Nope, getting the same error running it with Docker.

**Comment by vitobotta** [comment]
Can you share the cluster config yaml (without the token of course)?

**Comment by Rinnray** [comment]
Of course!
```
---
hetzner_token: <TOKEN>
cluster_name: Gliroid_Studios_Cluster
kubeconfig_path: "./kubeconfig"
k3s_version: v1.21.3+k3s1
ssh_key_path: "~/.ssh/id_rsa.pub"
verify_host_key: false
location: nbg1
masters:
  instance_type: cpx11
  instance_count: 3
worker_node_pools:
- name: small
  instance_type: cpx21
  instance_count: 3
```
