### ISSUE TITLE
Invalid Hetzner Cloud token

### ISSUE THREAD

**Issue by opsdevit-nl** [vitobotta/hetzner-k3s#104]
Hi,

I appreciate your work a lot, I got me going with k3s and I using it constantly for learning purposes. I'm using your project for about a year now and it worked great until I upgraded my hetzner-k3s binary (running on Linux). No matter what I do, I get the error:  Invalid Hetzner Cloud token.

I ran: 
- `hetzner-k3s create-cluster --config-file=config.yaml`
- `hetzner-k3s upgrade-cluster --config-file=config.yaml --new-k3s-version v1.24.4+k3s1`
- I created the config file from scratch by using the example from the instructions
- Created a few new Hetzner Projects and API Tokens at them with read and write permissions
- I checked my env vars (HCLOUD_TOKEN is not set)
- Tried with and without qoutes around the token in the config file
- I tested the Hetzner API by running `curl  -H "Authorization: Bearer $API_TOKEN"   'https://api.hetzner.cloud/v1/server_types'` with the API Token and that works fine. 
- I tried versions 0.6.0 until 0.6.5.pre1
- I even tried the docker version

In al cases I get the error: 
```
Some information in the configuration file requires your attention:
 - Invalid Hetzner Cloud token
```

I hope I didn't make a simple mistake. Do you have any idea what the problem can be?

Thanks in advance

**Comment by vitobotta** [comment]
Hi, there seem to be some issues with the binaries which I am investigating. Can you try with the gem instead?

**Comment by Privatecoder** [comment]
@opsdevit-nl

Can you share your config (replace the token) to check?

@vitobotta I think the problematic part is after creating the Cluster via Hetzners API which seems to work for everyone so far, so I reckon this is a different issue.

**Comment by opsdevit-nl** [comment]
> Hi, there seem to be some issues with the binaries which I am investigating. Can you try with the gem instead?

Unfortunately I'm running Fedora 36 and Ruby 2.7.1 is not available in it's epos. Installing it in a different way is a big hassle so to see

**Comment by opsdevit-nl** [comment]
> @opsdevit-nl
> 
> Can you share your config (replace the token) to check?
> 
> @vitobotta I think the problematic part is after creating the Cluster via Hetzners API which seems to work for everyone so far, so I reckon this is a different issue.

Sure!

```
hetzner_token: <token>
cluster_name: cluster-test
kubeconfig_path: "./kubeconfig"
k3s_version: v1.24.4+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
ssh_allowed_networks:
- 0.0.0.0/0
verify_host_key: false
location: nbg1
schedule_workloads_on_masters: false
masters:
  instance_type: cpx11
  instance_count: 1
worker_node_pools:
- name: small
  instance_type: cx41
  instance_count: 1
```

**Comment by Privatecoder** [comment]
for me your config shows the following error: `At least one network/IP range must be specified for API access`

Adding
```
api_allowed_networks:
  - 0.0.0.0/0
 ```
fixes that. However there does not seem to be another issue with that config (I just copy&pasted it from here).

**Comment by vitobotta** [comment]
On a side note, I think I have (almost) decided to rewrite the tool in Rust because while Ruby is my favorite, it's not really the best for these things because you cannot package it easily etc. I am gonna spend some time on it during the weekend to play with this option.

**Comment by opsdevit-nl** [comment]
> for me your config shows the following error: `At least one network/IP range must be specified for API access`
> 
> Adding
> 
> ```
> api_allowed_networks:
>   - 0.0.0.0/0
> ```
> 
> fixes that. However there does not seem to be another issue with it (I just copy&pasted it from here).

I pasted the wrong variant and in the latest one it is present. Still the same error.
Tested with this one and still the same error

```
[C150 cluster ri@xf-]$hetzner-k3s create-cluster --config-file=config.yaml
Some information in the configuration file requires your attention:
 - Invalid Hetzner Cloud token
[C151 cluster ri@xf-]$cat config.yaml 
hetzner_token: 53YxoUyxxxxUs8uIwjpxxxxK9xduVAiJ94jxxxxj920GmrXwLmhogIyp6Y5xxxx 
cluster_name: cluster-test
kubeconfig_path: "./kubeconfig"
k3s_version: v1.24.4+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
ssh_allowed_networks:
- 0.0.0.0/0
api_allowed_networks:
- 0.0.0.0/0
verify_host_key: false
location: nbg1
schedule_workloads_on_masters: false
masters:
  instance_type: cpx11
  instance_count: 1
worker_node_pools:
- name: small
  instance_type: cx41
  instance_count: 1
[C152 cluster ri@xf-]$hetzner-k3s version
0.6.5.pre1
```
redacted token a bit
