### ISSUE TITLE
Can't run newer versions of docker image

### ISSUE THREAD

**Issue by jsven1** [vitobotta/hetzner-k3s#106]
Hi,

when I try 

```shell
docker run --rm -it -v c:\Users\john\k3s:/cluster -v c:\Users\john\k3s\ssh:/tmp/.ssh vitobotta/hetzner-k3s:v0.6.4 create-cluster --config-file /cluster/config.yaml
```

on a windows machine

with the following config.yaml:

```yaml
---
hetzner_token: <secret-token>
cluster_name: cloud1
kubeconfig_path: "/cluster/kubeconfig"
k3s_version: v1.24.4+k3s1
public_ssh_key_path: "/tmp/.ssh/id_rsa_hetz1.pub"
private_ssh_key_path: "/tmp/.ssh/id_rsa_hetz1"
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: nbg1
schedule_workloads_on_masters: false
masters:
  instance_type: cpx21
  instance_count: 1
worker_node_pools:
- name: small
  instance_type: cpx21
  instance_count: 4
- name: big
  instance_type: cpx31
  instance_count: 1
```

(I have the public and private keys in folder ```c:\Users\john\k3s\ssh```)

I get 

```shell
Could not find rake-12.3.3 in any of the sources
Run `bundle install` to install missing gems.
```

This also happens for versions before 0.6.4, while some previous versions (such as 0.5.1) do not give this error message.
