### ISSUE TITLE
Public SSH key is invalid

### ISSUE THREAD

**Issue by xLEpEX** [vitobotta/hetzner-k3s#108]
I'm not sure if I did something wrong, but when I run the create-cluster command I get the error "Invalid Public SSH key path" and I can't find the method which is capable for the validation of the public key

```
config:
---
hetzner_token: token
cluster_name: test
kubeconfig_path: "./kubeconfig"
k3s_version: v1.25.3-rc2+k3s1
public_ssh_key_path: "public.pub"
private_ssh_key_path: "privkey.ppk"
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: nbg1
schedule_workloads_on_masters: false
masters:
  instance_type: cx21
  instance_count: 1
  # labels:
  #   purpose: master
  #   size: cpx21
  # taints:
  #   something: value1:NoSchedule
worker_node_pools:
- name: small
  instance_type: cx21
  instance_count: 1
  # labels:
  #   purpose: worker
  #   size: cpx21
  # taints:
  #   something: GpuWorkloadsOnly:NoSchedule
- name: big
  instance_type: cx21
  instance_count: 1
additional_packages:
- somepackage
post_create_commands:
- apt update
- apt upgrade -y
- apt autoremove -y
- shutdown -r now
enable_encryption: true
# kube_api_server_args:
# - arg1
# - ...
# kube_scheduler_args:
# - arg1
# - ...
# kube_controller_manager_args:
# - arg1
# - ...
# kube_cloud_controller_manager_args:
# - arg1
# - ...
# kubelet_args:
# - arg1
# - ...
# kube_proxy_args:
# - arg1
# - ...
# existing_network: <specify if you want to use an existing network, otherwise one will be created for this cluster>
```

public key:
ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAkIUc3LW2Y35UDYBb9jNSLAnsfH0fcDQLq31o
fD9OvdP19ydyD4r0GVPAca3HP8k+x0qryz/NOO1ssXKMzLP5mbWLnBU7RtFf799a
Aap0VfV/YugoY4nkpwjSBZEFpZUjbdGSx/BnypqPz6n0cG0oxebA95bTQVoXa3Wn
CdKwRFopINDNdwUInce4PG8Y9VPiW2ZAqpJ3pqfdJdqHnE+vYg/2Rt68h7SIa8Eo
UacVxWHDtC6FTu3WARE/78P/Pxha/ElD14+5XCA2HHE9B2Lnei6GCsz6zZ4neVnY
jd6KP7xVzIyxmRFMMWddccxpQONyaPoWC/sE14FHqcVtz2UL6w== rsa-key-20221018
