### ISSUE TITLE
label issue

### ISSUE THREAD

**Issue by dyipon** [vitobotta/hetzner-k3s#119]
Hi,

I got error if I preset a label in config:
```
masters_pool:                                                                                                                                                            
  instance_type: cpx11                                                                                                                                                   
  instance_count: 3                                                                                                                                                      
  location: nbg1                                                                                                                                                         
  labels:                                                                                                                                                                
    node.kubernetes.io/exclude-from-external-load-balancers: "true"                                                                                                      
```

```
Unhandled exception: Expected sequence, not mapping at line 21, column 5 (YAML::ParseException)
  from /usr/share/crystal/src/yaml/nodes/nodes.cr:30:9 in 'raise'
  from /usr/share/crystal/src/yaml/from_yaml.cr:47:16 in 'new'
  from /usr/share/crystal/src/yaml/serialization.cr:187:7 in 'from_yaml'
  from /workspace/src/configuration/loader.cr:78:5 in 'new'
  from /workspace/src/hetzner-k3s.cr:23:25 in 'run:parent:program_name'
  from /workspace/src/hetzner-k3s.cr:10:3 in 'parse_and_run'
  from /workspace/src/hetzner-k3s.cr:96:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:115:5 in 'main'
  from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
```

Whats the correct way to label the nodes?

**Comment by vitobotta** [comment]
Hi, the `labels` key expects an array in the following format (as shown in the README):

```yaml
  labels:
    - key: node.kubernetes.io/exclude-from-external-load-balancers
      value: true
```

Can you try with this format?

**Comment by dyipon** [comment]
well, [readme](https://github.com/vitobotta/hetzner-k3s/blob/main/README.md) says:
```
schedule_workloads_on_masters: false
masters_pool:
  instance_type: cpx21
  instance_count: 3
  location: nbg1
  # labels:
  #   purpose: master
  #   size: cpx21
```

But the key/value pair you mentioned working fine, thanks!
