### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by dyipon** [vitobotta/hetzner-k3s#121]
Hi,

I get the next error message when creating cluster:
```
+ hetzner-k3s create --config create-cluster.yaml
Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Creating network...done.
Creating firewall...done.
Creating SSH key...done.
Creating placement group hetzner-k3s-masters...done.
Creating placement group hetzner-k3s-intel...done.
Creating server hetzner-k3s-cx11-pool-intel-worker1...
Creating server hetzner-k3s-cpx11-master1...
Creating server hetzner-k3s-cpx11-master2...
Creating server hetzner-k3s-cpx11-master3...
Creating server hetzner-k3s-cx11-pool-intel-worker2...
Creating server hetzner-k3s-cx11-pool-intel-worker3...
...server hetzner-k3s-cx11-pool-intel-worker3 created.
...server hetzner-k3s-cx11-pool-intel-worker1 created.
...server hetzner-k3s-cpx11-master1 created.
...server hetzner-k3s-cpx11-master3 created.
...server hetzner-k3s-cpx11-master2 created.
...server hetzner-k3s-cx11-pool-intel-worker2 created.
Waiting for server hetzner-k3s-cx11-pool-intel-worker3 to be ready...
Waiting for server hetzner-k3s-cx11-pool-intel-worker1 to be ready...
Waiting for server hetzner-k3s-cpx11-master1 to be ready...
Waiting for server hetzner-k3s-cpx11-master3 to be ready...
Waiting for server hetzner-k3s-cpx11-master2 to be ready...
Waiting for server hetzner-k3s-cx11-pool-intel-worker2 to be ready...
Unhandled exception in spawn: timeout after 00:00:05 (Tasker::Timeout)
  from /usr/share/crystal/src/array.cr:114:31 in 'execute!'
  from /workspace/lib/tasker/src/tasker.cr:29:7 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???

```

below you can find my config:
---
```
hetzner_token: xx
cluster_name: hetzner-k3s
kubeconfig_path: "./kubeconfig-hetzner.yaml"
k3s_version: v1.25.5+k3s1
public_ssh_key_path: ".ssh/hetzner.pub"
private_ssh_key_path: ".ssh/hetzner.key"
ssh_allowed_networks:
  - xx/32
  - yy/24
api_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: nbg1
schedule_workloads_on_masters: false
masters_pool:
  instance_type: cpx11
  instance_count: 3
  location: nbg1
  labels:
    - key: node.kubernetes.io/exclude-from-external-load-balancers
      value: true
worker_node_pools:
- name: intel
  instance_type: cx11
  instance_count: 3
  location: nbg1
```

How can I debug what can cause this timeout?

Almost same configuration worked with previous versions.
