### ISSUE TITLE
Unhandled exception: Missing YAML attribute: location at line 34, column 3 (YAML::ParseException)

### ISSUE THREAD

**Issue by cryptobench** [vitobotta/hetzner-k3s#127]
Hello! I noticed your post on /r/DevOps and I was curious to try out your project as i've been wanting to run kubernetes on hetzner for a long time.

I am struggling create a cluster with the example provided in the repository. Could you point me to the error?

This is the error happening when trying to create the cluster

```
Unhandled exception: Missing YAML attribute: location at line 34, column 3 (YAML::ParseException)
  from /opt/homebrew/Cellar/hetzner_k3s/1.0.1/bin/hetzner-k3s in 'raise<YAML::ParseException>:NoReturn'
  from /opt/homebrew/Cellar/hetzner_k3s/1.0.1/bin/hetzner-k3s in 'YAML::Nodes::Node+@YAML::Nodes::Node#raise<String>:NoReturn'
  from /opt/homebrew/Cellar/hetzner_k3s/1.0.1/bin/hetzner-k3s in 'Configuration::NodePool::new_from_yaml_node<YAML::ParseContext, YAML::Nodes::Node+>:Configuration::NodePool'
  from /opt/homebrew/Cellar/hetzner_k3s/1.0.1/bin/hetzner-k3s in 'Configuration::Main@Object::from_yaml<String>:Configuration::Main'
  from /opt/homebrew/Cellar/hetzner_k3s/1.0.1/bin/hetzner-k3s in 'Configuration::Loader::new<String, Nil>:Configuration::Loader'
  from /opt/homebrew/Cellar/hetzner_k3s/1.0.1/bin/hetzner-k3s in 'Hetzner::K3s::CLI::Create#run:Nil'
  from /opt/homebrew/Cellar/hetzner_k3s/1.0.1/bin/hetzner-k3s in 'Hetzner::K3s::CLI#parse_and_run:Nil'
  from /opt/homebrew/Cellar/hetzner_k3s/1.0.1/bin/hetzner-k3s in '__crystal_main'
  from /opt/homebrew/Cellar/hetzner_k3s/1.0.1/bin/hetzner-k3s in 'main'
```

```
---
hetzner_token: redacted
cluster_name: redacted
kubeconfig_path: "./kubeconfig"
k3s_version: v1.21.3+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
schedule_workloads_on_masters: false
masters:
  instance_type: cpx21
  instance_count: 3
  location: nbg1
  # labels:
  #   - key: purpose
  #     value: blah
  # taints:
  #   - key: something
  #     value: value1:NoSchedule
worker_node_pools:
- name: small
  instance_type: cpx21
  instance_count: 4
  location: nbg1
  # labels:
  #   - key: purpose
  #     value: blah
  # taints:
  #   - key: something
  #     value: value1:NoSchedule
- name: big
  instance_type: cpx31
  instance_count: 2
  location: nbg1
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 3
post_create_commands:
- apt update
- apt upgrade -y
- apt autoremove -y
- shutdown -r now
enable_encryption: true
# existing_network: <specify if you want to use an existing network, otherwise one will be created for this cluster>
# kube_api_server_args:
# - arg1
# - ...
# kube_scheduler_args:
# - arg1
# - ...
# kube_controller_manager_args:
# - arg1
# - ...
# kube_cloud_controller_manager_args:
# - arg1
# - ...
# kubelet_args:
# - arg1
# - ...
# kube_proxy_args:
# - arg1
# - ...


```
