### ISSUE TITLE
Ingress not serving SSL certificates

### ISSUE THREAD

**Issue by cryptobench** [vitobotta/hetzner-k3s#131]
I have followed all the guides you've provided, i've setup DNS01 challenges and they go through with no issues, but when i'm trying to access my website, then the SSL cert is not valid and presented as "Kubernetes Ingress Controller Fake Certificate"

Ingress should be configured properly and everything. It looks pretty much similar to the managed k8's ingress I configured on DigitalOcean. Do you have any clue as to what might be wrong here? 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-django
  namespace: deploy
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - staging.api.golemgrid.com
      - '*.golemgrid.com'
      - '*.golemgrid.app'
      secretName: letsencrypt-nginx-django-secret-2
  rules:
    - host: staging.api.golemgrid.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django
                port:
                  number: 8002
    - host: '*.golemgrid.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: internalproxy
                port:
                  number: 80
    - host: '*.golemgrid.app'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: internalproxy
                port:
                  number: 80
```

```
➜  GitHub kubectl get cert
NAME                                READY   SECRET                              AGE
letsencrypt-nginx-django-secret     True    letsencrypt-nginx-django-secret     18m
letsencrypt-nginx-django-secret-2   True    letsencrypt-nginx-django-secret-2   13m
```
