### ISSUE TITLE
How install a hetzner volume and share data across pods?

### ISSUE THREAD

**Issue by cryptobench** [vitobotta/hetzner-k3s#132]
I read the README and as far as I understood, you do some magic to share the volume between all pods. Is that correctly understood?

I am having some trouble provisioning this, and this is the PVC i've tried creating

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediafiles
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
```

And in my deployment:

```
...
    spec:
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: mediafiles
      restartPolicy: Always
      containers:
      - name: stats-backend
        volumeMounts:
          - mountPath: "/data"
            name: media-storage
...
```

But my container stays in a creating state, so I must be doing something wrong. Any clue to what i'm doing wrong?
