### ISSUE TITLE
Nodes stay with "uninitialized" taint

### ISSUE THREAD

**Issue by promofu** [vitobotta/hetzner-k3s#133]
After new creations my nodes seem to never change to uniitialized: false

![image](https://user-images.githubusercontent.com/4403465/210667147-b5378ea4-290f-4885-b381-89ccc162a07a.png)

I tried with v1.0.2 and v0.7.0 as well as with several versions of k3s.

As a result I am not able to start any Pod ... even coredns does stay in Pending:

![image](https://user-images.githubusercontent.com/4403465/210668032-7ad9f921-43fe-42e8-a28c-4516e054dfca.png)

![image](https://user-images.githubusercontent.com/4403465/210668571-673fbff0-7edf-4ad8-afdc-2b18b3e5b4c0.png)

Anything I am missing here ? Or am I too impatient ;-) ... would CPX21 nodes take more than 5 minutes to be "up"

**Comment by vitobotta** [comment]
No, nodes should be ready within a minute. Can you share your config file? (remember to remove the token!)

**Comment by promofu** [comment]
This is my playground yaml

```
hetzner_token: <...>
cluster_name: sandbox
kubeconfig_path: "./sandbox/kubeconfig"
k3s_version: v1.25.5+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
use_ssh_agent: false
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0

schedule_workloads_on_masters: false
masters_pool:
  instance_type: cpx21
  instance_count: 1
  location: nbg1
  # labels:
  #   - key: purpose
  #     value: blah
  # taints:
  #   - key: something
  #     value: value1:NoSchedule
worker_node_pools:
- name: small
  instance_type: cpx21
  instance_count: 2
  location: nbg1
  # labels:
  #   - key: purpose
  #     value: blah
  # taints:
  #   - key: something
  #     value: value1:NoSchedule
#- name: big
#  instance_type: cpx31
#  instance_count: 2
#  location: fsn1
additional_packages:
#- somepackage
post_create_commands:
- apt update
- apt upgrade -y
- apt autoremove -y
- shutdown -r now
enable_encryption: true

# existing_network: <specify if you want to use an existing network, otherwise one will be created for this cluster>
# kube_api_server_args:
# - arg1
# - ...
# kube_scheduler_args:
# - arg1
# - ...
# kube_controller_manager_args:
# - arg1
# - ...
# kube_cloud_controller_manager_args:
# - arg1
# - ...
# kubelet_args:
# - arg1
# - ...
# kube_proxy_args:
# - arg1
# - ...
```
