### ISSUE TITLE
CPX31 "big" instances getting created and deleted by itself

### ISSUE THREAD

**Issue by cryptobench** [vitobotta/hetzner-k3s#138]
Heya! Back again with another issue. 

I created my cluster last week, and I was wondering why I couldn't see the "big" CX31 instances, but I continued on with my day. Today I received an email about this new instance being created and how to access it, but when I went into the Hetzner UI , nothing was to be seen.

Few hours later and I receive a new message about it being created and available, and I got into the UI and I can see it! Then shortly after the big machine are deleted. 

I have not run the `hetzner-k3s` tool, so i'm wondering how all of this is happening. Any clue? 

This is the config i'm using:

```
masters_pool:
  instance_type: cpx21
  instance_count: 3
  location: nbg1
  # labels:
  #   - key: purpose
  #     value: blah
  # taints:
  #   - key: something
  #     value: value1:NoSchedule
worker_node_pools:
- name: small
  instance_type: cpx21
  instance_count: 4
  location: nbg1
  # labels:
  #   - key: purpose
  #     value: blah
  # taints:
  #   - key: something
  #     value: value1:NoSchedule
- name: big
  instance_type: cpx31
  instance_count: 2
  location: nbg1
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 3
```
