### ISSUE TITLE
Installation timing out

### ISSUE THREAD

**Issue by kubeworkz** [vitobotta/hetzner-k3s#141]
Hi:

I'm doing a fresh install and I get the following error after about 15 minutes:
```
osboxes@osboxes-VirtualBox:~/k3s$ hetzner-k3s create --config config.yaml 
Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Creating network...done.
Creating firewall...done.
Creating SSH key...done.
Creating placement group cloudrock-masters...done.
Creating placement group cloudrock-small...done.
Creating server cloudrock-cpx11-master1...
Creating server cloudrock-cx41-pool-small-worker1...
Creating server cloudrock-cx41-pool-small-worker3...
Creating server cloudrock-cx41-pool-small-worker2...
...server cloudrock-cx41-pool-small-worker3 created.
...server cloudrock-cx41-pool-small-worker1 created.
...server cloudrock-cx41-pool-small-worker2 created.
...server cloudrock-cpx11-master1 created.
Waiting for server cloudrock-cx41-pool-small-worker3...
Waiting for server cloudrock-cx41-pool-small-worker1...
Waiting for server cloudrock-cx41-pool-small-worker2...
Waiting for server cloudrock-cpx11-master1...
Unhandled exception in spawn: timeout after 00:00:05 (Tasker::Timeout)
  from /usr/share/crystal/src/array.cr:114:31 in 'execute!'
  from /workspace/lib/tasker/src/tasker.cr:29:7 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
Unhandled exception in spawn: timeout after 00:00:05 (Tasker::Timeout)
  from /usr/share/crystal/src/array.cr:114:31 in 'execute!'
  from /workspace/lib/tasker/src/tasker.cr:29:7 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
Unhandled exception in spawn: timeout after 00:00:05 (Tasker::Timeout)
  from /usr/share/crystal/src/array.cr:114:31 in 'execute!'
  from /workspace/lib/tasker/src/tasker.cr:29:7 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
Unhandled exception in spawn: timeout after 00:00:05 (Tasker::Timeout)
  from /usr/share/crystal/src/array.cr:114:31 in 'execute!'
  from /workspace/lib/tasker/src/tasker.cr:29:7 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```

My config file is:
```
---
hetzner_token: <my token>
cluster_name: cloudrock
kubeconfig_path: "/cluster/kubeconfig"
k3s_version: v1.25.5+k3s1
public_ssh_key_path: "~/.ssh/kubeworkz.pub"
private_ssh_key_path: "~/.ssh/kubeworkz"
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
schedule_workloads_on_masters: false
masters_pool:
  instance_type: cpx11
  instance_count: 1
  location: hel1
worker_node_pools:
- name: small
  location: hel1
  instance_type: cx41
  instance_count: 3
```
I also tried different k3s versions and Hetzner locations.
