### ISSUE TITLE
Autoscaling node pools

### ISSUE THREAD

**Issue by aleksasiriski** [vitobotta/hetzner-k3s#143]
How is autoscaling handled if a node pool has: `instance_count: 2` and autoscaling:
```
autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 3
```
Does that mean it will create 2 nodes and then autoscale to 0 if nothing is being ran on them or is `instance_count` the actual minimum?
