### ISSUE TITLE
Multiple master pools?

### ISSUE THREAD

**Issue by aleksasiriski** [vitobotta/hetzner-k3s#144]
Is there a way to have multiple master pools? I don't see `-` so I don't think it accepts an array like workers do.

Usage for this would be, instead of 1 master pool in one location with 3 masters, you could have 3 pools in 3 different locations and each location would have a single node.

**Comment by aleksasiriski** [comment]
Also, I still get hangs when when using rocky-9 and microos with snapshot made with packer tool.
![image](https://user-images.githubusercontent.com/31509435/212570013-24bfa0bb-fe07-4a29-9d93-3705ad21a40f.png)

```yaml
---
hetzner_token: *redacted*
cluster_name: tmina
kubeconfig_path: "./kubeconfig"
k3s_version: v1.25.5+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
use_ssh_agent: false
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
schedule_workloads_on_masters: false
image: rocky-9 # tried with snapshot ID and uncommented line below
# snapshot_os: microos
masters_pool:
  instance_type: cpx21
  instance_count: 1
  location: nbg1
worker_node_pools:
- name: small
  instance_type: cpx21
  instance_count: 2
  location: nbg1
```

It works with this config
![image](https://user-images.githubusercontent.com/31509435/212570186-3391690b-3c58-48fe-bcfd-139e23707c7e.png)

```yaml
---
hetzner_token: *redacted*
cluster_name: tmina
kubeconfig_path: "./kubeconfig"
k3s_version: v1.25.5+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
use_ssh_agent: false
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
schedule_workloads_on_masters: false
# image: rocky-9 # default ubuntu-22.04
# snapshot_os: microos
masters_pool:
  instance_type: cpx11
  instance_count: 1
  location: nbg1
worker_node_pools:
- name: small
  instance_type: cpx21
  instance_count: 2
  location: nbg1
```
