### ISSUE TITLE
Installation Hanging

### ISSUE THREAD

**Issue by dclayton77** [vitobotta/hetzner-k3s#150]
I am trying to create a new cluster.  I have added a project to Hetzner, created a API key and tried to run the create command using the yaml provided in your example on the main page.  The only difference is that I have added my api key.  The installation never completes and just sits waiting for the servers.  I can see in Hetzner that the objects have all been created.

Am I missing something obvious?

![image](https://user-images.githubusercontent.com/28646129/214688807-2b3102c8-46ea-4d20-bbc4-333e8391c884.png)

**Comment by vitobotta** [comment]
Hi, there is likely a problem with your key. If you are using an old type RSA key this happens because SHA1 has been deprecated in Ubuntu 22 (which is the default used by the tool) and other tools. I recommend you create new ed25519 keys and create a new cluster in a new project. There is a workaround with old keys but since you haven't used this cluster yet anyway it's easier to create a new one.

**Comment by dclayton77** [comment]
Thanks for your response, I will look into the keys and try again.  Will post back my findings.

**Comment by dclayton77** [comment]
I was using a Ubuntu 20.04 distro on WSL.  I created a 22.04 distro, created a new project on Hetzner and used the yaml file from your blog.  It gets further but still gets stuck on the third master?

![image](https://user-images.githubusercontent.com/28646129/214697796-5ab70563-e496-481e-b5e6-899129e26e78.png)

**Comment by vitobotta** [comment]
Which key are you using now? Did you try with an ed25519 key?

**Comment by dclayton77** [comment]
Sorry, yes I am using a ed25519 key

**Comment by dclayton77** [comment]
Dropped the master pool to 1 and it now installs K8S

**Comment by vitobotta** [comment]
Did you just change the masters instance count from 3 to 1? if yes you need to delete the extra masters manually from the Hetzner console.

**Comment by dclayton77** [comment]
I deleted the entire cluster, then updated the yaml to specify just one master.  That worked successfully.  It just fails with masters set to 3.

**Comment by vitobotta** [comment]
When you changed the key, did you try creating a new cluster with 3 masters or did you try to update the existing one?

**Comment by psavva** [comment]
@vitobotta   I'm creating a brand new cluster on Hetzner and am facing the same issue as described in this ticket.

My config file is below: 
```
---
hetzner_token: <REDACTED>
cluster_name: siliconcloud
kubeconfig_path: "./kubeconfig"
k3s_version: v1.26.1+k3s1
public_ssh_key_path: "~/.ssh/id_ed25519.pub"
private_ssh_key_path: "~/.ssh/id_ed25519"
use_ssh_agent: true
ssh_allowed_networks:
- <REDACTED>/32
- <REDACTED>/24
- <REDACTED>/32
api_allowed_networks:
- 0.0.0.0/0
schedule_workloads_on_masters: true
enable_encryption: true
masters_pool:
  instance_type: cpx21
  location: nbg1
  instance_count: 3
worker_node_pools:
- name: autoscaled-nbg1-cx21
  instance_type: cpx21
  location: nbg1
  instance_count: 0
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 2
```

I have generated my ssh keys as such: `ssh-keygen -t ed25519`

This is the output from hetzner-k3s
```
$ hetzner-k3s create --config cluster.yaml
Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Network already exists, skipping.
Creating firewall...done.
SSH key already exists, skipping.
Creating placement group siliconcloud-masters...done.
Creating server siliconcloud-cpx21-master1...
Creating server siliconcloud-cpx21-master3...
Creating server siliconcloud-cpx21-master2...
...server siliconcloud-cpx21-master1 created.
...server siliconcloud-cpx21-master3 created.
...server siliconcloud-cpx21-master2 created.
Waiting for server siliconcloud-cpx21-master1...
Waiting for server siliconcloud-cpx21-master3...
Waiting for server siliconcloud-cpx21-master2...

Unhandled exception in spawn: timeout after 00:00:05 (Tasker::Timeout)
  from /workspace/lib/tasker/src/tasker/timeout.cr:37:9 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
Unhandled exception in spawn: timeout after 00:00:05 (Tasker::Timeout)
  from /workspace/lib/tasker/src/tasker/timeout.cr:37:9 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
Unhandled exception in spawn: timeout after 00:00:05 (Tasker::Timeout)
  from /workspace/lib/tasker/src/tasker/timeout.cr:37:9 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
