### ISSUE TITLE
Infinite wait loop

### ISSUE THREAD

**Issue by tomsiwik** [vitobotta/hetzner-k3s#154]
I'm running Debian-11 nodes and v1.0.7 of this cli with the following config (using ecdsa ssh keys):

```
hetzner_token: "${HCLOUD_TOKEN}"
cluster_name: "${CLUSTER_NAME}"
kubeconfig_path: "./kubeconfig"
k3s_version: v1.26.1+k3s1
public_ssh_key_path: "${SSH_PUBLIC_KEY_PATH}"
private_ssh_key_path: "${SSH_PRIVATE_KEY_PATH}"
use_ssh_agent: false
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
schedule_workloads_on_masters: false
image: debian-11
masters_pool:
  instance_type: cpx21
  instance_count: 3
  location: nbg1
worker_node_pools:
- name: small
  instance_type: cpx21
  instance_count: 2
  location: fsn1
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 3
```

The first 'setup' runs smoothly and waits a short time until every master node is up.
I have this same config on the CI... so when rerunning `hetzner-k3s create --config config.yaml` the second run it infinitely waits for the master nodes (CI has a timeout for 30min. and it reached it). The servers are up and running but apparently the echo is never returned? Not sure how to go about this. Hope you can help.

```
=== Creating infrastructure resources ===
Network already exists, skipping.
Updating firewall...done.
SSH key already exists, skipping.
Placement group test-masters already exists, skipping.
Server test-cpx21-master1 already exists, skipping.
Server test-cpx21-master3 already exists, skipping.
Server test-cpx21-master2 already exists, skipping.
Waiting for server test-cpx21-master1...
Waiting for server test-cpx21-master3...
Waiting for server test-cpx21-master2...
```

+thanks for this cli... it reduces a lot of headaches with my current ansible and hetzner python scripts.
