### ISSUE TITLE
Multi-Location Cluster deployment

### ISSUE THREAD

**Issue by manfredipist** [vitobotta/hetzner-k3s#165]
Hi, first of all, I'd like to thank you for the amazing work @vitobotta! This project is outstanding! Secondly I'm having issues deploying a multi-location cluster, in particular I'd like to have workers nodes deployed over different regions to avoid a single location-based point of failure. With the configuration provided the nbg-worker nodes don't get deployed, either the servers created but I don't understand why. 
Shouldn't the script respect the min_instances count despite of autoscaling needs?

With the current configuration I expect to have:
1 master in fsn1
1 worker in fsn1
1 worker in nbg1

Eventually it should automatically scale to :
1 master in fsn1
2 worker in fsn1
2 worker in nbg1

But my current situation is:
1 master in fsn1
1 worker in fsn1

Thanks for your help

```yaml
hetzner_token: xxxxxx
cluster_name: xxx-cluster
kubeconfig_path: "./kubeconfig"
k3s_version: v1.25.5+k3s1
public_ssh_key_path: "~/.ssh/xxx.pub"
private_ssh_key_path: "~/.ssh/xxx_rsa"
use_ssh_agent: false
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
schedule_workloads_on_masters: false
# image: rocky-9 # optional: default is ubuntu-22.04
# snapshot_os: microos # otional: specified the os type when using a custom snapshot
masters_pool:
  instance_type: cx21
  instance_count: 1
  location: fsn1
worker_node_pools:
- name: fsn-worker
  instance_type: cx21
  instance_count: 1
  location: fsn1
  autoscaling:
    enabled: true
    min_instances: 1
    max_instances: 2
- name: nbg-worker
  instance_type: cx21
  instance_count: 1
  location: nbg1
  autoscaling:
    enabled: true
    min_instances: 1
    max_instances: 2
```
EDIT 2: I've got another question, is it possible to also deploy master nodes in different locations ? Something like the following
```yaml
masters_pool:
- name: fsn-master
    instance_type: cx11
    instance_count: 2
    location: fsn1
- name: nbg-master
    instance_type: cx11
    instance_count: 1
    location: nbg1
```

**Comment by vitobotta** [comment]
Hi,

for question 1, the scaling depends on the resources required in the cluster. If only one worker node is created in only one pool, than maybe there are enough resources for what you are running now. Is the autoscaler pod running? (in kube-system)

question 2: it's on my list to be implemented as soon as I have time, maybe next weekend.

**Comment by manfredipist** [comment]
Hi, thanks for your response!
Regarding question 1: autoscaler is running flawlessly on kube-system. My only concern was that I had set a min instance count of 1 for both the 2 different workers, thus I expected to have 2 workers pods regardless of the circumstances. So it's just normal that min_instance_count is not binding and autoscaler will do its job depending on resources consumption

Regardign question 2: great! ty for the update

**Comment by vitobotta** [comment]
The autoscaler should always create one node if min instances is set to 1. If you try and deploy something that requires more resources than available on 2-3 nodes does it create nodes on that node pool?

**Comment by manfredipist** [comment]
So I've actually tried to deploy 100 pods and autoscaler deployed one more node into the pool but within the same location. 
So in my example:

I expected  to have:
1 master in fsn1
1 worker in fsn1
1 worker in nbg1

 I have:
1 master in fsn1
1 worker in nbg1

I deployed 100 pods  and now I have
1 master in fsn1
2 worker in nbg1

The server in fsn1 doesn't exist at all in my hetzner profile page though

**Comment by vitobotta** [comment]
And  you configured resource requests? The autoscaler decides where to create nodes if you have multiple pools, it's not something we can control

**Comment by manfredipist** [comment]
nope I haven't configured any resource request, is that mandatory? 

By the way I think the problem is somewhere else, here we're talking about deployments thus given the cluster_config I shared with you earlier, I should have already a working worker node in  fsn1, as I've specified that I want two autoscaling workers with **at least** 1 instance in both fsn1 and ngb1 but this is not the case.

Could you try to setup a cluster with my same config and see If both the workers get deployed? I've not exceeded servers limit for my accounts (3 actives out of 10) so I don't really get why the second worker server doesn't get instantiated. 

As always, thanks for your support!

**Comment by vitobotta** [comment]
> nope I haven't configured any resource request, is that mandatory?

Basically yes, if you want to avoid problems. If you don't specify resource requests, the schedule can create more pods than it should on the same node because it doesn't know how much memory they need. So if they use a lot of memory, the memory of the node might be exhausted leading to the problem you are having now. If you specify memory requests instead, the schedule is clever enough to create nodes required to accommodate each pod's needs.

**Comment by vitobotta** [comment]
The autoscaling _requires_ memory requests to be specified, btw.

**Comment by manfredipist** [comment]
Ok so I've configured the resource requests and it's finally working as expected! 

Please clarify me one more thing, your autoscaler works both as horizontal and vertical scaler right? I don't need to define any HPA for my pods, once limit resources are reached, new pods will be automatically instantiated, if there's no more room in that node a new node will be created, right?

For other people who's gonna look for the same problem this is my configuration for a nodejs app:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace:production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app:: my-app
    spec:
      containers:
        - name: my-app
          image: my-registry:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9021
          envFrom:
            - configMapRef:
                name: my-config
          livenessProbe:
            httpGet:
              path: /index
              port: 9021
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 3
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
      imagePullSecrets:
         - name: my-secret
```
