### ISSUE TITLE
Nodes randomly become unavailable and freezes the whole cluster

### ISSUE THREAD

**Issue by cryptobench** [vitobotta/hetzner-k3s#168]
For some reason I sometimes experience that the cluster freezes even though I try to deploy everything with HA in mind. When investigating the issue I can see that multiple nodes or sometimes even a single one just got into a "Not ready" state , which causes the cluster to freeze up

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/33448819/222252558-c9178d8a-fac9-4b54-bb08-738894b5d06b.png">
(Ignore the full load visualization below. Its just due to the metrics server not being available and reporting infinity)
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/33448819/222252669-00defe0a-321e-4f63-9060-557f100c4909.png">

What's even more weird is that if I check the graphs for the not ready nodes on hetzner, then they look incredibly busy

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/33448819/222252764-25ce8236-56fb-45b9-8d60-138c2a4a9cae.png">

Do you have any idea what could be causing this? I can't really find any pattern in this. 

This is my config 

```
---
hetzner_token: blablabla
cluster_name: blablalba
kubeconfig_path: "./kubeconfig"
k3s_version: v1.24.9+k3s1
public_ssh_key_path: "./id_ed25519.pub"
private_ssh_key_path: "./id_ed25519"
ssh_allowed_networks:
    - 0.0.0.0/0
api_allowed_networks:
    - 0.0.0.0/0
schedule_workloads_on_masters: false
masters_pool:
    instance_type: cpx21
    instance_count: 3
    location: nbg1
worker_node_pools:
    - name: small
      instance_type: cpx21
      instance_count: 4
      location: nbg1
      labels:
          - key: workertype
            value: general
    - name: big
      instance_type: cpx31
      instance_count: 2
      labels:
          - key: workertype
            value: general
      location: nbg1
      autoscaling:
          enabled: true
          min_instances: 0
          max_instances: 3

    - name: dbprimary
      instance_type: cpx21
      instance_count: 1
      labels:
          - key: workertype
            value: dbprimary
      location: nbg1
    - name: dbreplica
      instance_type: cx21
      instance_count: 2
      labels:
          - key: workertype
            value: dbreplica
      location: nbg1
enable_encryption: true



``` 

My version of your tool is 1.1.0
