### ISSUE TITLE
ssh-key is not installed on worker nodes

### ISSUE THREAD

**Issue by TLINDEN** [vitobotta/hetzner-k3s#173]
I can ssh into the master nodes, but not the worker nodes. I've got to reset the root password and install the ssh key manually.

**Comment by vitobotta** [comment]
Can you share your config file?

**Comment by TLINDEN** [comment]
Here it is:
```yaml
---
hetzner_token: ***
cluster_name: tarantula
kubeconfig_path: "./kubeconfig"
k3s_version: v1.25.5+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
use_ssh_agent: false
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
private_network_subnet: 10.0.0.0/16
schedule_workloads_on_masters: false
image: debian-10
masters_pool:
  instance_type: cpx11
  instance_count: 3
  location: nbg1
  labels:
     - key: hetzner-node-type
       value: master
worker_node_pools:
- name: pool-cpx11
  instance_type: cpx11
  instance_count: 1
  location: hel1
  labels:
     - key: hetzner-node-type
       value: node
  autoscaling:
    enabled: true
    min_instances: 1
    max_instances: 3
```
