### ISSUE TITLE
Best way to scale to high # of nodes

### ISSUE THREAD

**Issue by Niek** [vitobotta/hetzner-k3s#200]
Right now it appears the maximum value of `instance_count` is `10`. If set to a higher number, it errors with:
```
  - workers cannot have more than 10 nodes due to a limitation with the Hetzner placement pools. You can add more node pools if you need more nodes.
```

This corresponds to the limits listed here: https://docs.hetzner.com/cloud/placement-groups/overview/#limits

I can split in node pools of size 10 each, but there are max 50 placement groups per project allowed, so the absolute theoretical maximum is 500 nodes. The YAML file looks like a mess though with 50 identical pools.

Is there any other way to scale a cluster to a high number of nodes? Can we skip the whole idea of placement groups and use key-value labels instead? Or is are multiple clusters (each in their own project) the way to go?

**Comment by vitobotta** [comment]
I just fixed this while still keeping the placement groups (which are useful to guarantee higher availability). With the next version I will release today or tomorrow the tool creates as many placement groups as needed and you can specify pools with any number of nodes with this change (of course remember that your account has a limit to the number of servers that you can create and you may have to request an increase).

I will update this again when I have released the new version.

**Comment by vitobotta** [comment]
@Niek I just released v1.1.1 that removes that restriction. You can now specify node pools with more than 10 nodes :)

Feel free to reopen if we encounter issues with it.

**Comment by Niek** [comment]
Wow, amazing work! Thanks @vitobotta 🙏

**Comment by Niek** [comment]
I just tested but saw this:
```bash
$ hetzner-k3s --version
1.1.1
$ hetzner-k3s create --config hetzner.yaml
Validating configuration......configuration seems valid.
-snip-
Creating server hetzner-cpx21-pool-node-4g-3amd-worker18...
Failed to create server: HTTP status code 422: Unprocessable Entity
{
  "error": {
    "message": "placement group 123456 contains already 10 servers",
    "code": "service_error",
    "details": null
  }
}
```

Maybe I'm missing something?

**Comment by vitobotta** [comment]
Can you share your config? is this a new cluster or an existing one?

**Comment by Niek** [comment]
It's an existing cluster, fairly simple config:
```yaml
hetzner_token: -snip-
cluster_name: hetzner
kubeconfig_path: "~/Documents/kubeconfig-hetzner.yaml"
k3s_version: v1.26.3+k3s1 # Run: hetzner-k3s releases | grep -v \\-rc | tail -1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0

schedule_workloads_on_masters: false
masters_pool:
  instance_type: cpx11
  instance_count: 1
  location: fsn1

worker_node_pools:
- name: node-4g-3amd
  instance_type: cpx21
  instance_count: 20
  location: fsn1

post_create_commands:
- apt update
- apt upgrade -y
- apt autoremove -y
- shutdown -r now
enable_encryption: true
```

Should I delete it and start fresh?

**Comment by vitobotta** [comment]
Wait before deleting, I'd  like to understand what's the issue. Can you please tell me the names of the current placement groups and how many servers each has? Thanks

**Comment by Niek** [comment]
I have 10 servers in the placement group called `hetzner-node-4g-3amd`, when I run the script it creates a new group `hetzner-node-4g-3amd-1` (0 servers) just before erroring. Hope this helps!

**Comment by vitobotta** [comment]
Weird, existing placement groups shouldn't affect the new functionality since the names are in a different format. I will check as soon as I have some time.

**Comment by vitobotta** [comment]
Hi, can you tell me the names of the existing placement groups and how many servers each has? Thanks

**Comment by vitobotta** [comment]
Hu @Niek - are you still having issues with this or can we close?

**Comment by Niek** [comment]
We issue is still here, but even if we scale outside 10 nodes there's still the issue that Hetzner allows only 100 IPs per network group. So closing this for now.

**Comment by vitobotta** [comment]
> Hetzner allows only 100 IPs per network group. So closing this for now.

What do you mean? Any reference?

**Comment by Niek** [comment]
> > Hetzner allows only 100 IPs per network group. So closing this for now.
> 
> What do you mean? Any reference?

Sure! See here: https://docs.hetzner.com/de/cloud/networks/overview/#limits

Also the discussion here: https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/730

**Comment by vitobotta** [comment]
That makes me *very* sad. This limits things considerably :(

**Comment by Niek** [comment]
It's very unfortunate indeed... I tried several times to reach our to their support, but these are hard limits that they don't want to raise. The only solution is: more powerful nodes so you can run more pods per node.

**Comment by vitobotta** [comment]
How is it possible that they limit to just 100 ips?? that doesn't make any sense to me. Very disappointing. I was going to propose Hetzner at work too to save costs compared with GCP which we use now, but looks like I can't. I am glad that you raised this, thanks for the information! You just helped me avoid a very bad mistake.

**Comment by Niek** [comment]
I don't want to trash Hetzner, because their pricing is amazing, but to be honest I would *not* recommend to run any production application on their cloud servers.

Not only the scaling is an issue, their abuse department is extremely aggressive. They have locked multiple of my servers at multiple times because they thought outgoing netscan activity was going on, while it was merely an in-house service being pinged. They even refused to unlock a couple of servers.

In addition to that, I received a complaint from their "blacklist team" last week that CPU usage on cloud servers was "too high". To quote their email:
> permanent CPU usage is not allowed, not even at 70% or 60%, because even in this time the CPU cannot be used by other customers

Note that none of their policies state anything about using too much CPU... The only solution they offered: switch to dCPUs or dedicated servers.

Sorry for the rant, but after these issues I'm not actively recommending Hetzner anymore - at least their cloud product.

**Comment by vitobotta** [comment]
I might still suggest Hetzner for the sandbox/dev cluster because it would reduce cost by 90% for us. That environment is not too critical. Anyway, very disappointed and sad

**Comment by vitobotta** [comment]
@Niek I am thinking of ways to work around this limitation and I am thinking of doing something like ZeroTier between nodes using the public network interface instead of the private network.

I love ZeroTier because it allows me to configure a VPN across all my devices without any firewall setup. I will see if it's possible to set up something like this in a programmatic way.

**Comment by Niek** [comment]
@vitobotta I thought about that as well (but using Wireshark instead of ZeroTier). It can probably work, but I'm not sure how much traffic would go over it and how much of an effect it has on the bandwidth limits (20TB for cloud) - assuming the pods don't communicate too much with each other, only the control plane.

**Comment by vitobotta** [comment]
I found a potential solution that seems easy to set up https://github.com/juanfont/headscale

This would allow a fast mesh with minimal configuration and firewalling. It just requires an additional vps to act as control server and that's it

**Comment by vitobotta** [comment]
k3s has support for Tailscale! and the devs on Slack say that the next release will even support Headscale, so this might be the perfect solution to the problem.

**Comment by hroost** [comment]
Maybe this one also may help https://github.com/gravitl/netmaker for mesh network

**Comment by vitobotta** [comment]
> Maybe this one also may help https://github.com/gravitl/netmaker for mesh network. Easy to setup and use. Same requirements: you need a minimal server for control

Looks interesting, thanks!

**Comment by clouedoc** [comment]
I tried netmaker, but had a bad experience with it.
Their new user interface lacks lots of functionality, and I couldn't get access to my cluster.
The Kubernetes documentation is outdated.

Tailscale worked OK when I used it on a cluster a while ago, but it was a bit unreliable.
This might be because of my own network, and they might have improved since.

So, here is my attempt at mesh networking for the 13th time in 24 hours!

# don't follow this guide or you'll break your cluster.
# I'm only posting this for future adventurers

## Installing Tailscale on existing nodes 👌

**EDIT**: do not bother using my script. Edit `worker_install_script.sh` instead, it'll be easier, and also, it'll skip control-plane nodes for more peace of mind.

```bash
#!/bin/bash

# filename: tailscale.sh

# This script installs Tailscale + utilities on nodes I need.

export NODE_NAME=$1

if [ -z "$NODE_NAME" ]; then
	echo "Usage: $0 <node-name>"
	exit 1
fi

echo "Installing Tailscale on $NODE_NAME"

kubectl node-shell $NODE_NAME <<EOF
	# exit if the "tailscale" command already exists
	which tailscale && echo ------------- TAILSCALE ALREADY INSTALLED ------------------ && exit 0

	echo ----------- TAILSCALE NOT INSTALLED, INSTALLING -----------------

	apt-get update
	apt-get install -y unattended-upgrades update-notifier-common
	systemctl enable unattended-upgrades && systemctl start unattended-upgrades
	curl -fsSL https://tailscale.com/install.sh | sh
EOF


```

To run the script on all nodes:

```bash
kubectl get nodes -o jsonpath='{.items[*].metadata.name}' | xargs -n 1 -P 5 -I {} bash tailscale.sh {}
```

## Installing Tailscale on new nodes 🤷‍♂️

YAML macro for the node pools, to avoid having to run the script.

```yaml
  # 8 CPU, 32GB ram, 40EUR/month
  - name: foundation-servers
    instance_type: ccx32
    instance_count: 5
    location: hel1
    additional_packages: &additional_packages
      - unattended-upgrades
      - update-notifier-common
    post_create_commands: &post_create_commands
      - sudo systemctl enable unattended-upgrades
      - sudo systemctl start unattended-upgrades
      - curl -fsSL https://tailscale.com/install.sh | sh
  - name: ns-qr-dedi
    instance_count: 1
    instance_type: cx51
    location: hel1
    labels:
      - key: node-role.kubernetes.io/ns-queue-refresh
        value: 'true'
    taints:
      - key: ReservedFor
        value: ns-queue-refresh:PreferNoSchedule
    additional_packages: *additional_packages
    post_create_commands: *post_create_commands
```

## Integrating Tailscale with k3s 👀

**WARNING:** this is where I broke my cluster, promised myself to never try a VPN on a production cluster again, and gave up

k3s requires adding a CLI argument to join the Tailscale mesh.

Here is a link to the documentation: https://docs.k3s.io/installation/network-options#integration-with-the-tailscale-vpn-provider-experimental

> To deploy K3s with Tailscale integration enabled, you must add the following parameter on each of your nodes:
> `--vpn-auth="name=tailscale,joinKey=$AUTH-KEY"`

I tried using the `kubelet_args` option but I get `[INFO]  No change detected so skipping service start`

So, to make things easier for me, I edited `worker_install_script.sh` like this:
