### ISSUE TITLE
support for new ampere servers

### ISSUE THREAD

**Issue by WladyX** [vitobotta/hetzner-k3s#204]
Tried a cax11 instance type and it gave an error:
```
Creating server test-cax11-master3...
Failed to create server: HTTP status code 412: Precondition Failed
{
  "error": {
    "message": "error during placement",
    "code": "resource_unavailable",
    "details": null
  }
}
```
Think it would be very cool to add support for these new cheap server types.

**Comment by WladyX** [comment]
New/fresh cluster.

**Comment by vitobotta** [comment]
Does it happen again if you re-run the create command? Also please your config (minus the token of course)

**Comment by WladyX** [comment]
ran it for a few times one after another, same error each time.
```
cluster_name: test
kubeconfig_path: "./kubeconfig"
k3s_version: v1.25.5+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
use_ssh_agent: true
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
private_network_subnet: 10.0.0.0/16
schedule_workloads_on_masters: true
masters_pool:
  instance_type: cax11
  instance_count: 3
  location: nbg1
worker_node_pools:
- name: small-static
  instance_type: cax11
  instance_count: 1
  location: nbg1
- name: big-autoscaled
  instance_type: cpx31
  instance_count: 0
  location: fsn1
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 3
```
