### ISSUE TITLE
New ARM worker node images not matching architecture (autoscaler)

### ISSUE THREAD

**Issue by carlesjavierre** [vitobotta/hetzner-k3s#207]
Hello and thanks for actively maintaining this amazing project!

Here's a few log lines of the issue. It's on the cluster-autoscaler.

![image](https://user-images.githubusercontent.com/12613547/234369558-66e4955a-971b-489d-b3c8-c3a04e6f6a20.png)

The master node is created correctly, but no workers are created. It works ONLY when I create them from your script.

I've inspected the HCLOUD API and it seems like whenever you search for ubuntu, the ARM image is on the second page. Maybe since the one creating it is the cluster autoscaler it doesn't know the architecture it goes for the first one it finds? Maybe there's an architecture parameter that can be defined on the cluster-autoscaler?

This is the configuration I have on my cluster, if that helps you replicate the issue:

```yaml
hetzner_token: token
cluster_name: cluster
kubeconfig_path: "./kubeconfig"
k3s_version: v1.26.2+k3s1
public_ssh_key_path: "~/.ssh/id_ed25519.pub"
private_ssh_key_path: "~/.ssh/id_ed25519"
use_ssh_agent: false
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
private_network_subnet: 10.0.0.0/16
schedule_workloads_on_masters: false
image: ubuntu-22.04
masters_pool:
  instance_type: cax11
  instance_count: 1
  location: fsn1
worker_node_pools:
- name: small-autoscaled
  instance_type: cax21
  instance_count: 1
  location: fsn1
  autoscaling:
    enabled: true
    min_instances: 1
    max_instances: 5
```
