### ISSUE TITLE
Endlessly waiting on a random server

### ISSUE THREAD

**Issue by EnessenE** [vitobotta/hetzner-k3s#210]
I have an odd issue I cant figure out. (Below the config and the yaml I am expirmenting with). I am using 1.1.2.

Everytime I deploy a cluster (this is attempt 3). It keeps randomly waiting for one of the worker nodes. It randomly just hangs on "waiting for server" at one of the nodes. Waiting a 3-10 minutes and/or rebooting the server doesn't help. Anything obvious I am missing?

```
enes@desktop:~$ hetzner-k3s create --config testcluster.yaml
Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Network already exists, skipping.
Updating firewall...done.
SSH key already exists, skipping.
Placement group testcluster-prod-masters already exists, skipping.
Placement group testcluster-prod-small-static-1 already exists, skipping.
Server testcluster-prod-cx21-pool-small-static-worker2 already exists, skipping.
Server testcluster-prod-cx21-pool-small-static-worker1 already exists, skipping.
Server testcluster-prod-cpx21-master1 already exists, skipping.
Server testcluster-prod-cx21-pool-small-static-worker3 already exists, skipping.
Waiting for server testcluster-prod-cx21-pool-small-static-worker2...
Waiting for server testcluster-prod-cx21-pool-small-static-worker1...
Waiting for server testcluster-prod-cpx21-master1...
Waiting for server testcluster-prod-cx21-pool-small-static-worker3...
^C
enes@desktop:~$ hetzner-k3s create --config testcluster.yaml
Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Network already exists, skipping.
Updating firewall...done.
SSH key already exists, skipping.
Placement group testcluster-prod-masters already exists, skipping.
Placement group testcluster-prod-small-static-1 already exists, skipping.
Server testcluster-prod-cx21-pool-small-static-worker1 already exists, skipping.
Server testcluster-prod-cpx21-master1 already exists, skipping.
Server testcluster-prod-cx21-pool-small-static-worker2 already exists, skipping.
Server testcluster-prod-cx21-pool-small-static-worker3 already exists, skipping.
Waiting for server testcluster-prod-cx21-pool-small-static-worker1...
Waiting for server testcluster-prod-cpx21-master1...
Waiting for server testcluster-prod-cx21-pool-small-static-worker2...
Waiting for server testcluster-prod-cx21-pool-small-static-worker3...
^C
enes@desktop:~$ ^C
enes@desktop:~$ hetzner-k3s create --config testcluster.yaml
Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Network already exists, skipping.
Updating firewall...done.
SSH key already exists, skipping.
Placement group testcluster-prod-masters already exists, skipping.
Placement group testcluster-prod-small-static-1 already exists, skipping.
Server testcluster-prod-cx21-pool-small-static-worker2 already exists, skipping.
Server testcluster-prod-cpx21-master1 already exists, skipping.
Server testcluster-prod-cx21-pool-small-static-worker3 already exists, skipping.
Server testcluster-prod-cx21-pool-small-static-worker1 already exists, skipping.
Waiting for server testcluster-prod-cx21-pool-small-static-worker2...
Waiting for server testcluster-prod-cpx21-master1...
Waiting for server testcluster-prod-cx21-pool-small-static-worker3...
Waiting for server testcluster-prod-cx21-pool-small-static-worker1...
```

My config file:

```yaml
---
hetzner_token: <token>
cluster_name: testcluster-prod
kubeconfig_path: "./kubeconfig"
k3s_version: v1.25.5+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
use_ssh_agent: true
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
private_network_subnet: 10.0.0.0/16
schedule_workloads_on_masters: false
# image: rocky-9 # optional: default is ubuntu-22.04
# autoscaling_image: 103908130 # optional, defaults to the `image` settings
# snapshot_os: microos # otional: specified the os type when using a custom snapshot
masters_pool:
  instance_type: cpx21
  instance_count: 1
  location: nbg1
  labels:
    - key: type
      value: master
worker_node_pools:
- name: small-static
  instance_type: cx21
  instance_count: 3
  location: nbg1
  labels:
    - key: type
      value: small
service:
    annotations:
      load-balancer.hetzner.cloud/hostname: cluster.testcluster.nl
      load-balancer.hetzner.cloud/http-redirect-https: 'true'
      load-balancer.hetzner.cloud/location: nbg1
      load-balancer.hetzner.cloud/name: "testcluster prod loadbalancer"
      load-balancer.hetzner.cloud/uses-proxyprotocol: 'true'
      load-balancer.hetzner.cloud/use-private-ip: "true"
post_create_commands:
- apt update
- apt upgrade -y
- apt autoremove -y
# enable_encryption: true
# existing_network: <specify if you want to use an existing network, otherwise one will be created for this cluster>
# kube_api_server_args:
# - arg1
# - ...
# kube_scheduler_args:
# - arg1
# - ...
# kube_controller_manager_args:
# - arg1
# - ...
# kube_cloud_controller_manager_args:
# - arg1
# - ...
# kubelet_args:
# - arg1
# - ...
# kube_proxy_args:
# - arg1
# - ...
```
