### ISSUE TITLE
FEATURE REQUEST: Multiple control-planes in different locations

### ISSUE THREAD

**Issue by Styopchik** [vitobotta/hetzner-k3s#219]
There is a possibility to define different locations fo worker nodes with 
```
worker_node_pools:
- name: small-static
  instance_type: cpx21
  instance_count: 4
  location: hel1
```
But there is no such possibility to do the same for masters_pool (control-planes).
