### ISSUE TITLE
Workers not created when autoscaling enabled (v1.1.2)

### ISSUE THREAD

**Issue by leemeichin** [vitobotta/hetzner-k3s#223]
Given the following configuration:

```yaml
---
cluster_name: test-cluster
kubeconfig_path: "~/.kube/config"
k3s_version: v1.27.2+k3s1
public_ssh_key_path: "~/.ssh/id_ed25519.pub"
private_ssh_key_path: "~/.ssh/id_ed25519"
use_ssh_agent: false
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
private_network_subnet: 10.0.0.0/16
schedule_workloads_on_masters: false
masters_pool:
  instance_type: cax11
  instance_count: 1
  location: fsn1
worker_node_pools:
  - name: worker-pool-autoscaler
    instance_type: cax11
    instance_count: 1
    location: fsn1
    autoscaling:
      enabled: true
      min_instances: 1
      max_instances: 3
additional_packages:
  - unattended-upgrades
  - update-notifier-common
post_create_commands:
  - sudo systemctl enable unattended-upgrades
  - sudo systemctl start unattended-upgrades
 ```

When I apply this using the latest version of `hetzner-k3s` (v 1.1.2), the masters pool will be created as expected, but the worker pool with autoscaling enabled will not and the output from creating the cluster will contain anything related to the worker pool, as if it was completely ignored. No placement group exists in the Hetzner Cloud UI and the autoscaler logs output this every few seconds:

```text
W0603 14:05:23.734002       1 clusterstate.go:443] Failed to find readiness information for test-cluster-worker-pool
```

However, when I changed `enabled` to `false` under the `autoscaling` config, the worker pool will be created correctly and everything works as expected (but with no autoscaling, of course).

I'm using ARM-based nodes in the FSN1 region for this.
