### ISSUE TITLE
Initialization never ends

### ISSUE THREAD

**Issue by maxmielchen** [vitobotta/hetzner-k3s#232]
When I created my cluster, the script hung up and then after some time I got an error message.

Config:
```yml
hetzner_token: <api_token>
cluster_name: content
kubeconfig_path: "./kubeconfig" 
k3s_version: v1.27.2+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
use_ssh_agent: true
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
schedule_workloads_on_masters: false
masters_pool:
  instance_type: cx21
  instance_count: 3
  location: fsn1
worker_node_pools:
  - name: ger_arm
    instance_type: cax11
    instance_count: 2
    location: fsn1
    autoscaling:
      enabled: true
      min_instances: 1
      max_instances: 5
```

Command:
```bash
hetzner-k3s create --config cluster_config.yaml 
```

Console:
```
Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Creating network...done.
Creating firewall...done.
Creating SSH key...done.
Creating placement group content-masters...done.
Creating server content-cx21-master3...
Creating server content-cx21-master2...
Creating server content-cx21-master1...
...server content-cx21-master2 created.
...server content-cx21-master1 created.
...server content-cx21-master3 created.
Waiting for server content-cx21-master2...
Waiting for server content-cx21-master1...
Waiting for server content-cx21-master3...
Unhandled exception in spawn: timeout after 00:00:05 (Tasker::Timeout)
  from /workspace/lib/tasker/src/tasker/timeout.cr:37:9 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
Unhandled exception in spawn: timeout after 00:00:05 (Tasker::Timeout)
  from /workspace/lib/tasker/src/tasker/timeout.cr:37:9 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
Unhandled exception in spawn: timeout after 00:00:05 (Tasker::Timeout)
  from /workspace/lib/tasker/src/tasker/timeout.cr:37:9 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```

Thanks in advance
