### ISSUE TITLE
Default Nginx Ingress / load balancer instructions invalid

### ISSUE THREAD

**Issue by Shakahs** [vitobotta/hetzner-k3s#241]
The [cluster setup instructions](https://github.com/vitobotta/hetzner-k3s/blob/main/wiki/Setting%20up%20a%20cluster.md) indicate that proxy protocol should be enabled on the load balancer via annotation. 

This results in a broken configuration, as Nginx Ingress will reject all requests from the load balancer with HTTP 400 unless Nginx Ingress is _also_ configured to enable proxy protocol. 

This can be resolved by adding the following to `ingress-nginx-annotations.yaml`:
```
  config:
    use-proxy-protocol: "true"
```

This is the full working `ingress-nginx-annotations.yaml`:
```
controller:
  kind: DaemonSet
  config:
    use-proxy-protocol: "true"
  service:
    annotations:
      load-balancer.hetzner.cloud/location: ash
      load-balancer.hetzner.cloud/name: k3s_ashburn_lb
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/uses-proxyprotocol: 'true'
      load-balancer.hetzner.cloud/http-redirect-https: 'false'
```
