### ISSUE TITLE
worker nodes don't join the cluster anymore

### ISSUE THREAD

**Issue by Funzinator** [vitobotta/hetzner-k3s#289]
Since today (or yesterday), if I execute the following `cluster_config.yaml`
```yaml
---
cluster_name: test
k3s_version: v1.28.3+k3s2

schedule_workloads_on_masters: false

private_network_subnet: 10.21.0.0/16
cluster_cidr: 10.244.0.0/16
service_cidr: 10.43.0.0/16
disable_flannel: false
enable_encryption: true

image: rocky-9
autoscaling_image: rocky-9

cloud_controller_manager_manifest_url: "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.18.0/ccm-networks.yaml"
csi_driver_manifest_url: "https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.5.1/deploy/kubernetes/hcloud-csi.yml"
system_upgrade_controller_manifest_url: "https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml"

masters_pool:
  instance_type: cax11
  instance_count: 1
  location: fsn1

worker_node_pools:
- name: cax21-autoscale-1
  instance_type: cax21
  instance_count: 1
  location: fsn1
```
I have to run the hetzner-k3s command twice in order for the worker node(s) to join the cluster. If I use autoscaling, it doesn't work at all anymore - I guess since there is no retry.

I can see that the k3s installer is executed twice (once master, once worker) - but the join succeeds only on the second run.

Anyone else experiencing this?
