### ISSUE TITLE
empty kubeconfig

### ISSUE THREAD

**Issue by dyipon** [vitobotta/hetzner-k3s#297]
Hi,

im trying to setup a new private networked k3s cluster, but the created kubeconfig is empty. Is there any way to debug this issue?

config below:
```
---
cluster_name: hetzner-k3s
kubeconfig_path: "kubeconfig-hetzner.yaml"
k3s_version: v1.28.3+k3s1
public_ssh_key_path: "hetzner.pub"
private_ssh_key_path: "hetzner.key"

private_network_subnet: 10.0.9.0/24
existing_network: private

enable_public_net_ipv4: false
enable_public_net_ipv6: false

use_ssh_agent: false
image: ubuntu-20.04

ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: nbg1
schedule_workloads_on_masters: false

masters_pool:
  instance_type: cx11
  instance_count: 1
  location: nbg1
worker_node_pools:
- name: intel1
  instance_type: cx21
  instance_count: 1
  location: nbg1
  post_create_commands:
    - timedatectl set-timezone Europe/Berlin
    - >
      printf "network## {config## disabled}" |
      sed 's/##/:/g' > /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    - >
      printf "network##\n  version## 2\n  renderer## networkd\n  ethernets##\n    ens10##\n      dhcp4## true\n      nameservers##\n        addresses## [185.12.64.1, 185.12.64.2]\n      routes##\n        - to## default\n          via## 10.0.9.2" |
      sed 's/##/:/g' > /etc/netplan/50-cloud-init.yaml
    - netplan generate
    - netplan apply
    - apt update
    - apt upgrade -y
    - apt autoremove -y
post_create_commands:
  - timedatectl set-timezone Europe/Berlin
  - >
    printf "network## {config## disabled}" |
    sed 's/##/:/g' > /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
  - >
    printf "network##\n  version## 2\n  renderer## networkd\n  ethernets##\n    enp7s0##\n      dhcp4## true\n      nameservers##\n        addresses## [185.12.64.1, 185.12.64.2]\n      routes##\n        - to## default\n          via## 10.0.9.2" |
    sed 's/##/:/g' > /etc/netplan/50-cloud-init.yaml
  - netplan generate
  - netplan apply
  - apt update
  - apt upgrade -y
  - apt autoremove -y
```

log output:

```
+ ./hetzner-k3s create --config create-cluster.yaml
Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Updating firewall...done.
SSH key already exists, skipping.
Placement group hetzner-k3s-masters already exists, skipping.
Placement group hetzner-k3s-intel1-1 already exists, skipping.
Server hetzner-k3s-cx21-pool-intel1-worker1 already exists, skipping.
Server hetzner-k3s-cx11-master1 already exists, skipping.
Server hetzner-k3s-cx11-master1 already exists, skipping.
Waiting for successful ssh connectivity with server hetzner-k3s-cx11-master1...
Server hetzner-k3s-cx21-pool-intel1-worker1 already exists, skipping.
Waiting for successful ssh connectivity with server hetzner-k3s-cx21-pool-intel1-worker1...
...server hetzner-k3s-cx11-master1 is now up.
...server hetzner-k3s-cx21-pool-intel1-worker1 is now up.

=== Setting up Kubernetes ===
Deploying k3s to first master hetzner-k3s-cx11-master1...
Waiting for the control plane to be ready...
Saving the kubeconfig file to /root/k3s/kubeconfig-hetzner.yaml...
...k3s has been deployed to first master hetzner-k3s-cx11-master1 and the control plane is up.
Deploying k3s to worker hetzner-k3s-cx21-pool-intel1-worker1...
...k3s has been deployed to worker hetzner-k3s-cx21-pool-intel1-worker1.

=== Deploying Hetzner drivers ===

Creating secret for Hetzner Cloud token...
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Failed to create Hetzner Cloud secret:
#<Util::Shell::Result:0x7fafeeff25e0>
+ kubectl --kubeconfig kubeconfig-hetzner.yaml get nodes
E1128 21:13:41.442044    2507 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080:
 connect: connection refused
```

kubeconfig file:
```

root@tailscale:~/k3s# ls -la kubeconf*
-rw------- 1 root root 0 Nov 28 21:13 kubeconfig-hetzner.yaml
```

version: 
```
/hetzner-k3s --version
1.1.5
```
