### ISSUE TITLE
Can't create cluster from management server

### ISSUE THREAD

**Issue by Chris6077** [vitobotta/hetzner-k3s#298]
Hello!

I am trying to create a K3s cluster using a management server in the same virtual network.
For this, I have created a Ubuntu 22.04 server (10.1.0.2) and a vnet (vnet-temp). When I try to create the cluster with "hetzner-k3s create --config x.yaml" the script gives me the following errors:

> Validating the configuration...
> Some information in the configuration file requires your attention:
>   - Your current IP **publicIPv4** must belong to at least one of the networks allowed for SSH
>   - Your current IP **publicIPv4** must belong to at least one of the permitted API networks

This is my config:
```
hetzner_token: <removed>
cluster_name: test
kubeconfig_path: "./kubeconfig"
k3s_version: v1.26.10+k3s1
public_ssh_key_path: "/home/test/.ssh/id_ecdsa.pub"
private_ssh_key_path: "/home/test/.ssh/id_ecdsa"
use_ssh_agent: true
ssh_port: 22
ssh_allowed_networks:
  - 10.1.0.0/16
api_allowed_networks:
  - 10.1.0.0/16
private_network_subnet: 10.1.0.0/16
disable_flannel: false
schedule_workloads_on_masters: false
enable_public_net_ipv4: false
enable_public_net_ipv6: false
cloud_controller_manager_manifest_url: "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.18.0/ccm-networks.yaml"
csi_driver_manifest_url: "https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.5.1/deploy/kubernetes/hcloud-csi.yml"
system_upgrade_controller_manifest_url: "https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml"
masters_pool:
  instance_type: cx21
  instance_count: 3
  location: fsn1
worker_node_pools:
- name: small-static
  instance_type: cx21
  instance_count: 2
  location: fsn1
- name: big-autoscaled
  instance_type: cx41
  instance_count: 2
  location: fsn1
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 3
post_create_commands:
- apt update
- apt upgrade -y
- apt autoremove -y
enable_encryption: true
existing_network: vnet-temp
```

Is there anything wrong with my configuration?
When using 0.0.0.0/0 for ssh_allowed_networks and api_allowed_networks, the servers will be created, but the script will get stuck at this part:
```
Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Creating firewall...done.
Creating SSH key...done.
Creating placement group test-masters...done.
Placement group test-small-static-1 already exists, skipping.
Creating server test-cx21-master1...
Creating server test-cx21-pool-small-static-worker2...
Creating server test-cx21-pool-small-static-worker1...
Creating server test-cx21-master2...
Creating server test-cx21-master3...
...server test-cx21-pool-small-static-worker1 created.
...server test-cx21-master2 created.
...server test-cx21-master1 created.
...server test-cx21-pool-small-static-worker2 created.
...server test-cx21-master3 created.
Server test-cx21-master1 already exists, skipping.
Waiting for successful ssh connectivity with server test-cx21-master1...
Server test-cx21-master2 already exists, skipping.
Waiting for successful ssh connectivity with server test-cx21-master2...
Server test-cx21-master3 already exists, skipping.
Waiting for successful ssh connectivity with server test-cx21-master3...
Server test-cx21-pool-small-static-worker1 already exists, skipping.
Waiting for successful ssh connectivity with server test-cx21-pool-small-static-worker1...
Waiting for successful ssh connectivity with server test-cx21-pool-small-static-worker2...
```
