### ISSUE TITLE
System Upgrade Controller does not target tainted nodes

### ISSUE THREAD

**Issue by lloesche** [vitobotta/hetzner-k3s#300]
When adding node taints `system-upgrade-controller` fails to upgrade the tainted nodes because there's a toleration missing for those taints.

For example:
```
- name: db
  instance_type: ccx43
  instance_count: 3
  location: ash
  labels:
  - key: node-role
    value: database
  taints:
  - key: node-role/dedicated
    value: database:NoSchedule
```

This node pool failed to upgrade. After manually adding the toleration to the created jobs the upgrade finished successfully.

Since Rancher's `system-upgrade-controller` has support for node taints in its config, I'm assuming that this is something `hetzner-k3s` would have to set based on the taints it finds in its own pools config.
