### ISSUE TITLE
Node pool with `instance_size: 0` and `autoscaling.min_instances: 0` still gets one node right away

### ISSUE THREAD

**Issue by NiklasRosenstein** [vitobotta/hetzner-k3s#316]
Hi! I've just bootstrapped a new cluster with this configuration and find that the `amd64-large` worker node pool immediately has one node in it:

![image](https://github.com/vitobotta/hetzner-k3s/assets/1318438/1a462e34-7b86-48cd-8b01-0f97ac718e6f)

![image](https://github.com/vitobotta/hetzner-k3s/assets/1318438/9fce4c2f-f505-488e-ae6a-e0b7779f610d)

<details><summary><code>`cluster.yaml`</code></summary>

```
---
cluster_name: github-arc
kubeconfig_path: "./kubeconfig.yaml"
k3s_version: v1.28.1-rc2+k3s1
public_ssh_key_path: "id_ed25519.pub"
private_ssh_key_path: "id_ed25519"
use_ssh_agent: false # set to true if your key has a passphrase or if SSH connections don't work or seem to hang without agent. See https://github.com/vitobotta/hetzner-k3s#limitations
# ssh_port: 22
ssh_allowed_networks:
  - 0.0.0.0/0 # ensure your current IP is included in the range
api_allowed_networks:
  - 0.0.0.0/0 # ensure your current IP is included in the range
private_network_subnet: 10.0.0.0/16 # ensure this doesn't overlap with other networks in the same project
disable_flannel: false # set to true if you want to install a different CNI
schedule_workloads_on_masters: false

image: ubuntu-22.04
cloud_controller_manager_manifest_url: "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.18.0/ccm-networks.yaml"
csi_driver_manifest_url: "https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.5.1/deploy/kubernetes/hcloud-csi.yml"
system_upgrade_controller_manifest_url: "https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml"

masters_pool:
  instance_type: cax11
  instance_count: 1
  location: hel1

worker_node_pools:
- name: default
  instance_type: cpx21
  instance_count: 1
  location: hel1

- name: amd64-small
  instance_type: cpx21
  instance_count: 1
  location: hel1
  labels:
    - key: arc-worker-pool
      value: small
  taints:
    - key: workload
      value: arc-job:NoSchedule
  autoscaling:
    enabled: true
    min_instances: 1
    max_instances: 3

- name: arm64-small
  instance_type: cax11
  instance_count: 1
  location: hel1
  labels:
    - key: arc-worker-pool
      value: small
  taints:
    - key: workload
      value: arc-job:NoSchedule
  autoscaling:
    enabled: true
    min_instances: 1
    max_instances: 3

- name: amd64-large
  instance_type: cpx41
  instance_count: 0
  location: hel1
  labels:
    - key: arc-worker-pool
      value: large
  taints:
    - key: workload
      value: arc-job:NoSchedule
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 4

- name: arm64-large
  instance_type: cax41
  instance_count: 0
  location: hel1
  labels:
    - key: arc-worker-pool
      value: large
  taints:
    - key: workload
      value: arc-job:NoSchedule
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 4
```

</details>

I also find that the master node does not have a NoSchedule taint for being a control plane despite `schedule_workloads_on_masters: false`.
