### ISSUE TITLE
Question : How to add a new worker node pool

### ISSUE THREAD

**Issue by omar6995** [vitobotta/hetzner-k3s#318]
Hi Everyone, 

I used this tools a few months ago to deploy my application. I used this config : 

```
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
use_ssh_agent: false
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
schedule_workloads_on_masters: false
masters_pool:
  instance_type: cx21
  instance_count: 1
  location: nbg1
worker_node_pools:
  - name: small
    instance_type: ccx12
    instance_count: 1
    location: nbg1
```

today, the instance type ccx12 and cx21 are no longer available in hetzner.

I would like to deploy a separate worker node pool which will host my database. How should I do this ? Should I simply add the new node pool and rerun the create command? Will this be affecting my old nodes ?

Thanks in advance for your help
