### ISSUE TITLE
hetzner-k3s delete does not remove worker pool placement groups

### ISSUE THREAD

**Issue by shadshar** [vitobotta/hetzner-k3s#321]
Hi! When running `hetzner-k3s delete`, it uses the wrong names when it refers to the names of the worker pool placement groups that were created. On creation, the placement groups get named `name-X`, where `X` is a number. That number is not being used during the deletion process, so the placement groups remain and need to be deleted by hand using the cloud console.

So for example, with a config snippet as follows:
```yaml
worker_node_pools:
- name: small-static-1
  instance_type: cax11
  instance_count: 2
  location: nbg1
  labels:
    - key: purpose
      value: k3s-worker
- name: small-static-2
  instance_type: cax11
  instance_count: 2
  location: nbg1
  labels:
    - key: purpose
      value: k3s-worker
```
During creation, the output confirms the creation like this:
````
Creating placement group k3s-playground-masters...done.
Creating placement group k3s-playground-small-static-1-1...done.
Creating placement group k3s-playground-small-static-2-1...done.
````
And deletion fails like this:
```
Deleting placement group k3s-playground-masters...done.
Placement group k3s-playground-small-static-1 does not exist, skipping.
Placement group k3s-playground-small-static-2 does not exist, skipping.
```
