### ISSUE TITLE
Rescale Master Nodes from CPX11 to CPX21

### ISSUE THREAD

**Issue by psavva** [vitobotta/hetzner-k3s#326]
Dear @vitobotta 

I'm looking at rescaling my master nodes for example from CPX11 to CPX21.

If i simply change 
```
  masters_pool:
  instance_type: cpx11
  location: nbg1
  instance_count: 3
```
to 

```
masters_pool:
  instance_type: cpx21
  location: nbg1
  instance_count: 3
```

A new cluster is created.

How do you go about scaling the master nodes?
