### ISSUE TITLE
ingress-nginx not giving external ip / not creating a lb

### ISSUE THREAD

**Issue by 0xMALVEE** [vitobotta/hetzner-k3s#334]
![image](https://github.com/vitobotta/hetzner-k3s/assets/35369563/8768ddbc-741d-402f-9c2e-2d9ec3aba525)
stuck in pending state for ever.

commands ran to install ngnix-ingress is bellow
```
helm upgrade --install ingress-nginx ingress-nginx \
  --repo https://kubernetes.github.io/ingress-nginx \
  --namespace ingress-nginx --create-namespace
```

**Comment by 0xMALVEE** [comment]
fixed it. by adding anotattions under metadata.

**Comment by khustochka** [comment]
@0xMALVEE Do you mind telling what exactly you did to fix this. In which file did you added "annotations under metadata"? Would appreciate greatly!

I am having the same issue. Although I went to hetzner admin and manually added the target to the load balancer, and services to the target. Weirdly, after this https connection somehow started to work, but http did not (returning status 400 Bad request). And no External IP appeared anyway.

**Comment by 0xMALVEE** [comment]
@khustochka sorry for the late reply. here is what I did basically added the hetzner specific metadata there in the ngnix ingress yaml file and manually applied.
```
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.10.0
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations: 
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/use-private-ip: "true"

```
![image](https://github.com/vitobotta/hetzner-k3s/assets/35369563/c651f7d1-6598-4f18-8b95-69f26cdaa707)
