### ISSUE TITLE
Feature Request: add possiblity to install custom packages on Worker Nodes

### ISSUE THREAD

**Issue by janosmiko** [vitobotta/hetzner-k3s#37]
When I create a worker node using hetzner-k3s, there are some packages which I have to manually install. The most useful example in my case is `nfs-common` which is required for multiple storage classes (eg. longhorn PVC in RWX mode).

Could you make it possible to add an `additional_packages` list to the `config.yaml`. These packages could be a part of user-data in hetzner install.

eg.:
```yaml
---
hetzner_token: 1234
cluster_name: name
kubeconfig_path: "/cluster/kubeconfig"
k3s_version: v1.21.6+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
ssh_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: nbg1
schedule_workloads_on_masters: false
additional_packages:
  - "nfs-common"
masters:
  instance_type: cpx41
  instance_count: 1
worker_node_pools:
  - name: worker
    instance_type: cpx51
    instance_count: 3
```
