### ISSUE TITLE
Some workarounds for priv IP clusters

### ISSUE THREAD

**Issue by axgkl** [vitobotta/hetzner-k3s#379]
Hi,

since I fiddled for quite some time, maybe I can save some time for others with this.

The `enable_public_net_ipv4: false` switch did involve a few problems here, so I try list my workarounds. 
Others report that cluster creation works (e.g. #372) - but not for me and seemingly others - I keep getting the same errors, even with the exact same config than #372 :-/ (except the name of the priv network).

## Goals
- Working priv IP only cluster, configured from a bastion host with a pub ip, running that script.
- All cluster nodes can reach the internet, incl. DNS
- Autoscaler fully works, allows SSH access from bastion host

## Problems
a) k3s did not install, empty kubeconfig on bastion node, failing with STDIN error at first kubeconfig apply time - even over repeated retries
b) missing DNS on the cluster nodes
c) autoscaler did create the nodes but could not include them into the cluster
d) ssh rejects (max retries exceeded) when trying to ssh into the autoscaled nodes
e) upgrade controller was broken

## Solutions

e) was caused by [this](https://github.com/rancher/system-upgrade-controller/issues/302) and was solved by `kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml` after the cluster was up.  I expect rancher to fix this soon, i.e. might work when you read this out of the box (again).

All other points addressed with the following config:

```yaml
additional_packages:
 - ifupdown
 
post_create_commands:
  - printf "started" > status
  - timedatectl set-timezone Europe/Berlin
  - ip route add default via 10.0.0.1
  - ip route add 169.254.0.0/16 via 172.31.1.1
  - mkdir -p /etc/network/interfaces.d
  - echo "auto enp7s0"                                              > /etc/network/interfaces.d/enp7s0
  - echo "iface enp7s0 inet dhcp"                                  >> /etc/network/interfaces.d/enp7s0
  - echo "    post-up ip route add default via 10.0.0.1"           >> /etc/network/interfaces.d/enp7s0
  - echo "    post-up ip route add 169.254.169.254 via 172.31.1.1" >> /etc/network/interfaces.d/enp7s0
  - rm -f                            /etc/resolv.conf
  - echo 'nameserver 185.12.64.1'  > /etc/resolv.conf
  - echo 'nameserver 185.12.64.2' >> /etc/resolv.conf
  - echo 'edns edns0 trust-ad'    >> /etc/resolv.conf
  - echo 'search .'               >> /etc/resolv.conf
  - sed -i '1i export INSTALL_K3S_SKIP_DOWNLOAD=true' /root/.bashrc
  - wget 'https://github.com/k3s-io/k3s/releases/download/v1.29.6+k3s2/k3s'
  - chmod +x k3s
  - mv k3s /usr/local/bin/k3s
  - echo 'ssh-ed25519 AAAAC3Nz....  admin@bast' >> /root/.ssh/authorized_keys
  - echo 'ssh-rsa AAAAB3Nzx1yc...  me@mylaptop' >> /root/.ssh/authorized_keys
  - echo "root:somesupersecret" | chpasswd
  - printf "done" > status
```

The bastion host has 10.0.0.2 (first host created on the private network) and has a public ipv4.  On it, `echo 1 > /proc/sys/net/ipv4/ip_forward` and `iptables -t nat -A POSTROUTING -s '10.0.0.0/16' -o eth0 -j MASQUERADE` are run and persisted.

## Discussion

- The ifupdown based network setup configures the nodes to go to the internet via the bastion host, which NATs their traffic.

  - Note the `10.0.0.1` - while the bastion host is on `10.0.0.2`  - Has to be like that!
  - My images are ubuntu and debian 11 / amd.  Both have enp7s0 iface, when in the private network. Adapt if different for you.
  - The 172.31.1.1 might also be different for you - not sure. Found it via `tracepath -n 169.254.169.254` on the bastion host, first hop.

- The DNS is brutally set to point to the Hetzner's DNS servers, away from systemd resolvd, which did not resolve for queries from within containers.

- I don't reboot for install speed - but the routes and dns mod are persistent over reboots

- There is a specific route for the hetzner API endpoint at `169.254.169.254`, which the autoscaler uses to find the instance name. Without that route, the autoscaler reports something like "is this a hetzner node?" (from the [hcloud go lib](https://github.com/hetznercloud/hcloud-go/blob/main/hcloud/metadata/client.go)), in the logs and does not include new nodes into the cluster.

- The k3s is **manually** downloaded via wget, and put into place (in the matching version). Then in bashrc, the script gets a `INSTALL_K3S_SKIP_DOWNLOAD` set to true. Reason:  I keep getting failing downloads when triggered from the script - I'm sure it's not the fault of the script, works perfect with pub IPs but due to this network config. With this it works reliably, the second time you run it, after the first STDIN failure. 

Edit: See my following comment for the reason of this.

- ssh keys and root password are set from the post installer. Because for nodes created from the autoscaler, those where not set, causing hetzner to want a root password reset and so I got immediate ssh login failures (the script sets max failed attempts to a low 2).  This keys and pw setting from the post installer resolves all issues with ssh.

---

Thanks in any case for the nice installer, way easier than terraform!
