### ISSUE TITLE
First feedback: Looking for help testing v2.0.0

### ISSUE THREAD

**Issue by axgkl** [vitobotta/hetzner-k3s#387]
First of all: Thanks again.

The binary works on my fedora ootb, did not need to compile.

Nice to have:

- would be a debug flag / verbose mode, where one can see more what's going on, but only if easy.
- 

Current minor issues:

**Docs**
- https://github.com/vitobotta/hetzner-k3s/blob/more-refactoring/docs/Installation.md
  -  I think now the user also requires **helm** not only kubectl, no? Btw: The binenv tool I find the fastest way to get to such binaries, thinking about adding this here there as well
  - wget https://github.com/vitobotta/hetzner-k3s/releases/download/v1.1.5/hetzner-k3s-macos-amd64 -> Dont' forget to change to the v2

- Creating_a_cluster.md
  - Not 100% clear how the commented out cluster and service cidrs should be - I guess not under CNI but under network. Ah forget it, it's clear seeing the indented hashes further below. Mabye an empty line under flannel makes it clear to everybody.

**Blocker**
I'm installing from my bastion host again, at 10.4.0.2, into private network 10.4.0.0/16.

<details><summary>output</summary>

```
Last login: Wed Jul 24 15:19:17 2024 from 84.150.82.88
root@bastion:~# ./hetzner-k3s create --config config.yaml
[Configuration] Validating configuration...
[Configuration] ...configuration seems valid.
[SSH key] Creating SSH key...
[SSH key] ...SSH key created
[Placement groups] Deleting unused placement group ax-masters...
[Placement groups] ...placement group ax-masters deleted
[Placement groups] Creating placement group ax-masters...
[Placement groups] ...placement group ax-masters created
[Instance ax-master2] Creating instance ax-master2 (attempt 1)...
[Instance ax-master3] Creating instance ax-master3 (attempt 1)...
[Instance ax-master1] Creating instance ax-master1 (attempt 1)...
[Instance ax-master2] Instance status: off
[Instance ax-master2] Powering on instance (attempt 1)
[Instance ax-master3] Instance status: off
[Instance ax-master3] Powering on instance (attempt 1)
[Instance ax-master2] Waiting for instance to be powered on...
[Instance ax-master3] Waiting for instance to be powered on...
[Instance ax-master1] Instance status: off
[Instance ax-master1] Powering on instance (attempt 1)
[Instance ax-master1] Waiting for instance to be powered on...
[Instance ax-master2] Instance status: running
[Instance ax-master2] Attaching instance to network (attempt 1)
[Instance ax-master3] Instance status: running
[Instance ax-master2] Waiting for instance to be attached to the network...
[Instance ax-master3] Attaching instance to network (attempt 1)
[Instance ax-master1] Instance status: running
[Instance ax-master3] Waiting for instance to be attached to the network...
[Instance ax-master1] Attaching instance to network (attempt 1)
[Instance ax-master1] Waiting for instance to be attached to the network...
[Instance ax-master3] Instance ax-master3 already exists, skipping create
[Instance ax-master2] Instance ax-master2 already exists, skipping create
[Instance ax-master1] Instance ax-master1 already exists, skipping create
[Instance ax-master3] Instance status: running
[Instance ax-master3] Waiting for successful ssh connectivity with instance ax-master3...
[Instance ax-master2] Instance status: running
[Instance ax-master2] Waiting for successful ssh connectivity with instance ax-master2...
[Instance ax-master1] Instance status: running
[Instance ax-master1] Waiting for successful ssh connectivity with instance ax-master1...
[Instance ax-master3] ...instance ax-master3 is now up.
[Instance ax-master2] Instance status: running
[Instance ax-master2] Waiting for successful ssh connectivity with instance ax-master2...
[Instance ax-master2] ...instance ax-master2 is now up.
[Instance ax-master1] ...instance ax-master1 is now up.
[Firewall] Updating firewall...
[Instance ax-master3] Instance status: running
[Instance ax-master3] Waiting for successful ssh connectivity with instance ax-master3...
[Firewall] ...firewall updated
[Instance ax-master2] ...instance ax-master2 is now up.
[Instance ax-master2] ...instance ax-master2 created
[Instance ax-master1] Instance status: running
[Instance ax-master1] Waiting for successful ssh connectivity with instance ax-master1...
[API Load balancer] Load balancer for API server already exists, skipping create
[Instance ax-master3] ...instance ax-master3 is now up.
[Instance ax-master3] ...instance ax-master3 created
[Instance ax-master1] ...instance ax-master1 is now up.
[Instance ax-master1] ...instance ax-master1 created
[Instance ax-master3] Awaiting cloud/instance/boot-finished...
[Instance ax-master3] Awaiting cloud/instance/boot-finished...
[Instance ax-master3] Awaiting cloud/instance/boot-finished...
[Instance ax-master3] Awaiting cloud/instance/boot-finished...
[Instance ax-master3] Awaiting cloud/instance/boot-finished...
[Instance ax-master3] Awaiting cloud/instance/boot-finished...
[Instance ax-master3] Awaiting cloud/instance/boot-finished...
[Instance ax-master3] Awaiting cloud/instance/boot-finished...
[Instance ax-master3] Awaiting cloud/instance/boot-finished...
[Instance ax-master3] Awaiting cloud/instance/boot-finished...
[Instance ax-master3] [INFO]  Using v1.26.4+k3s1 as release
[Instance ax-master3] [INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.26.4+k3s1/sha256sum-amd64.txt
[Instance ax-master3] [INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.26.4+k3s1/k3s
[Instance ax-master3] [INFO]  Verifying binary download
[Instance ax-master3] [INFO]  Installing k3s to /usr/local/bin/k3s
[Instance ax-master3] [INFO]  Skipping installation of SELinux RPM
[Instance ax-master3] [INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[Instance ax-master3] [INFO]  Creating /usr/local/bin/crictl symlink to k3s
[Instance ax-master3] [INFO]  Creating /usr/local/bin/ctr symlink to k3s
[Instance ax-master3] [INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[Instance ax-master3] [INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[Instance ax-master3] [INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[Instance ax-master3] [INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[Instance ax-master3] [INFO]  systemd: Enabling k3s unit
[Instance ax-master3] [INFO]  systemd: Starting k3s
[Instance ax-master3] Waiting for the control plane to be ready...
[Control plane] Saving the kubeconfig file to /root/kubeconfig...
^C
```
would time out here.

On master3 the service file looks good:

```
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service 2>/dev/null'
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
	'--disable-cloud-controller' \
	'--disable' \
	'servicelb' \
	'--disable' \
	'traefik' \
	'--disable' \
	'metrics-server' \
	'--write-kubeconfig-mode=644' \
	'--node-name=ax-master3' \
	'--cluster-cidr=10.50.0.0/16' \
	'--service-cidr=10.60.0.0/16' \
	'--cluster-dns=10.60.0.10' \
	'--kube-controller-manager-arg=bind-address=0.0.0.0' \
	'--kube-proxy-arg=metrics-bind-address=0.0.0.0' \
	'--kube-scheduler-arg=bind-address=0.0.0.0' \
	'--kubelet-arg' \
	'cloud-provider=external' \
	'--kubelet-arg' \
	'resolv-conf=/etc/k8s-resolv.conf' \
	'--etcd-expose-metrics=true' \
	'--flannel-backend=none' \
	'--disable-network-policy' \
	'--disable-kube-proxy' \
	'--embedded-registry' \
	'--advertise-address=10.4.0.4' \
	'--node-ip=10.4.0.4' \
	'--node-external-ip=100.66.0.155' \
	'--cluster-init' \
	'--tls-san=' \
	'--tls-san=10.4.0.3' \
	'--tls-san=10.4.0.4' \
	'--tls-san=10.4.0.5' \
	'--tls-san=127.0.0.1' \
	'--tls-san=65.109.223.252' \
```
from config

```yaml
---
cluster_name: "ax"
kubeconfig_path: "./kubeconfig"
k3s_version: "v1.26.4+k3s1"
networking:
  ssh:
    port: 22
    use_agent: false # set to true if your key has a passphrase
    public_key_path: "~/.ssh/id_ed25519.pub"
    private_key_path: "~/.ssh/id_ed25519"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api:
      - 0.0.0.0/0
  public_network:
    ipv4: false
    ipv6: true
  private_network:
    enabled : true
    subnet: 10.4.0.0/16
    existing_network_name: "ten_4"
  cni:
    enabled: true
    encryption: false
    mode: cilium
  cluster_cidr: 10.50.0.0/16
  service_cidr: 10.60.0.0/16
  cluster_dns: 10.60.0.10
datastore:
  mode: etcd # etcd (default) or external
  external_datastore_endpoint: postgres://....
schedule_workloads_on_masters: true

masters_pool:
  instance_type: "cx11"
  instance_count: 3
  location: "hel1"
  image: "ubuntu-22.04"

worker_node_pools:
- name: small-static
  instance_type: "cx11"
  instance_count: 0
  location: "hel1"
  image: "ubuntu-22.04"
  # labels:
  #   - key: purpose
  #     value: blah
  # taints:
  #   - key: something
  #     value: value1:NoSchedule

- name: medium-autoscaled
  instance_type: "cx11"
  instance_count: 3
  location: "hel1"
  image: "ubuntu-22.04"
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 3

embedded_registry_mirror:
  enabled: true

additional_packages:
 - ifupdown

post_create_commands:
  - printf "started" > status
  - timedatectl set-timezone Europe/Berlin
  - echo 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAgIhV5X2r7MthxFZBUZUZRo3zDbOS7k3GYXQVirne9W8fUE8QM1AUxVXOK/wL3zOSaP2CIqDT2OxfC+tWDnPu0= root@bastion' >> /root/.ssh/authorized_keys
  - echo 'ssh-rsa AAAqqdSp....' >> /root/.ssh/authorized_keys
   - echo "root:$(head -c 50 /dev/urandom | base64)" | chpasswd
  - ip route add default via 10.4.0.1
  - ip route add 169.254.0.0/16 via 172.31.1.1
  - mkdir -p /etc/network/interfaces.d
  - echo "auto ens10"                                               > /etc/network/interfaces.d/ens10
  - echo "iface ens10 inet dhcp"                                   >> /etc/network/interfaces.d/ens10
  - echo "    post-up ip route add default via 10.4.0.1" >> /etc/network/interfaces.d/ens10
  - echo "    post-up ip route add 169.254.169.254 via 172.31.1.1" >> /etc/network/interfaces.d/ens10
  - rm -f                            /etc/resolv.conf
  - echo "nameserver 185.12.64.1"  > /etc/resolv.conf
  - echo "nameserver 185.12.64.2" >> /etc/resolv.conf
  - echo "edns edns0 trust-ad"    >> /etc/resolv.conf
  - echo "search ." >> /etc/resolv.conf
  - printf "done" > status

```
That settings are still needed to get ssh working and internet access, when private ips.

</details>

On master1 and 2 there is nothing downloaded, as it looks not even attempted. 

All masters can ping each other and all see the internet.

Let you know when I find out more why the process does not continue.
