### ISSUE TITLE
helm cilium encryption settings

### ISSUE THREAD

**Issue by axgkl** [vitobotta/hetzner-k3s#399]
```ruby
    --namespace kube-system \
    --set encryption.enabled=#{settings.networking.cni.enabled.to_s} \
    --set encryption.type=wireguard \
    --set encryption.nodeEncryption=#{settings.networking.cni.enabled.to_s} \
    --set routingMode=tunnel \
    --set tunnelProtocol=vxlan \
    --set ipam.mode="kubernetes" \
 ```
 
in `src/kubernetes/software/cilium.cr`
 
can this be right? 
 
config has these:

```yaml
cni:
    enabled: true
    encryption: false
    mode: flannel
```
 
Shouldn't `cni.encryption` be in both?

Also, you think vxlan is the best for hetzner, or should it be configurable maybe?
