### ISSUE TITLE
Api-Platform integration issues

### ISSUE THREAD

**Issue by JvB94** [vitobotta/hetzner-k3s#40]
I have been procrastinating for a long time now before creating this thread and I know it's not a mistake on your part but I don't know where else to ask.

I have created a cluster with your tool and everything works so far. I use API-Platform and am now trying to integrate a load balancer. My expected result is that a load balancer is created and it has my worker nodes as a service.

In the values.yaml I have tried to insert the following in all places, always under annotations.
```load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/name: cluster-name-ingress-nginx
    load-balancer.hetzner.cloud/use-private-ip: "true"
```
among others the following
```
ingress:
  enabled: true
  annotations:
    load-balancer.hetzner.cloud/hostname: "random-hostname.com"
    load-balancer.hetzner.cloud/http-redirect-https: 'false'
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/health-check-port: "30787"
    #load-balancer.hetzner.cloud/name: "backend-lb-prod"
    load-balancer.hetzner.cloud/uses-proxyprotocol: 'true' #load-balancer.hetzner.cloud/name: 'backend-lb-prod
    load-balancer.hetzner.cloud/use-private-ip: 'true'
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
  hosts:
    - host: random-hostname.com
      paths:
        - path: "/"
          pathType: "Prefix
          backend:
            service:
              name: "test"
              port:
                number: 80
  tls: []
```

Since it didn't work, I also tried to write the whole thing directly into the ingress.yaml under the points as explained in the instructions.

After deployment, no load balancer is created.

Is there anyone here who can help me? I would be very grateful, I've been dealing with this for over a week now and can't get any further. I think other API Platform users would also appreciate it.

EDIT:
If i run 
```kubectl describe ingress main-api-platform```

I got

```
Name:             main-api-platform
Namespace:        default
Address:          
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                 Path  Backends
  ----                 ----  --------
  random-hostname.com  
                       /   main-api-platform:80 (10.244.2.20:80)
Annotations:           kubernetes.io/ingress.class: nginx
                       kubernetes.io/tls-acme: true
                       load-balancer.hetzner.cloud/health-check-port: 30787
                       load-balancer.hetzner.cloud/hostname: random-hostname.com
                       load-balancer.hetzner.cloud/http-redirect-https: false
                       load-balancer.hetzner.cloud/location: nbg1
                       load-balancer.hetzner.cloud/use-private-ip: true
                       load-balancer.hetzner.cloud/uses-proxyprotocol: true
                       meta.helm.sh/release-name: main
                       meta.helm.sh/release-namespace: default
Events:                <none>
```

Dont know this info helps but seems like it takes the annotations... I guess on the wrong place?
