### ISSUE TITLE
2.0.2 - Stuck on masters node creation.

### ISSUE THREAD

**Issue by Alilat-imad** [vitobotta/hetzner-k3s#415]
Scenario to reproduce : 

``` yaml
hetzner_token: <TOKEN>
cluster_name: k3s-cluster
k3s_version: v1.30.3+k3s1
kubeconfig_path: "~/.kube/config"

networking:
  ssh:
    port: 22
    use_agent: false # set to true if your key has a passphrase
    public_key_path: "~/.ssh/id_ed25519.pub"
    private_key_path: "~/.ssh/id_ed25519"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api: # this will firewall port 6443 on the nodes; it will NOT firewall the API load balancer
      - 0.0.0.0/0
  public_network:
    ipv4: false
    ipv6: true
  private_network:
    enabled : true
    subnet: 10.0.0.0/16
    existing_network_name: "ALILAT_NETWORK"
  cni:
    enabled: true
    encryption: false
    mode: flannel

schedule_workloads_on_masters: false
embedded_registry_mirror:
  enabled: true

datastore:
  #mode: etcd # etcd (default) or external
  external_datastore_endpoint: postgresql://<USER>:<PASSWORD>@>PRIVATE_IP_POSTGRES_SERVER>:5432/k3s_cluster?sslmode=prefer

image: debian-12
autoscaling_image: debian-12

masters_pool:
 instance_type: cx22
 instance_count: 3
 location: nbg1

worker_node_pools:
- name: worker-cx32-autoscaled
  instance_type: cx32
  instance_count: 2
  location: nbg1
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 4

post_create_commands:
 - apt update
 - apt upgrade -y
 - apt autoremove -y
```

After exec `hetzner-k3s create --config hetzner-k3s-config.yml | tee create.log`

The output : 

```
hetzner-k3s create --config hetzner-k3s-config.yml | tee create.log
[Configuration] Validating configuration...
[Configuration] ...configuration seems valid.
[SSH key] SSH key already exists, skipping create
[Instance k3s-cluster-master2] Creating instance k3s-cluster-master2 (attempt 1)...
[Instance k3s-cluster-master3] Creating instance k3s-cluster-master3 (attempt 1)...
[Instance k3s-cluster-master1] Creating instance k3s-cluster-master1 (attempt 1)...
[Instance k3s-cluster-master3] Instance status: off
[Instance k3s-cluster-master3] Powering on instance (attempt 1)
[Instance k3s-cluster-master3] Waiting for instance to be powered on...
[Instance k3s-cluster-master2] Instance status: off
[Instance k3s-cluster-master2] Powering on instance (attempt 1)
[Instance k3s-cluster-master1] Instance status: off
[Instance k3s-cluster-master1] Powering on instance (attempt 1)
[Instance k3s-cluster-master2] Waiting for instance to be powered on...
[Instance k3s-cluster-master1] Waiting for instance to be powered on...
[Instance k3s-cluster-master3] Instance status: running
[Instance k3s-cluster-master2] Instance status: running
[Instance k3s-cluster-master1] Instance status: running
[Instance k3s-cluster-master3] Waiting for successful ssh connectivity with instance k3s-cluster-master3...
[Instance k3s-cluster-master2] Waiting for successful ssh connectivity with instance k3s-cluster-master2...
[Instance k3s-cluster-master1] Waiting for successful ssh connectivity with instance k3s-cluster-master1...
[Instance k3s-cluster-master3] Instance k3s-cluster-master3 already exists, skipping create
[Instance k3s-cluster-master1] Instance k3s-cluster-master1 already exists, skipping create
[Instance k3s-cluster-master2] Instance k3s-cluster-master2 already exists, skipping create
[Instance k3s-cluster-master3] Instance status: running
[Instance k3s-cluster-master2] Instance status: running
[Instance k3s-cluster-master1] Instance status: running
[Instance k3s-cluster-master3] Waiting for successful ssh connectivity with instance k3s-cluster-master3...
[Instance k3s-cluster-master2] Waiting for successful ssh connectivity with instance k3s-cluster-master2...
[Instance k3s-cluster-master1] Waiting for successful ssh connectivity with instance k3s-cluster-master1...
[Instance k3s-cluster-master3] Instance k3s-cluster-master3 already exists, skipping create
[Instance k3s-cluster-master1] Instance k3s-cluster-master1 already exists, skipping create
[Instance k3s-cluster-master3] Instance status: running
[Instance k3s-cluster-master1] Instance status: running
[Instance k3s-cluster-master2] Instance k3s-cluster-master2 already exists, skipping create
[Instance k3s-cluster-master2] Instance status: running
[Instance k3s-cluster-master3] Waiting for successful ssh connectivity with instance k3s-cluster-master3...
[Instance k3s-cluster-master1] Waiting for successful ssh connectivity with instance k3s-cluster-master1...
[Instance k3s-cluster-master2] Waiting for successful ssh connectivity with instance k3s-cluster-master2...
Error creating instance: timeout after 00:01:00
Instance creation for k3s-cluster-master3 failed. Try rerunning the create command.
Error creating instance: timeout after 00:01:00
Instance creation for k3s-cluster-master1 failed. Try rerunning the create command.
Error creating instance: timeout after 00:01:00
Instance creation for k3s-cluster-master2 failed. Try rerunning the create command.
```

And then nothing happen, no more attempt no more outputs.

**Comment by vitobotta** [comment]
Please edit and remove your token asap if that's a valid token :) I'll read your message and reply shortly

**Comment by vitobotta** [comment]
You have disabled the public ipv4 interface. Are you executing these commands from a server in the same private network as the cluster? If not that's what you need to do or the computer from which you run commands will not be able to reach the nodes. Also, when you disable the public interface you need some additional setup to be able to use Internet from the nodes and download packages etc. You need to set up the NAT gateway. This of setup is not yet described in the docs since it's less common but for the time being you can refer to the post create commands in https://github.com/vitobotta/hetzner-k3s/discussions/385#discussioncomment-10168998 as an example. But you also need to configure the NAT gateway.

**Comment by Alilat-imad** [comment]
I previously created a server on Hetzner to install PostgreSQL. Since IPv4 came at an additional cost, I opted for IPv6 only and use it for SSH access.

So I need to have the ipv4 enabled even for worker nodes ?

Any way, once I've did the bellow changes, everything works well.

**Comment by Alilat-imad** [comment]
Now I have another issue where I need your precious assistance.

```
networking:
  public_network:
    ipv4: false
    ipv6: true
```

Trying to use a k3s datastore  into my postgres instance instead of the default etcd.
To do that, i've created a private network group where is found my postgres server. Than I created the k3s cluster using that same network group. but it seems that the property `external_datastore_endpoint` is being ignored.

First i thought I've mistaked the url by doing : 

```
datastore:
  external_datastore_endpoint: postgres://user:password@PRIVATE_IP:5432/k3s_cluster_db
```
Than I've fixhed the url to this : 

```
datastore:
  external_datastore_endpoint: postgresql://user:password@POSTGRES_PRIVATE_IP:5432/k3s_cluster_db
```
But it didn't work, (etc is the one being used)

Next obvious verification I've tried was to ssh into the master node and ping POSTGRES_PRIVATE_IP it did work well.

Last check i've did was 

```
sudo apt-get install postgresql-client
psql postgresql://user:password@PRIVATE_IP:5432/k3s_cluster_db
```
It also did work.

**Comment by vitobotta** [comment]
> I previously created a server on Hetzner to install PostgreSQL. Since IPv4 came at an additional cost, I opted for IPv6 only and use it for SSH access.
> 
> So I need to have the ipv4 enabled even for worker nodes ?
> 
> Any way, once I've did the bellow changes, everything works well.

You can disable the public IPs if you prefer, but in order to access the cluster with hetzner-k3s you need to run it from a server in the same private network. I haven't tested with ipv6 only to be honest.

**Comment by vitobotta** [comment]
> Now I have another issue where I need your precious assistance.
> 
> ```
> networking:
>   public_network:
>     ipv4: false
>     ipv6: true
> ```
> 
> Trying to use a k3s datastore into my postgres instance instead of the default etcd. To do that, i've created a private network group where is found my postgres server. Than I created the k3s cluster using that same network group. but it seems that the property `external_datastore_endpoint` is being ignored.
> 
> First i thought I've mistaked the url by doing :
> 
> ```
> datastore:
>   external_datastore_endpoint: postgres://user:password@PRIVATE_IP:5432/k3s_cluster_db
> ```
> 
> Than I've fixhed the url to this :
> 
> ```
> datastore:
>   external_datastore_endpoint: postgresql://user:password@POSTGRES_PRIVATE_IP:5432/k3s_cluster_db
> ```
> 
> But it didn't work, (etc is the one being used)
> 
> Next obvious verification I've tried was to ssh into the master node and ping POSTGRES_PRIVATE_IP it did work well.
> 
> Last check i've did was
> 
> ```
> sudo apt-get install postgresql-client
> psql postgresql://user:password@PRIVATE_IP:5432/k3s_cluster_db
> ```
> 
> It also did work.

You forgot to set the mode of the datastore to `external`:

```yaml
datastore:
  mode: external
  external_datastore_endpoint: postgres://....
```
