### ISSUE TITLE
2.0.2 Error creating instance: Expected Array or Hash, not Nil

### ISSUE THREAD

**Issue by ironytr** [vitobotta/hetzner-k3s#418]
hello, im trying to create a cluster with new versions but i got error

```
hetzner_token: 
cluster_name: xxx
kubeconfig_path: "./kubeconfig"
k3s_version: v1.30.3+k3s1

networking:
  ssh:
    port: 22
    use_agent: false # set to true if your key has a passphrase
    public_key_path: "~/.ssh/id_ed25519.pub"
    private_key_path: "~/.ssh/id_ed25519"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api: # this will firewall port 6443 on the nodes; it will NOT firewall the API load balancer
      - 0.0.0.0/0
  public_network:
    ipv4: true
    ipv6: true
  private_network:
    enabled : true
    subnet: 10.0.0.0/16
    existing_network_name: ""
  cni:
    enabled: true
    encryption: false
    mode: flannel

  # cluster_cidr: 10.244.0.0/16 # optional: a custom IPv4/IPv6 network CIDR to use for pod IPs
  # service_cidr: 10.43.0.0/16 # optional: a custom IPv4/IPv6 network CIDR to use for service IPs. Warning, if you change this, you should also change cluster_dns!
  # cluster_dns: 10.43.0.10 # optional: IPv4 Cluster IP for coredns service. Needs to be an address from the service_cidr range


# manifests:
#   cloud_controller_manager_manifest_url: "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.20.0/ccm-networks.yaml"
#   csi_driver_manifest_url: "https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.9.0/deploy/kubernetes/hcloud-csi.yml"
#   system_upgrade_controller_deployment_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/system-upgrade-controller.yaml"
#   system_upgrade_controller_crd_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/crd.yaml"
#   cluster_autoscaler_manifest_url: "https://raw.githubusercontent.com/kubernetes/autoscaler/master/cluster-autoscaler/cloudprovider/hetzner/examples/cluster-autoscaler-run-on-master.yaml"

# datastore:
#   mode: etcd # etcd (default) or external
#   external_datastore_endpoint: postgres://....

schedule_workloads_on_masters: false

# image: rocky-9 # optional: default is ubuntu-24.04
# autoscaling_image: 103908130 # optional, defaults to the `image` setting
# snapshot_os: microos # optional: specified the os type when using a custom snapshot

masters_pool:
  instance_type: cx21
  instance_count: 1
  location: nbg1
worker_node_pools:
- name: main-static-a
  instance_type: ccx23
  instance_count: 1
  location: nbg1
- name: main-static-b
  instance_type: ccx23
  instance_count: 1
  location: nbg1
- name: medium-autoscaled
  instance_type: ccx13
  instance_count: 1
  location: nbg1
  autoscaling:
    enabled: true
    min_instances: 1
    max_instances: 3

embedded_registry_mirror:
  enabled: true

# additional_packages:
# - somepackage

post_create_commands:
- apt update
- apt upgrade -y
- apt autoremove -y

# kube_api_server_args:
# - arg1
# - ...
# kube_scheduler_args:
# - arg1
# - ...
# kube_controller_manager_args:
# - arg1
# - ...
# kube_cloud_controller_manager_args:
# - arg1
# - ...
# kubelet_args:
# - arg1
# - ...
# kube_proxy_args:
# - arg1
# - ...
# api_server_hostname: k8s.example.com # optional: DNS for the k8s API LoadBalancer. After the script has run, create a DNS record with the address of the API LoadBalancer.
```

`hetzner-k3s create --config cluster_config.yaml | tee create.log
[Configuration] Validating configuration...
[Configuration] ...configuration seems valid.
[Private Network] Private network already exists, skipping create
[SSH key] SSH key already exists, skipping create
[Placement groups] Deleting unused placement group esnaf1-main-static-a-2...
[Placement groups] ...placement group esnaf1-main-static-a-2 deleted
[Placement groups] Deleting unused placement group esnaf1-main-static-b-2...
[Placement groups] ...placement group esnaf1-main-static-b-2 deleted
[Placement groups] Deleting unused placement group esnaf1-masters...
[Placement groups] ...placement group esnaf1-masters deleted
[Placement groups] Creating placement group esnaf1-masters...
[Placement groups] ...placement group esnaf1-masters created
[Placement groups] Creating placement group esnaf1-main-static-a-2...
[Placement groups] Creating placement group esnaf1-main-static-b-2...
[Placement groups] ...placement group esnaf1-main-static-b-2 created
[Placement groups] ...placement group esnaf1-main-static-a-2 created
Error creating instance: Expected Array or Hash, not Nil
Instance creation for esnaf1-master1 failed. Try rerunning the create command.
`

second question is do i need to remove comments sections from manifets to work as old version that installs hcloud and necessary tools?

````
# manifests:
#   cloud_controller_manager_manifest_url: "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.20.0/ccm-networks.yaml"
#   csi_driver_manifest_url: "https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.9.0/deploy/kubernetes/hcloud-csi.yml"
#   system_upgrade_controller_deployment_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/system-upgrade-controller.yaml"
#   system_upgrade_controller_crd_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/crd.yaml"
#   cluster_autoscaler_manifest_url: "https://raw.githubusercontent.com/kubernetes/autoscaler/master/cluster-autoscaler/cloudprovider/hetzner/examples/cluster-autoscaler-run-on-master.yaml"
````
