### ISSUE TITLE
Node labels not possible with include_instance_type_in_instance_name

### ISSUE THREAD

**Issue by ValentinVoigt** [vitobotta/hetzner-k3s#425]
I'm trying to update our clusters to v2, but I am having trouble with the node labels. I think using labels (and possibly taints) on a cluster with `include_instance_type_in_instance_name` enabled is currently not possible. It works fine on masters, though. These are the last few lines of output:

```
[Instance test-cx22-pool-asdf-worker1] [INFO]  systemd: Starting k3s-agent
[Instance test-cx22-pool-asdf-worker1] ...k3s has been deployed to worker test-cx22-pool-asdf-worker1.
[Node labels] 
Adding labels to masters_pool pool workers...
[Node labels] node/test-cx22-master1 not labeled
[Node labels] ...node labels applied
[Node labels] 
Adding labels to asdf pool workers...
error: resource(s) were provided, but no name was specified
[Node labels] : error: resource(s) were provided, but no name was specified
```

I also did some digging and I think the issue might be related to [this line of code](https://github.com/vitobotta/hetzner-k3s/blob/74da9f6d260f348b957e20709d02c68adf911d38/src/kubernetes/installer.cr#L325), as it does not check for the configured naming scheme. Not sure, though.

**Workaround**: I just removed the labels and taints from the config file. Existing labels and taints will not be removed from the nodes.

This is the config I used for testing. (I'm using an existing network.)

<details>
  <summary>cluster.yaml</summary>

```yaml
---
hetzner_token:
cluster_name: test
kubeconfig_path: "./kubeconfig"
k3s_version: v1.30.4+k3s1
schedule_workloads_on_masters: true
include_instance_type_in_instance_name: true
embedded_registry_mirror:
  enabled: false

networking:
  ssh:
    port: 22
    use_agent: true
    public_key_path: "~/.ssh/id_rsa.pub"
    private_key_path: "~/.ssh/id_rsa"
  allowed_networks:
    ssh:
      - 
      - 
    api:
      - 
      - 
  public_network:
    ipv4: true
    ipv6: false
  private_network:
    enabled: true
    subnet: 10.0.0.0/16
    existing_network_name: "network-1"
  cni:
    enable: true
    encryption: false
    mode: flannel

datastore:
  mode: etcd
  external_datastore_endpoint: postgres://....

masters_pool:
  instance_type: cx22
  instance_count: 1
  location: nbg1
  labels:
    - key: foo
      value: bar

worker_node_pools:
  - name: asdf
    instance_type: cx22
    instance_count: 1
    location: nbg1
    labels:
      - key: foo
        value: bar
```

</details>
