### ISSUE TITLE
hetzner-k3s Failed to create private network JSON error A valid JSON document is required

### ISSUE THREAD

**Issue by LarvePoire** [vitobotta/hetzner-k3s#426]
Hello,

I'm encountering an issue while using `hetzner-k3s` to create a Kubernetes cluster. The process fails during the private network creation with the following error message:
```
[Configuration] Validating configuration...
[Configuration] ...configuration seems valid.
[Private Network] Creating private network...
[Private Network] Failed to create private network: {
    "error": {
        "code": "json_error",
        "message": "A valid JSON document is required."
    }
}
```

I am currently on Step 5 of the [Setting up a Cluster](https://github.com/vitobotta/hetzner-k3s/blob/main/docs/Setting%20up%20a%20cluster.md) guide. Although the configuration is validated, the error persists when I run the following command:
```bash
hetzner-k3s create --config hetzner-k3s_cluster_config.yaml
```

Below is the YAML configuration file I am using:
```yaml
hetzner_token: 'secret'
cluster_name: hello-world
kubeconfig_path: "./kubeconfig"
k3s_version: v1.30.4+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
use_ssh_agent: true
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
schedule_workloads_on_masters: false
masters_pool:
  instance_type: cx22
  instance_count: 3
  location: hel1
worker_node_pools:
  - name: small
    instance_type: ccx13
    instance_count: 1
    location: hel1
```

I'm wondering if this issue might be due to a configuration mistake or if it could be a bug in the current version of `hetzner-k3s`.

If anyone has encountered this issue before or can provide advice on how to resolve this error, I would greatly appreciate your help.

Thank you in advance!
