### ISSUE TITLE
JSON error while creating private network despite using updated YAML format

### ISSUE THREAD

**Issue by LarvePoire** [vitobotta/hetzner-k3s#428]
Hello,

I'm experiencing the same issue I reported earlier with the JSON error during private network creation, even though I am now using the updated YAML configuration format as per the [Creating a Cluster](https://github.com/vitobotta/hetzner-k3s/blob/main/docs/Creating_a_cluster.md) guide.

Here’s the error I’m seeing:

```
[Configuration] Validating configuration...
[Configuration] ...configuration seems valid.
[Private Network] Creating private network...
[Private Network] Failed to create private network: {
    "error": {
        "code": "json_error",
        "message": "A valid JSON document is required."
    }
}
```

And here is the YAML configuration file I'm currently using:

```yaml
---
hetzner_token: secret
cluster_name: demo-vitobotta
kubeconfig_path: "./kubeconfig"
k3s_version: v1.30.4+k3s1

networking:
  ssh:
    port: 22
    use_agent: true
    public_key_path: "~/.ssh/id_ed25519.pub"
    private_key_path: "~/.ssh/id_ed25519"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api:
      - 0.0.0.0/0
  public_network:
    ipv4: true
    ipv6: true
  private_network:
    enabled: true
    subnet: 10.0.0.0/16
    existing_network_name: ""
  cni:
    enabled: true
    encryption: false
    mode: flannel

schedule_workloads_on_masters: false

masters_pool:
  instance_type: cx22
  instance_count: 3
  location: hel1

worker_node_pools:
  - name: small-static
    instance_type: ccx13
    instance_count: 1
    location: hel1
  - name: medium-autoscaled
    instance_type: ccx13
    instance_count: 2
    location: hel1
    autoscaling:
      enabled: true
      min_instances: 0
      max_instances: 3

embedded_registry_mirror:
  enabled: true

```

I want to mention that I’m relatively new to Kubernetes, so it's entirely possible that I might have missed something that could be obvious to more experienced users. However, I’m eager to learn and understand how to properly set this up, as I’m excited to start using this wonderful technology.

If there’s something I might have overlooked, I would greatly appreciate any guidance or pointers. I really want to get this working and learn the best practices along the way.

Thank you so much for your help!
