### ISSUE TITLE
question about annotation

### ISSUE THREAD

**Issue by jboesh** [vitobotta/hetzner-k3s#44]
Hi me again, yeah sorry I'm quite busy with the cluster lately
I applied the following custom configuration to the ingress nginx:

```
controller:
  kind: DaemonSet
  service:
    annotations:
      load-balancer.hetzner.cloud/location: nbg1
      load-balancer.hetzner.cloud/name: kluster-ingress-nginx
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/uses-proxyprotocol: 'true'
```

but for some reason my oauth2proxy service is not working correctly. [this ](https://github.com/oauth2-proxy/oauth2-proxy/issues/969)page describes basically my issue. Now is see that I miss the hostname annotation. this could be related (not sure but I need to find out)
`      load-balancer.hetzner.cloud/hostname: <a valid fqdn>`

Can you tell me what this should be?
the same as the cloud/name of the nginx ingress loadbalancer? (kluster-ingress-nginx) or the ip? but fqdn = only a name right?
or should this be the domain name I'm using in the cert-manager?

thanks again!
