### ISSUE TITLE
Cannot update cluster config: node pool has an invalid instance type

### ISSUE THREAD

**Issue by alamos-gmbh** [vitobotta/hetzner-k3s#446]
Hello,

we wanted to add some new nodes to our worker node pools, but hetzner changed vm types.
An extract from our cluster config (example only)

```
masters_pool:
  instance_type: cx21
  instance_count: 3
  location: fsn1
worker_node_pools:
- name: small-power
  instance_type: cx21
  instance_count: 3
  location: fsn1
```

cx21 does not exist anymore, so the script cannot validate the cluster-config

```
[Configuration] Validating configuration...
[Configuration] Some information in the configuration file requires your attention:
[Configuration]  - masters node pool has an invalid instance type
[Configuration]  - small-power node pool has an invalid instance type
```

Is there any option to add new nodes without using (ignoring?) the existing master node and worker node pools?
We thought about removing the existing pools and just add new pools with the new hetzner types, but I guess this will recreate the control plane, right?

Is it possible to create some kind of alias, so cx21 (alias) will be treated like cx22 (currently existing in hetzner cloud)
We're afraid of losing production data.

Thanks in advance!

(Will ask the CEO about sponsoring this great project!!)
