### ISSUE TITLE
issues creating the cluster - 

### ISSUE THREAD

**Issue by yoplait** [vitobotta/hetzner-k3s#45]
Hi again, well I am giving it another try as I am following the project and seems I am stuck on something here .. while I can see the resources created on the cloud side ... seems like something doesn't follow along ....

```
jc@infra-0:~$ hetzner-k3s create-cluster --config-file cluster_config.yaml

Placement group already exists, skipping.
Firewall already exists, skipping.
Private network already exists, skipping.
SSH key already exists, skipping.
API load balancer already exists, skipping.


Creating server k3s-wireguard-cpx21-master1...
Creating server k3s-wireguard-cpx21-pool-small-worker2...
Creating server k3s-wireguard-cpx21-pool-small-worker3...
Creating server k3s-wireguard-cpx21-master3...
Creating server k3s-wireguard-cpx21-pool-small-worker1...
Creating server k3s-wireguard-cpx21-master2...
...server k3s-wireguard-cpx21-pool-small-worker3 created.

Error creating server k3s-wireguard-cpx21-master2. Response details below:

#<HTTP::Response/1.1 403 Forbidden {"Date"=>"Wed, 01 Dec 2021 18:28:58 GMT", "Content-Type"=>"application/json", "Content-Length"=>"202", "Connection"=>"close", "ratelimit-limit"=>"3600", "ratelimit-remaining"=>"3583", "ratelimit-reset"=>"1638383354", "x-correlation-id"=>"74604510-3a34-4d9b-ad6f-815e3ece5f4a", "Strict-Transport-Security"=>"max-age=15724800; includeSubDomains", "Access-Control-Allow-Origin"=>"*", "Access-Control-Allow-Credentials"=>"true"}>
Error creating server k3s-wireguard-cpx21-pool-small-worker1. Response details below:

#<HTTP::Response/1.1 403 Forbidden {"Date"=>"Wed, 01 Dec 2021 18:28:58 GMT", "Content-Type"=>"application/json", "Content-Length"=>"202", "Connection"=>"close", "ratelimit-limit"=>"3600", "ratelimit-remaining"=>"3584", "ratelimit-reset"=>"1638383353", "x-correlation-id"=>"0a07d11e-a88e-4e57-876f-ad7722144ce2", "Strict-Transport-Security"=>"max-age=15724800; includeSubDomains", "Access-Control-Allow-Origin"=>"*", "Access-Control-Allow-Credentials"=>"true"}>
...server k3s-wireguard-cpx21-pool-small-worker2 created.

...server k3s-wireguard-cpx21-master3 created.

...server k3s-wireguard-cpx21-master1 created.


Waiting for server k3s-wireguard-cpx21-master1 to be up...
Waiting for server k3s-wireguard-cpx21-pool-small-worker2 to be up...
Waiting for server k3s-wireguard-cpx21-master3 to be up...
#<Thread:0x00007ff16c059cf8 /home/jc/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:168 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	7: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:168:in `block (2 levels) in create_resources'
	6: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:460:in `wait_for_ssh'
	5: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	4: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	3: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	2: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	1: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/home/jc/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:461:in `block in wait_for_ssh': undefined method `[]' for nil:NilClass (NoMethodError)
#<Thread:0x00007ff16c059c08 /home/jc/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:168 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	7: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:168:in `block (2 levels) in create_resources'
	6: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:460:in `wait_for_ssh'
	5: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	4: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	3: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	2: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	1: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/home/jc/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:461:in `block in wait_for_ssh': undefined method `[]' for nil:NilClass (NoMethodError)
Waiting for server k3s-wireguard-cpx21-pool-small-worker3 to be up...
Waiting for server k3s-wireguard-cpx21-pool-small-worker3 to be up...
Waiting for server k3s-wireguard-cpx21-master3 to be up...
Waiting for server k3s-wireguard-cpx21-pool-small-worker2 to be up...
Waiting for server k3s-wireguard-cpx21-master1 to be up...
Waiting for server k3s-wireguard-cpx21-master1 to be up...
Waiting for server k3s-wireguard-cpx21-pool-small-worker3 to be up...
Waiting for server k3s-wireguard-cpx21-pool-small-worker2 to be up...
Waiting for server k3s-wireguard-cpx21-master3 to be up...
Waiting for server k3s-wireguard-cpx21-master1 to be up...
Waiting for server k3s-wireguard-cpx21-pool-small-worker3 to be up...
Waiting for server k3s-wireguard-cpx21-master3 to be up...
Waiting for server k3s-wireguard-cpx21-pool-small-worker2 to be up...
Waiting for server k3s-wireguard-cpx21-pool-small-worker3 to be up...
Waiting for server k3s-wireguard-cpx21-master1 to be up...
Waiting for server k3s-wireguard-cpx21-master3 to be up...
Waiting for server k3s-wireguard-cpx21-pool-small-worker2 to be up...
Waiting for server k3s-wireguard-cpx21-master1 to be up...
Waiting for server k3s-wireguard-cpx21-pool-small-worker3 to be up...
Waiting for server k3s-wireguard-cpx21-pool-small-worker2 to be up...
Waiting for server k3s-wireguard-cpx21-master3 to be up...
Waiting for server k3s-wireguard-cpx21-pool-small-worker2 to be up...
Waiting for server k3s-wireguard-cpx21-master1 to be up...
Waiting for server k3s-wireguard-cpx21-master3 to be up...
Waiting for server k3s-wireguard-cpx21-pool-small-worker3 to be up...
...server k3s-wireguard-cpx21-master1 is now up.
Waiting for server k3s-wireguard-cpx21-pool-small-worker2 to be up...
Waiting for server k3s-wireguard-cpx21-master3 to be up...
Waiting for server k3s-wireguard-cpx21-pool-small-worker3 to be up...
...server k3s-wireguard-cpx21-pool-small-worker3 is now up.
Traceback (most recent call last):
	7: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:168:in `block (2 levels) in create_resources'
	6: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:460:in `wait_for_ssh'
	5: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	4: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	3: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	2: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	1: from /home/jc/.rbenv/versions/2.7.5/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/home/jc/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:461:in `block in wait_for_ssh': undefined method `[]' for nil:NilClass (NoMethodError)
jc@infra-0:~$
```

My configuration looks like:
```
cat << 'EOF' > cluster_config.yaml
---
hetzner_token: "2qSTPIXRedactedY7l7hQ4L"
cluster_name: k3s-wireguard
kubeconfig_path: "./kubeconfig"
k3s_version: v1.21.3+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
ssh_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: hel1
schedule_workloads_on_masters: false
masters:
  instance_type: cpx21
  instance_count: 3
worker_node_pools:
- name: small
  instance_type: cpx21
  instance_count: 3
EOF
```

My env looks like:

```
jc@infra-0:~$ docker --version
Docker version 20.10.11, build dea9396
jc@infra-0:~$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
jc@infra-0:~$ ruby -v
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]
jc@infra-0:~$
```

So as you can see I can connect over ssh like:

```
jc@infra-0:~$ ssh -i ~/.ssh/id_rsa root@95.111.222.111
Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-90-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed 01 Dec 2021 06:38:15 PM UTC

  System load:             0.04
  Usage of /:              2.1% of 74.82GB
  Memory usage:            5%
  Swap usage:              0%
  Processes:               150
  Users logged in:         0
  IPv4 address for enp7s0: 10.0.0.6
  IPv4 address for eth0:   95.217.21.109
  IPv6 address for eth0:   2a01:4f9:c010:3690::1


5 updates can be applied immediately.
4 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable


Last login: Wed Dec  1 18:37:34 2021 from 95.111.222.111
root@k3s-wireguard-cpx21-pool-small-worker2:~#
```

Thanks!

**Comment by vitobotta** [comment]
If you rerun the create command with the same configuration do you still get errors? Also can you create a server manually from the Hetzner console? Are you using the gem or the Docker image?

**Comment by vitobotta** [comment]
If you set `export KUBECONFIG=..` with the path of the kubeconfig can you see the nodes?

**Comment by yoplait** [comment]
ei @vitobotta thanks for the time and effort i want to close the issue .. so after reviewing and clarify the config file I am online!

```
jc@infra-0:~$ KUBECONFIG=kubeconfig kubectl get nodes
NAME                                     STATUS   ROLES                       AGE    VERSION
k3s-wireguard-cpx21-master1              Ready    control-plane,etcd,master   101s   v1.21.3+k3s1
k3s-wireguard-cpx21-pool-small-worker1   Ready    <none>                      72s    v1.21.3+k3s1
k3s-wireguard-cpx21-pool-small-worker2   Ready    <none>                      72s    v1.21.3+k3s1
jc@infra-0:~$ kubectl get pods --all-namespaces -o wide
NAMESPACE        NAME                                               READY   STATUS    RESTARTS   AGE     IP           NODE                                     NOMINATED NODE   READINESS GATES
kube-system      coredns-7448499f4d-qmzgh                           1/1     Running   0          2m55s   10.244.1.3   k3s-wireguard-cpx21-pool-small-worker1   <none>           <none>
kube-system      hcloud-cloud-controller-manager-666d7bbfcc-4w8qq   1/1     Running   0          2m39s   10.0.0.2     k3s-wireguard-cpx21-pool-small-worker1   <none>           <none>
kube-system      hcloud-csi-controller-0                            5/5     Running   0          2m38s   10.244.2.3   k3s-wireguard-cpx21-pool-small-worker2   <none>           <none>
kube-system      hcloud-csi-node-4vr68                              3/3     Running   0          2m38s   10.244.0.2   k3s-wireguard-cpx21-master1              <none>           <none>
kube-system      hcloud-csi-node-9qvfp                              3/3     Running   0          2m38s   10.244.2.2   k3s-wireguard-cpx21-pool-small-worker2   <none>           <none>
kube-system      hcloud-csi-node-s2525                              3/3     Running   0          2m38s   10.244.1.2   k3s-wireguard-cpx21-pool-small-worker1   <none>           <none>
system-upgrade   system-upgrade-controller-7bc9cd65fb-xmkwg         1/1     Running   0          2m37s   10.244.0.3   k3s-wireguard-cpx21-master1              <none>           <none>
jc@infra-0:~$
jc@infra-0:~$ ll
total 45924
drwxr-xr-x  9 jc   jc       4096 Dec  3 11:01 ./
drwxr-xr-x  4 root root     4096 Dec  1 10:38 ../
-rw-------  1 jc   jc      26678 Dec  3 14:29 .bash_history
-rw-r--r--  1 jc   jc        220 Feb 25  2020 .bash_logout
-rw-r--r--  1 jc   jc       4467 Dec  2 16:13 .bashrc
drwx------  3 jc   jc       4096 Dec  1 10:38 .cache/
-rw-r--r--  1 jc   jc          0 Nov 23 10:42 .cloud-locale-test.skip
-rw-rw-r--  1 jc   jc        490 Dec  2 16:36 cluster_config.yaml
drwxrwxr-x  3 jc   jc       4096 Dec  1 10:55 .config/
drwxrwxr-x  4 jc   jc       4096 Dec  1 10:57 .gem/
drwxr-x---  3 jc   jc       4096 Dec  3 11:01 .kube/
-rw--w----  1 jc   jc       3009 Dec 10 16:03 kubeconfig
-rw-rw-r--  1 jc   jc   46931968 Dec  2 16:35 kubectl
-rw-rw-r--  1 jc   jc         64 Dec  2 16:35 kubectl.sha256
drwxrwxr-x  3 jc   jc       4096 Dec  1 11:04 .local/
-rw-r--r--  1 jc   jc        972 Dec  2 16:34 .profile
drwxrwxr-x 13 jc   jc       4096 Dec  1 11:06 .rbenv/
drwx------  2 jc   jc       4096 Dec  1 18:37 .ssh/
-rw-r--r--  1 jc   jc          0 Nov 25 18:02 .sudo_as_admin_successful
jc@infra-0:~$
```

**Comment by vitobotta** [comment]
Hi, glad to hear all is sorted! You can see all the available annotations for load balancers here https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/b54847b9163a3fc39dd902ab2f5f0494003b7230/internal/annotation/load_balancer.go

**Comment by yoplait** [comment]
One question about this, do I need to install ingress here? like Nginx or Traefik .. I am trying to expose a deployment and I am having issues with some errors.. i see there is no ingress deployed ... any advice on that?

**Comment by vitobotta** [comment]
You can either create a service of type load balancer just for the deployment or - better - install an ingress controller like Nginx so you can share a single load balancer between multiple deployments via ingress resources. I do this usually.

**Comment by yoplait** [comment]
I tried with different projects and doesnt work:

```
kubectl create namespace apps

cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: carolyne-service
  namespace: apps
  annotations:
    load-balancer.hetzner.cloud/location: hel1
    load-balancer.hetzner.cloud/name: carolyne
    load-balancer.hetzner.cloud/protocol: http
    load-balancer.hetzner.cloud/health-check-http-path: /
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
    # load-balancer.hetzner.cloud/http-redirect-https: 'false'
    # service.beta.kubernetes.io/brightbox-load-balancer-healthcheck-request: /
    # load-balancer.hetzner.cloud/hostname: midomain.com
  labels:
    app: carolyne
spec:
  type: LoadBalancer
  selector:
    app: carolyne
  ports:
    - port: 4000
EOF


cat <<EOF | kubectl apply -f -
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /\$1
  name: apps-ingress-rules
  namespace: apps
spec:
  rules:
  - host: midomain.com
    http:
      paths:
      - backend:
          service: 
            name: carolyne-service
            port: 
              number: 4000
        path: /(.*)
        pathType: Prefix
EOF

```

I am pointing on that in my hosts

```
| => ping midomain.com
PING midomain.com (95.217.169.56): 56 data bytes
64 bytes from 95.217.169.56: icmp_seq=0 ttl=46 time=68.298 ms```

but doesn't work and in the cluster looks ok

```
jc@infra-0:~$ kubectl get ingress,svc,pods -n apps

NAME                       TYPE           CLUSTER-IP    EXTERNAL-IP                                   PORT(S)          AGE
service/carolyne-service   LoadBalancer   10.43.82.12   10.0.0.5,2a01:4f9:c01e:1ae::1,95.217.169.56   4000:32590/TCP   4m1s

NAME                            READY   STATUS    RESTARTS   AGE
pod/carolyne-787f985ddc-7wc5p   1/1     Running   0          4m19s
pod/carolyne-787f985ddc-9vnb9   1/1     Running   0          4m19s
pod/carolyne-787f985ddc-s6prx   1/1     Running   0          4m19s
jc@infra-0:~$
```

**Comment by vitobotta** [comment]
The service should have also the targetPort that is the port of the container where the service should connect to. Anyway I recommend to install an ingress controller.

**Comment by yoplait** [comment]
Hi @vitobotta I already checked that but still no luck .... weird:

```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carolyne
  namespace: apps
  labels:
    app: carolyne
spec:
  replicas: 3
  selector:
    matchLabels:
      app: carolyne
  template:
    metadata:
      labels:
        app: carolyne
    spec:
      containers:
        - name: carolyne
          image: jacqueline/carolyne:latest
          ports:
            - containerPort: 4000
EOF
```

and the service:

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: carolyne-service
  namespace: apps
  annotations:
    load-balancer.hetzner.cloud/location: hel1
    load-balancer.hetzner.cloud/name: carolyne
    load-balancer.hetzner.cloud/protocol: HTTP
    load-balancer.hetzner.cloud/health-check-http-path: /
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
    # load-balancer.hetzner.cloud/http-redirect-https: 'false'
    # service.beta.kubernetes.io/brightbox-load-balancer-healthcheck-request: /
    # load-balancer.hetzner.cloud/hostname: midomain.com
  labels:
    app: carolyne
spec:
  type: LoadBalancer
  selector:
    app: carolyne
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
EOF
```


before to make this more complicated with ingress ... any suggestion??

**Comment by yoplait** [comment]
ok i got it .. I did a service describe and i got the node port:

```
  ports:
  - nodePort: 31052
    port: 80
    protocol: TCP
    targetPort: 4000

````

looks for some reason that is blocked from external access... can be the yaml description:
```
ssh_allowed_networks:
  - 0.0.0.0/0
  ```

so we should open some rule to open those ports from the load balancer to those ports as I can do in that server a curl localhost to that port:

```
root@k3s-wireguard-cpx21-pool-small-worker1:~# curl -I http://localhost:31052
HTTP/1.1 200 OK
Date: Sat, 11 Dec 2021 18:27:57 GMT
Content-Length: 87
Content-Type: text/plain; charset=utf-8

root@k3s-wireguard-cpx21-pool-small-worker1:~# curl -vv http://localhost:31052
*   Trying ::1:31052...
* TCP_NODELAY set
* connect to ::1 port 31052 failed: Connection refused
*   Trying 127.0.0.1:31052...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 31052 (#0)
> GET / HTTP/1.1
> Host: localhost:31052
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Sat, 11 Dec 2021 18:28:07 GMT
< Content-Length: 87
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
Caroline says hello. I am the Cluster Asset Registration Overview Like I Never Expectedroot@k3s-wireguard-cpx21-pool-small-worker1:~#
root@k3s-wireguard-cpx21-pool-small-worker1:~#
```

from that node to that node ...

**Comment by vitobotta** [comment]
Allowed networks for SSH connection are unrelated. Has the load balancer actually been created?

**Comment by yoplait** [comment]
Yes it is ..... and I tested from other nodes in hetzner opening that socket in the workers and that works so looks is from the load balancer to the service ....

**Comment by yoplait** [comment]
ok solved .. look to disable ingress ....
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: carolyne-service
  namespace: apps
  annotations:
    load-balancer.hetzner.cloud/location: hel1
    load-balancer.hetzner.cloud/name: carolyne
    load-balancer.hetzner.cloud/protocol: http
    load-balancer.hetzner.cloud/health-check-http-path: /
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/disable-private-ingress: "false"
    # load-balancer.hetzner.cloud/disable-private-ingress: "true"
    # load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
    # load-balancer.hetzner.cloud/http-redirect-https: 'false'
    # service.beta.kubernetes.io/brightbox-load-balancer-healthcheck-request: /
    # load-balancer.hetzner.cloud/hostname: midomain.com
  labels:
    app: carolyne
spec:
  type: LoadBalancer
  selector:
    app: carolyne
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 4000
EOF
```

good stuff! Thanks again!
