### ISSUE TITLE
[Bug] Cannot assign labels when autoscaling config exists

### ISSUE THREAD

**Issue by trinhthinh388** [vitobotta/hetzner-k3s#459]
Hi team,
I've been trying out Hetzner K3s for my pet project and it is really great.
Anyway, there is an issue with labels assignment when a node pool also contains an autoscaling configs.

My configs is as follow:
```
- name: general-worker
    instance_type: cax11
    instance_count: 1
    location: fsn1
    labels:
      - key: purpose
        value: general

  - name: database-worker
    instance_type: cax11
    instance_count: 1
    location: fsn1
    labels:
      - key: purpose
        value: database
    autoscaling:
      enabled: true
      min_instances: 0
      max_instances: 3
```
And when I run the `create`  command, it gave me this error:

```
[Node labels] 
Adding labels to general-worker pool workers...
[Node labels] node/redge-develop-pool-general-worker-worker1 not labeled
[Node labels] ...node labels applied
[Node labels] 
Adding labels to database-worker pool workers...
error: resource(s) were provided, but no name was specified
[Node labels] : error: resource(s) were provided, but no name was specified
```
