### ISSUE TITLE
deploy master nodes in different locations

### ISSUE THREAD

**Issue by iSuslov** [vitobotta/hetzner-k3s#472]
follow up from here https://github.com/vitobotta/hetzner-k3s/issues/165

ability to have master nodes in different locations like that:
```
masters_pool:
- name: fsn-master
    instance_type: cx11
    instance_count: 2
    location: fsn1
- name: nbg-master
    instance_type: cx11
    instance_count: 1
    location: nbg1
```
seems to be missing, however according to this comment https://github.com/vitobotta/hetzner-k3s/issues/165#issuecomment-1446941129 it was planned.
