### ISSUE TITLE
Multiple services using the same loadbalancer

### ISSUE THREAD

**Issue by lukeberry99** [vitobotta/hetzner-k3s#497]
I'm trying to reuse the same loadbalancer for multiple services, in my example I'm deploying two very simple webapps using, both running on port 80.

This is the loadbalancer for the first:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: polly-lb
  annotations:
    load-balancer.hetzner.cloud/hostname: svc1.domain.dev
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/name: test-lb
spec:
  selector:
    app.kubernetes.io/instance: svc1
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  type: LoadBalancer
---
```

And the second

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: new-lb
  annotations:
    load-balancer.hetzner.cloud/hostname: svc2.domain.dev
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/name: test-lb
spec:
  selector:
    app.kubernetes.io/instance: svc2
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  type: LoadBalancer
---
```

However both domains are showing svc1, any ideas? Am I doing this right?
