### ISSUE TITLE
Having problems with NodePort

### ISSUE THREAD

**Issue by Xalaxis** [vitobotta/hetzner-k3s#5]
Hi there, loving this tool!

I'm having some problems getting NodePort services working. For some reason, even if I disable the automatically created firewalls, attempting to access a service using a NodePort configuration doesn't seem to work. Do you have any suggestions?

**Comment by Xalaxis** [comment]
Here's the yaml I'm using. It should expose a filebrowser web server (HTTP) on the dynamic NodePort

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openttd-test-50
  labels:
    dbOwnerID: '1'
    app: openttd
spec:
  securityContext:
    runAsUser: 1099
    runAsGroup: 1099
    fsGroup: 1099
  selector:
    matchLabels:
      app: openttd
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  serviceName: openttd
  podManagementPolicy: Parallel
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        labels:
          dbownerid: '1'
        annotations: {}
        name: openttd-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        dbOwnerID: '1'
        app: openttd
        octopusexport: OctopusExport
    spec:
      containers:
        - name: openttd
          image: redditopenttd/openttd
          terminationMessagePolicy: File
          ports:
            - name: openttd
              containerPort: 3979
              protocol: TCP
          volumeMounts:
            - name: openttd-data
              mountPath: /data
              subPath: ''
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
        - name: filebrowser
          image: filebrowser/filebrowser
          ports:
            - name: filebrowser-web
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: openttd-data
              mountPath: /data
              subPath: ''
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser-service
spec:
  type: NodePort
  selector:
    app: openttd
  ports:
    - port: 80
```
