### ISSUE TITLE
How to add labels to an autoscaled worker node?

### ISSUE THREAD

**Issue by jampy** [vitobotta/hetzner-k3s#526]
In my config I have...

```yaml
masters_pool:
  instance_type: cpx21
  instance_count: 3
  location: nbg1

worker_node_pools:
  - name: worker
    instance_type: cpx41
    instance_count: 3
    location: nbg1
    labels:
      - key: node-role.kubernetes.io/worker
        value: "true"
    autoscaling:
      enabled: true
      min_instances: 2
      max_instances: 5
```

...and no other nodes.

Since I need to configure a Helm chart to exclude DaemonSet Pods from the master nodes, I tried to add the `labels` above.

However, `kubectl describe node xxx` does not show the desired label:

```
Name:               my-test-cluster-worker-#########
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=cpx41
                    beta.kubernetes.io/os=linux
                    csi.hetzner.cloud/location=nbg1
                    failure-domain.beta.kubernetes.io/region=nbg1
                    failure-domain.beta.kubernetes.io/zone=nbg1-dc3
                    instance.hetzner.cloud/provided-by=cloud
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=my-test-cluster-worker-#######
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=cpx41
                    topology.kubernetes.io/region=nbg1
                    topology.kubernetes.io/zone=nbg1-dc3
```

Am I doing something wrong?

**Comment by jampy** [comment]
Closing because I just found out that [Autoscaling nodes unfortunately do not support labels](https://github.com/vitobotta/hetzner-k3s/issues/187#issuecomment-1483938776)

**Comment by vitobotta** [comment]
It's on my list IIRC because labels and taints should now be supported. I am reopening so I can notify you here when it's done. I need to do this quite soon because we need it at work as well.

**Comment by ServerSideHannes** [comment]
@vitobotta Do you have an update on this issue?

**Comment by vitobotta** [comment]
Support for labels and taints has been added in v2.2.8, which I just released. Closing this now.

**Comment by jampy** [comment]
I tried to configure a autoscaled node pool with labels in v2.2.9 like so:

```
masters_pool:
  instance_type: cpx21
  instance_count: 3
  locations:
    - nbg1

worker_node_pools:
  - name: worker
    instance_type: cpx41
    instance_count: 3
    location: nbg1
    labels:
      - key: node-role.kubernetes.io/worker
        value: "true"
    autoscaling:
      enabled: true
      min_instances: 2
      max_instances: 5
```

I see in the Hetzner Console that the instances are started but they do not appear to join the cluster:

```
$ kubectl get nodes
NAME                      STATUS   ROLES                       AGE   VERSION
generic-cluster-master1   Ready    control-plane,etcd,master   10m   v1.32.1+k3s1
generic-cluster-master2   Ready    control-plane,etcd,master   11m   v1.32.1+k3s1
generic-cluster-master3   Ready    control-plane,etcd,master   10m   v1.32.1+k3s1
```

Unfortunately I do not know how to debug this in more detail.

Deleting the cluster and running `hetzner-k3s` again without the `labels:` allows the cluster to come up without problems.
