### ISSUE TITLE
Unused placement groups deletion [BUG]

### ISSUE THREAD

**Issue by ricristian** [vitobotta/hetzner-k3s#530]
Hello, 

I'm not sure that this is intended behaviour but why the CLI started removing unused placement groups that were created by me manually or third party applications system ? 

```
[Configuration] Validating configuration...
[Configuration] ...configuration seems valid.
[Private Network] Creating private network...
[Private Network] ...private network created
[Placement groups] Deleting unused placement group cfke-xxx...
[Placement groups] ...placement group cfke-xxx..... deleted
[Placement groups] Deleting unused placement group production-pg...
[Placement groups] ...placement group production-pg deleted
[Placement groups] Creating placement group test-masters...
[Placement groups] ...placement group test-masters created
```

executed cmd: hetzner-k3s create --config test.yaml | tee create.log

test.yaml
```
---
hetzner_token: token
cluster_name: test
kubeconfig_path: "./kubeconfig"
k3s_version: v1.31.3+k3s1

networking:
  ssh:
    port: 22
    use_agent: false
    public_key_path: "~/.ssh/id_ed25519.pub"
    private_key_path: "~/.ssh/id_ed25519"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api: # this will firewall port 6443 on the nodes
      - 0.0.0.0/0
  public_network:
    ipv4: true
    ipv6: true
  private_network:
    enabled: true
    subnet: 10.0.0.0/16
    existing_network_name: ""
  cni:
    enabled: true
    encryption: false
    mode: flannel

datastore:
  mode: etcd # etcd (default) or external

schedule_workloads_on_masters: false

masters_pool:
  instance_type: cx22
  instance_count: 3
  locations:
    - fsn1
    - hel1
    - nbg1

worker_node_pools:
  - name: small
    instance_type: cx32
    instance_count: 2
    location: fsn1
    autoscaling:
      enabled: true
      min_instances: 0
      max_instances: 3

  - name: medium-autoscaled
    instance_type: cpx31
    instance_count: 2
    location: fsn1
    autoscaling:
      enabled: true
      min_instances: 0
      max_instances: 3

embedded_registry_mirror:
  enabled: false # Check if your k3s version is compatible before enabling this option. You can find more information at https://docs.k3s.io/installation/registry-mirror

protect_against_deletion: true

create_load_balancer_for_the_kubernetes_api: false # NOTE: it is currently not possible to restrict access to the load balancer by IP in the firewall since this hasn't been implemented by Hetzner yet.

#
#additional_packages:
#  - unattended-upgrades
#  - update-notifier-common
#
#post_create_commands:
#  - sudo systemctl enable unattended-upgrades
#  - sudo systemctl start unattended-upgrades
```

Also another. really weird bug as you can see in my configuration I've configured 2 worker node pools but I would expect to have 4 nodes deployed  but for my surprise only 1 server was created test-medium-autoscaled-e0844a8cdxxxx was created
