### ISSUE TITLE
Macos delete cluster weird behaviour

### ISSUE THREAD

**Issue by ricristian** [vitobotta/hetzner-k3s#531]
I've created a k3s cluster for testing purposes and I wanted to delete it but:

test.yaml

```
---
hetzner_token: token
cluster_name: test
kubeconfig_path: "./kubeconfig"
k3s_version: v1.31.3+k3s1

networking:
  ssh:
    port: 22
    use_agent: false
    public_key_path: "~/.ssh/id_ed25519.pub"
    private_key_path: "~/.ssh/id_ed25519"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api: # this will firewall port 6443 on the nodes
      - 0.0.0.0/0
  public_network:
    ipv4: true
    ipv6: true
  private_network:
    enabled: true
    subnet: 10.0.0.0/16
    existing_network_name: ""
  cni:
    enabled: true
    encryption: false
    mode: flannel

datastore:
  mode: etcd # etcd (default) or external

schedule_workloads_on_masters: false

masters_pool:
  instance_type: cx22
  instance_count: 3
  locations:
    - fsn1
    - hel1
    - nbg1

worker_node_pools:
  - name: small
    instance_type: cx32
    instance_count: 2
    location: fsn1
    autoscaling:
      enabled: true
      min_instances: 0
      max_instances: 3

  - name: medium-autoscaled
    instance_type: cpx31
    instance_count: 2
    location: fsn1
    autoscaling:
      enabled: true
      min_instances: 0
      max_instances: 3

embedded_registry_mirror:
  enabled: false # Check if your k3s version is compatible before enabling this option. You can find more information at https://docs.k3s.io/installation/registry-mirror

protect_against_deletion: true

create_load_balancer_for_the_kubernetes_api: false # NOTE: it is currently not possible to restrict access to the load balancer by IP in the firewall since this hasn't been implemented by Hetzner yet.

#
#additional_packages:
#  - unattended-upgrades
#  - update-notifier-common
#
#post_create_commands:
#  - sudo systemctl enable unattended-upgrades
#  - sudo systemctl start unattended-upgrades
```

hetzner-k3s delete --config test.yaml | tee delete.log

<img width="488" alt="Image" src="https://github.com/user-attachments/assets/aa9ecf1c-d487-4e37-acba-e262b5ce48ee" />

If I press enter key:

<img width="547" alt="Image" src="https://github.com/user-attachments/assets/26045f36-5e9e-4b8e-a00b-ab23905be595" />

Shouldn't I get a message like "Please type your cluster name before deletion?" 

https://github.com/vitobotta/hetzner-k3s/blob/main/docs/Deleting_a_cluster.md -> I'm not sure if this confirmation must be mentioned here also ? 

Hardware:
MacBook Pro M1 PRO - Sequoia 15.1
