### ISSUE TITLE
[Private Network] Failed to create private network

### ISSUE THREAD

**Issue by mcampa** [vitobotta/hetzner-k3s#532]
When creating a cluster for locations in `ash` or `hil` I get this error

```
[Configuration] Validating configuration...
[Configuration] ...configuration seems valid.
[Private Network] Creating private network...
[Private Network] Failed to create private network: {
    "error": {
        "code": "invalid_input",
        "message": "invalid input in field 'subnets[0].network_zone'",
        "details": {
            "fields": [
                {
                    "messages": [
                        "network zone does not exist"
                    ],
                    "name": "subnets[0].network_zone"
                }
            ]
        }
    }
}
```

This is my `hetzner-k3s_cluster_config.yaml` file:
```yaml
hetzner_token: [redacted]
cluster_name: unopago-cluster
kubeconfig_path: "./kubeconfig"  # or /cluster/kubeconfig if you are going to use Docker
k3s_version: v1.32.0+k3s1

networking:
  ssh:
    port: 22
    use_agent: false
    public_key_path: "~/.ssh/id_rsa.pub"
    private_key_path: "~/.ssh/id_rsa"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api:
      - 0.0.0.0/0

masters_pool:
  instance_type: cpx11
  instance_count: 1
  locations:
    - ash

worker_node_pools:
- name: small
  instance_type: cpx21
  instance_count: 3
  location: ash
- name: big
  instance_type: cpx31
  location: ash
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 2
```

But it works if I change locations to `fsn1`

I did a little digging and I think the issue is in this method https://github.com/vitobotta/hetzner-k3s/blob/3be93ca9cdd166d38f0d9a2ca897e4758768f1bd/src/configuration/settings/node_pool/location.cr#L14
I think that it should return  `us-east` for `ash` and `us-west` for `hil`
