### ISSUE TITLE
Location validation bug

### ISSUE THREAD

**Issue by mcampa** [vitobotta/hetzner-k3s#537]
There seems to be another bug with location validation

I'm getting this error with 2.2.6 but not with 2.2.2

```
 _          _                            _    _____
| |__   ___| |_ _____ __   ___ _ __     | | _|___ / ___
| '_ \ / _ \ __|_  / '_ \ / _ \ '__|____| |/ / |_ \/ __|
| | | |  __/ |_ / /| | | |  __/ | |_____|   < ___) \__ \
|_| |_|\___|\__/___|_| |_|\___|_|       |_|\_\____/|___/

Version: 2.2.6

[Configuration] Validating configuration...
[Configuration] Some information in the configuration file requires your attention:
[Configuration]  - All workers must be in valid locations and in the same same network zone as the masters when using a private network. If the masters are located in Ashburn, then all the worker must be located in Ashburn too. Same thing for Hillsboro and Singapore. If the masters are located in Germany and/or Finland, then also the workers must all be located in either Germany or Finland since these locations belong to the same network zone.
```

Here is my `cluster_config.yaml`:
```yaml
cluster_name: my-cluster
kubeconfig_path: "./kubeconfig"
k3s_version: v1.32.1+k3s1

networking:
  public_network:
    ipv4: false
    ipv6: false
  ssh:
    port: 22
    use_agent: false
    public_key_path: "~/.ssh/id_rsa.pub"
    private_key_path: "~/.ssh/id_rsa"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api:
      - 0.0.0.0/0

masters_pool:
  instance_type: cpx11
  instance_count: 1
  location: ash

worker_node_pools:
- name: small
  instance_type: cpx21
  instance_count: 6
  location: ash
- name: big
  instance_type: cpx31
  location: ash
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 3

```

**Comment by vitobotta** [comment]
Hi,

Please check the upgrade instructions for [v2.2.3](https://github.com/vitobotta/hetzner-k3s/releases/tag/v2.2.3) if you upgraded directly from v2.2.2 to v2.2.6. The `location` setting in the `masters_pool` has been deprecated and replaced with an array called `locations`. This change was made to support regional clusters, where each master can be in a different location for better availability.

If you have an existing cluster that was created with a version before v2.2.3, and it only has one master, then it's currently a zonal cluster with just one location. In this case, update your configuration as follows:

```yaml
masters_pool:
  instance_type: cpx11
  instance_count: 1
  locations: 
    - ash
```

This should resolve the issue.
