### ISSUE TITLE
incorrect validation error about API allowed networks

### ISSUE THREAD

**Issue by jampy** [vitobotta/hetzner-k3s#542]
Had a working v2.2.3 cluster and tried today to recreate it using v2.2.6

Using the same `cluster_config.yaml` it claims that my current IP is not in the list of allowed networks:

```
 _          _                            _    _____
| |__   ___| |_ _____ __   ___ _ __     | | _|___ / ___
| '_ \ / _ \ __|_  / '_ \ / _ \ '__|____| |/ / |_ \/ __|
| | | |  __/ |_ / /| | | |  __/ | |_____|   < ___) \__ \
|_| |_|\___|\__/___|_| |_|\___|_|       |_|\_\____/|___/

Version: 2.2.6

[Configuration] Validating configuration...
[Configuration] Some information in the configuration file requires your attention:
[Configuration]  - Your current IP 139.131.253.160 must belong to at least one of the API allowed networks
```

(I randomized the IP address in this issue text)

The relevant parts in the config:

```yaml
networking:
  ssh:
    port: 22
    use_agent: false
  allowed_networks:
    ssh:
      - 139.131.253.160/32
    api:
      - 139.131.253.160/32
      - 10.77.0.0/16
  public_network:
    ipv4: true
    ipv6: true
  private_network:
    enabled : true
    subnet: 10.77.0.0/16
    existing_network_name: "my-fancy-network-name"
```

So my "public IP" is actually in the list of allowed networks and I do not have any networking issues with v2.2.3
