### ISSUE TITLE
Unable to determine your current IP (necessary to validate allowed networks for SSH and API)

### ISSUE THREAD

**Issue by possonom** [vitobotta/hetzner-k3s#563]
I am working on the jump host in a project on Hetzner and trying to create a cluster, but I keep getting this error:
```
Version: 2.2.7

[Configuration] Validating configuration...
[Configuration] Some information in the configuration file requires your attention:
[Configuration]  - Unable to determine your current IP (necessary to validate allowed networks for SSH and API)
```
Here is my configuration content.

```
cluster_name: thp-k3s
kubeconfig_path: "./kubeconfig"  # or /cluster/kubeconfig if you are going to use Docker
k3s_version: v1.32.0+k3s1

networking:
  ssh:
    port: 22
    use_agent: false
    public_key_path: "~/.ssh/id_rsa.pub"
    private_key_path: "~/.ssh/id_rsa"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api:
      - 0.0.0.0/0 
  public_network:
    ipv4: false
    ipv6: false
  private_network:
    enabled: true
    subnet: 10.0.128.0/24 
schedule_workloads_on_masters: false
masters_pool:
  instance_type: cax11
  instance_count: 3
  locations:
    - fsn1
    - hel1
    - nbg1 
worker_node_pools:
- name: worker-small-arm
  instance_type: cax11
  instance_count: 2
  location: fsn1
  labels:
    - key: role
      value: worker
    - key: arch
      value: arm64
  taints:
    - key: role
      value: worker
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 1
- name: worker-small
  instance_type: cx22
  instance_count: 2
  location: fsn1
  labels:
    - key: role
      value: worker
    - key: arch
      value: amd64
  taints:
    - key: role
      value: worker
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 1
- name: storage
  instance_type: cax21
  instance_count: 2
  location: fsn1
  labels:
    - key: role
      value: database
    - key: arch
      value: arm64
  taints:
    - key: role
      value: database:NoSchedule 
- name: messaging
  instance_type: cax21
  instance_count: 2
  location: fsn1 
  labels:
    - key: role
      value: messaging
    - key: arch
      value: arm64
  taints:
    - key: role
      value: messaging:NoSchedule 

embedded_registry_mirror:
  enabled: true

create_load_balancer_for_the_kubernetes_api: false
post_create_commands:
- apt update
- apt upgrade -y
- apt install ifupdown resolvconf -y
- apt autoremove -y hc-utils
- apt purge -y hc-utils
- echo "auto enp7s0" > /etc/network/interfaces.d/60-private
- echo "iface enp7s0 inet dhcp" >> /etc/network/interfaces.d/60-private
- echo "    post-up ip route add default via 10.0.0.2"  >> /etc/network/interfaces.d/60-private
- echo "[Resolve]" > /etc/systemd/resolved.conf
- echo "DNS=1.1.1.1 1.0.0.2" >> /etc/systemd/resolved.conf
- ifdown enp7s0
- ifup enp7s0
- systemctl start resolvconf
- systemctl enable resolvconf
- echo "nameserver 1.1.1.1" >> /etc/resolvconf/resolv.conf.d/head
- echo "nameserver 1.0.0.2" >> /etc/resolvconf/resolv.conf.d/head
- resolvconf --enable-updates
- resolvconf -u
```
