### ISSUE TITLE
Flag to disable usage of cluster-autoscaler

### ISSUE THREAD

**Issue by cwilhelm** [vitobotta/hetzner-k3s#580]
I understand that many users need the autoscaling feature. But I do not need it and therefor would like to completely disable the usage of cluster-autoscaler.

**Comment by vitobotta** [comment]
Just don't define any autoscaled pools, and the autoscaling will be effectively disabled. Have you tried that?

**Comment by cwilhelm** [comment]
This is my config. I think I do not have autoscaled pools.

```
cluster_name: control
kubeconfig_path: "./kubeconfig"  # or /cluster/kubeconfig if you are going to run k3s in Docker
k3s_version: v1.31.7+k3s1
include_instance_type_in_instance_name: true
create_load_balancer_for_the_kubernetes_api: true
k3s_upgrade_concurrency: 1

networking:
  allowed_networks:
    api:
      - 0.0.0.0/0
    ssh:
      - 0.0.0.0/0
  cni:
    enabled: true
    encryption: true
    mode: flannel
  private_network:
    enabled: true
    subnet: 10.0.0.0/16
  public_network:
    ipv4: true
    ipv6: false
  ssh:
    port: 22
    public_key_path: ~/.ssh/id_ed25519.pub
    private_key_path: ~/.ssh/id_ed25519
    use_agent: false

datastore:
  mode: etcd

schedule_workloads_on_masters: true
verify_host_key: false

manifests:
  cloud_controller_manager_manifest_url: https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.24.0/ccm-networks.yaml
  # csi_driver_manifest_url: https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.7.1/deploy/kubernetes/hcloud-csi.yml
  # system_upgrade_controller_deployment_manifest_url: https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/system-upgrade-controller.yaml
  # system_upgrade_controller_crd_manifest_url: https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/crd.yaml
  #   cluster_autoscaler_manifest_url: "https://raw.githubusercontent.com/kubernetes/autoscaler/master/cluster-autoscaler/cloudprovider/hetzner/examples/cluster-autoscaler-run-on-master.yaml"
  # cluster_autoscaler_container_image_tag: "v1.32.0"


masters_pool:
  locations:
    - fsn1
  instance_type: cx42
  instance_count: 1

worker_node_pools: []

embedded_registry_mirror:
  enabled: true

additional_packages:
- aptitude
- unattended-upgrades
- update-notifier-common
post_create_commands:
- apt update
- apt upgrade -y
- apt autoremove -y
- sudo systemctl enable unattended-upgrades
- sudo systemctl start unattended-upgrades
- shutdown -r now
```
