### ISSUE TITLE
`Nil assertion failed` and create command is stuck

### ISSUE THREAD

**Issue by neferin12** [vitobotta/hetzner-k3s#587]
When running the create command to update my cluster I get the following error for both nodes:

```
[Instance kubernetes-cx32-pool-nbg-cx32-worker1] Cloud init finished: 73.10 - Fri, 02 May 2025 19:16:20 +0000 - v. 24.4.1-0ubuntu0~24.04.2
Unhandled exception in spawn: Nil assertion failed (NilAssertionError)
  from hetzner-k3s in 'Exception::CallStack::unwind:Array(Pointer(Void))'
  from hetzner-k3s in 'Exception::CallStack#initialize:Array(Pointer(Void))'
  from hetzner-k3s in 'Exception::CallStack::new:Exception::CallStack'
  from hetzner-k3s in 'raise<NilAssertionError>:NoReturn'
  from hetzner-k3s in '??'
  from hetzner-k3s in '??'
  from hetzner-k3s in 'Kubernetes::Installer::labels_and_tains<Configuration::Main, (Configuration::WorkerNodePool | Nil)>:String'
  from hetzner-k3s in 'Kubernetes::Installer::worker_install_script<Configuration::Main, Array(Hetzner::Instance), Hetzner::Instance, (Configuration::WorkerNodePool | Nil)>:String'
  from hetzner-k3s in 'Kubernetes::Installer#deploy_k3s_to_worker<(Configuration::WorkerNodePool | Nil), Hetzner::Instance>:Nil'
  from hetzner-k3s in '~procProc(Nil)'
  from hetzner-k3s in 'Fiber#run:Nil'
  from hetzner-k3s in '~proc2Proc(Fiber, Nil)'
  from ???
```

After that the tool does nothing.

This is my config:
```
hetzner_token: xxx
cluster_name: kubernetes
kubeconfig_path: "~/.kube/config"
k3s_version: v1.29.3+k3s1
include_instance_type_in_instance_name: true
networking:
  ssh:
    public_key_path: "~/.ssh/id_rsa.pub"
    private_key_path: "~/.ssh/id_rsa"
    use_agent: false
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api:
      - 0.0.0.0/0
  private_network:
    enabled: true
    subnet: 10.0.0.0/16
schedule_workloads_on_masters: false
masters_pool:
  name: nbg-cx11
  instance_type: cx22
  location: nbg1
  instance_count: 1
  legacy_instance_type: cx11
worker_node_pools:
- name: nbg-cx32
  instance_type: cx32
  location: nbg1
  instance_count: 2
  legacy_instance_type: cx32
additional_packages:
- nfs-common
post_create_commands:
- apt update
- apt upgrade -y
- apt autoremove -y
- sudo systemctl enable unattended-upgrades
- sudo systemctl start unattended-upgrades
```

If that is relevant: I needed to delete a node because it missbehaved. Then I tried to run the create command to add it again.
