### ISSUE TITLE
SSH configuration on Rocky 9 hosts fails

### ISSUE THREAD

**Issue by 0ranki** [vitobotta/hetzner-k3s#593]
I was wondering why I can't access created nodes over SSH, and it looks like hetzner-k3s sets the following to /etc/sshd_config:

```
...
# If you want to change the port on a SELinux system, you have to tell
# SELinux about this change.
# semanage port -a -t ssh_port_t -p tcp #PORTNUMBER
#
Port {{ ssh_port }}            ### <---
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
...
```

This seems to cause SSHD to listen only on IPv6.

Hetzner-k3s version: 2.3.0
Host OS: Rocky-9 / ARM

**Comment by vitobotta** [comment]
I can't reproduce and it has never been reported. SSH connections work fine with IPv4. Check your setup properly and if the problem persists share your config file and share more details so I can take a look.

**Comment by 0ranki** [comment]
Wow, fast response!

I have created about a dozen clusters in the past 24h, and the issue has appeared quite consistently.

Hetzner-k3s is installed via binary from GH on Linux AMD64.

I'm running OpenSuse TW, but need to execute the binary in a Ubuntu 22.04 distrobox. (Might be related, I'm facing [#309](https://github.com/vitobotta/hetzner-k3s/issues/309) if executing on the host)

Here's the config:
```
hetzner_token: x
cluster_name: k3s-testing
kubeconfig_path: "./kubeconfig"
k3s_version: v1.33.0+k3s1

networking:
  ssh:
    port: 22
    use_agent: false
    public_key_path: "~/.ssh/id_ed25519.pub"
    private_key_path: "~/.ssh/id_ed25519"
  allowed_networks:
    ssh:
      - <ipv4 address>/32
    api:
      - <ipv4 address>/32
  cni:
    enabled: true
    encryption: true
    mode: cilium

local_path_storage_class:
  enabled: true

protect_against_deletion: true
image: rocky-9

schedule_workloads_on_masters: false
masters_pool:
  instance_type: cax11
  instance_count: 1
  locations:
    - hel1

worker_node_pools:
- name: small
  instance_type: cpx21
  instance_count: 1
  location: hel1

additional_packages:
  - cryptsetup
```

The only special things are using Cilium and deploying only 1 master node that I can think of.

The issue was present also without adding the cryptsetup package.
