### ISSUE TITLE
hetzner-k3s v2.3.0 - Create Error

### ISSUE THREAD

**Issue by rmelilloii** [vitobotta/hetzner-k3s#594]
Gents o/ Happy almost Friday!

   Sorry to bother again, I was for a bit using TF and I saw the release notes here and decided to give it a go, as I do love the performance and simplicity provided by this tool :)

   So, this is something that used to work, and I am not sure on which version it was lost.

What: 
A: It was possible to use individual "post_create_commands" per "type of pool".
 - Master 
 - Worker

B: It was possible to request a restart to apply the updates before we start using the cluster. Now it restarts the node before the k3s installation is complete, which breaks the creation process.

Not a big deal, not sure if someone else noticed or need this feature, please feel free to close the discussion in case it is not an issue and also, please let me know in case I am doing something wrong

Example of what I apply to "master nodes", it is specific to master for the audit bit
```
  post_create_commands:
  - echo fs.inotify.max_user_watches=1048576|tee -a /etc/sysctl.conf
  - echo fs.inotify.max_user_instances=1024|tee -a /etc/sysctl.conf
  - echo Ciphers aes256-ctr,aes192-ctr,aes128-ctr|tee -a /etc/ssh/sshd_config
  - echo MACs hmac-sha2-256,hmac-sha2-512|tee -a /etc/ssh/sshd_config
  - mkdir -p -m 700 /var/lib/rancher/k3s/server/logs
  - touch /var/lib/rancher/k3s/server/logs/audit.log
  - touch /var/lib/rancher/k3s/server/audit.yaml
  - touch /var/lib/rancher/k3s/server/downloadAudit.sh
  - echo '#!/bin/bash' >> /var/lib/rancher/k3s/server/downloadAudit.sh
  - echo 'curl -s -o /var/lib/rancher/k3s/server/audit.yaml https://***/k3s/main/audit.yaml' >> /var/lib/rancher/k3s/server/downloadAudit.sh
  - chmod +x /var/lib/rancher/k3s/server/downloadAudit.sh
  - touch /etc/systemd/system/downloadAudit.service
  - echo '[Unit]' >> /etc/systemd/system/downloadAudit.service
  - echo 'Description=Download audit config' >> /etc/systemd/system/downloadAudit.service
  - echo '[Service]' >> /etc/systemd/system/downloadAudit.service
  - echo 'ExecStart=/var/lib/rancher/k3s/server/downloadAudit.sh' >> /etc/systemd/system/downloadAudit.service
  - echo '[Install]' >> /etc/systemd/system/downloadAudit.service
  - echo 'WantedBy=multi-user.target' >> /etc/systemd/system/downloadAudit.service
  - systemctl daemon-reload
  #- systemctl enable downloadAudit.service
  - systemctl start downloadAudit.service
  - apt update
  - apt upgrade -y
  - apt autoremove -y
  - shutdown -r now
```

---
example of a working yaml for v2.3.0
```
cat hetzner-cluster-config.yaml
hetzner_token: ***
cluster_name: rome
kubeconfig_path: "./kubeconfig"  # or /cluster/kubeconfig if you are going to use Docker
k3s_version: v1.32.4+k3s1
schedule_workloads_on_masters: true
protect_against_deletion: false

networking:
  ssh:
    public_key_path: "/Users/rmii/.ssh/rancher-staging/id_rsa.pub"
    private_key_path: "/Users/rmii/.ssh/rancher-staging/id_rsa"

masters_pool:
  instance_type: cpx21
  instance_count: 1
  locations:
    - nbg1
  image: ubuntu-24.04

worker_node_pools:
- name: generic-01
  instance_type: cpx11
  instance_count: 1
  location: nbg1
  image: ubuntu-24.04

post_create_commands:
- apt update
- apt upgrade -y   
- apt autoremove -y
```

Thanks!

**Comment by vitobotta** [comment]
Hi, you can still set different post-create commands for the masters pool and each node pool separately. Check out the code here: https://github.com/vitobotta/hetzner-k3s/blob/17dc377ccdec4aebe408557250201da839014210/src/cluster/create.cr#L122 and here: https://github.com/vitobotta/hetzner-k3s/blob/17dc377ccdec4aebe408557250201da839014210/src/cluster/create.cr#L162.

You just need to set the `post_create_commands` property on the pools instead of at the top level. We only use the top-level setting when it's not specified in the node pool. What specific issue are you facing with this?

Rebooting the instance is a bit tricky because it needs to happen at the right time between mandatory commands to prepare the node and the k3s setup. It gets even more complex with autoscaled nodes since the whole setup happens through Cloud Init. For this reason, I recommend using [Kured](https://kured.dev) to handle OS updates. It's a DaemonSet that detects when OS updates are available for a node. During a maintenance window you specify, it drains the node, updates it, reboots it, and then uncordons it so it's ready to run pods again. It does this with one node per time while respecting the maintenance window. This solution not only updates nodes when they're created but keeps them updated continuously. We use this for our clusters, and it works really well.

**Comment by rmelilloii** [comment]
Vito!

Thanks for that, I did a test per pool, it never finishes the deploy. The
wed to work well before.
But no worries, I’ll look at the code, do a bit more test, and if it
doesn’t work I’ll let you know ( maybe it is a bug indeed).
In anyway, I will just have scrip to do all the OS changes I need and will
follow your suggestion and use kured, I had no idea you could use it at
deploy.

Thanks again 🙇🏻

Romulo

**Comment by vitobotta** [comment]
Did you still have the reboot command in the list? If yes, that's the issue. I recommend you avoid restarting the nodes during the setup.

**Comment by rmelilloii** [comment]
No no, without reboot.

Romulo

**Comment by vitobotta** [comment]
I just tried it again by setting a different post create command for each pool. Each node pool writes a file with different content, and it worked perfectly. I couldn't reproduce the problem. Could you share your config file with the post create commands set separately for each node pool?

**Comment by rmelilloii** [comment]
Amazing!

Can you share yours?

But, on another note, I’ve just opened a ticket with hetzner, they are
having issues in us-east. I suppose it could be related too. So I’ve let
more tests for tomorrow.*will paste my config then.

Mine was a simple “touch command” to create a txt so I could track which
block was used where. Didn’t work, but the apt update did.

Thanks!
Romulo

**Comment by vitobotta** [comment]
This is what I used

```yaml
masters_pool:
  instance_type: cpx41
  instance_count: 3
  locations:
    - fsn1
    - hel1
    - nbg1
  post_create_commands:
  - echo master > /tmp/instance-type

schedule_workloads_on_masters: false

embedded_registry_mirror:
  enabled: true

local_path_storage_class:
  enabled: true

create_load_balancer_for_the_kubernetes_api: false

worker_node_pools:
- name: database-fsn
  instance_type: cpx41
  instance_count: 2
  location: fsn1
  post_create_commands:
  - echo worker > /tmp/instance-type
```

The /tmp/instance-type file was created with the correct value on each node.

**Comment by rmelilloii** [comment]
Thanks! (Now, it is a Happy Friday!)

   I took my time doing all the different validations and trying to use as many parameters as might be needed.

My issues:
- this is the main issue actually, Hetzner health: API and or SKU availability (unlucky, really, not the first time I get a similar behaviour)
- reboot (but this was clear after the initial test) - now working, I suppose any amount of minutes that is >=6 will do, if it is <5 it fails as I suppose the OS stops the tasks and prepares for shutdown.
- kube_api_server_args: apparently it now needs to be under the pool and aligned with "post_create_commands" 

I've also tried: 
 - "master" location, informing a single location or multiple, all work.
 - 5 variations of k3s version up to v1.32.4+k3s1, all work.

   I will spend time reading the code to make sure I know all parameters that can be used to have a "full template" with validated indentation and "block position". But, as with most things, it will have to be another time.

Thank you very much again and I hope this case can be helpful for other users too.

### **Working example**

```yaml
hetzner_token: ***
cluster_name: kld-demo
kubeconfig_path: "./kubeconfig"
k3s_version: v1.25.9+k3s1

schedule_workloads_on_masters: true
protect_against_deletion: false
create_load_balancer_for_the_kubernetes_api: false
k3s_upgrade_concurrency: 1

local_path_storage_class:
  enabled: true

embedded_registry_mirror:
  enabled: false

networking:
  ssh:
    port: 22
    use_agent: false
    public_key_path: "/***/id_rsa.pub"
    private_key_path: "/***/id_rsa"
  allowed_networks:
    ssh:
      - ***/32
    api:
      - ***/32
  public_network:
    ipv4: true
    ipv6: false
  private_network:
    enabled: true
    subnet: 10.0.0.0/16
  cni:
    enabled: true
    encryption: true
    mode: flannel

datastore:
  mode: etcd

masters_pool:
  instance_type: cpx51
  instance_count: 3
  locations:
    - ash
  image: ubuntu-24.04
  post_create_commands:
  - echo fs.inotify.max_user_watches=1048576|tee -a /etc/sysctl.conf
  - echo fs.inotify.max_user_instances=1024|tee -a /etc/sysctl.conf
  - echo Ciphers aes256-ctr,aes192-ctr,aes128-ctr|tee -a /etc/ssh/sshd_config
  - echo MACs hmac-sha2-256,hmac-sha2-512|tee -a /etc/ssh/sshd_config
  - mkdir -p -m 700 /var/lib/rancher/k3s/server/logs
  - touch /var/lib/rancher/k3s/server/logs/audit.log
  - touch /var/lib/rancher/k3s/server/audit.yaml
  - touch /var/lib/rancher/k3s/server/downloadAudit.sh
  - echo '#!/bin/bash' >> /var/lib/rancher/k3s/server/downloadAudit.sh
  - echo 'curl -s -o /var/lib/rancher/k3s/server/audit.yaml https:***' >> /var/lib/rancher/k3s/server/downloadAudit.sh
  - chmod +x /var/lib/rancher/k3s/server/downloadAudit.sh
  - touch /etc/systemd/system/downloadAudit.service
  - echo '[Unit]' >> /etc/systemd/system/downloadAudit.service
  - echo 'Description=Download audit config' >> /etc/systemd/system/downloadAudit.service
  - echo '[Service]' >> /etc/systemd/system/downloadAudit.service
  - echo 'ExecStart=/var/lib/rancher/k3s/server/downloadAudit.sh' >> /etc/systemd/system/downloadAudit.service
  - echo '[Install]' >> /etc/systemd/system/downloadAudit.service
  - echo 'WantedBy=multi-user.target' >> /etc/systemd/system/downloadAudit.service
  - systemctl daemon-reload
  - systemctl start downloadAudit.service
  - apt update
  - apt upgrade -y
  - apt autoremove -y
  - echo master > /tmp/instance-type
  - shutdown -r +10
  kube_api_server_args:
  - audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log
  - audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml
  - audit-log-maxage=30
  - audit-log-maxbackup=11
  - audit-log-maxsize=100

worker_node_pools:
- name: generic-01
  instance_type: ccx53
  instance_count: 1
  location: ash
  image: ubuntu-24.04
  post_create_commands:
  - echo fs.inotify.max_user_watches=1048576|tee -a /etc/sysctl.conf
  - echo fs.inotify.max_user_instances=1024|tee -a /etc/sysctl.conf
  - echo Ciphers aes256-ctr,aes192-ctr,aes128-ctr|tee -a /etc/ssh/sshd_config
  - echo MACs hmac-sha2-256,hmac-sha2-512|tee -a /etc/ssh/sshd_config
  - curl -s -o /etc/apt/apt.conf.d/51unattended-upgrades https://***
  - sudo systemctl enable unattended-upgrades
  - sudo systemctl start unattended-upgrades
  - apt update
  - apt upgrade -y   
  - apt autoremove -y
  - shutdown -r +10
  - echo worker > /tmp/instance-type
```
