### ISSUE TITLE
Bootstrap issue when disabling ipv4

### ISSUE THREAD

**Issue by mrdotb** [vitobotta/hetzner-k3s#605]
Hi, the guide suggest that is possible to disable ipv4 to save a bit on cost.
The bootstrap without ipv4 is hanging forever after those logs
```
[Configuration] Validating configuration...
[Configuration] ...configuration seems valid.
[Private Network] Creating private network...
[Private Network] ...private network created
[SSH key] Creating SSH key...
[SSH key] ...SSH key created
[Placement groups] Creating placement group stormwind-masters...
[Placement groups] ...placement group stormwind-masters created
[Placement groups] Creating placement group stormwind-small-static-1...
[Placement groups] ...placement group stormwind-small-static-1 created
[Instance stormwind-master1] Creating instance stormwind-master1 (attempt 1)...
[Instance stormwind-master2] Creating instance stormwind-master2 (attempt 1)...
[Instance stormwind-master3] Creating instance stormwind-master3 (attempt 1)...
[Instance stormwind-master2] Instance status: off
[Instance stormwind-master2] Powering on instance (attempt 1)
[Instance stormwind-master2] Waiting for instance to be powered on...
[Instance stormwind-master1] Instance status: off
[Instance stormwind-master1] Powering on instance (attempt 1)
[Instance stormwind-master1] Waiting for instance to be powered on...
[Instance stormwind-master3] Instance status: off
[Instance stormwind-master3] Powering on instance (attempt 1)
[Instance stormwind-master3] Waiting for instance to be powered on...
[Instance stormwind-master2] Instance status: running
[Instance stormwind-master1] Instance status: running
[Instance stormwind-master3] Instance status: running
```

I copied the config from the documentation and just changed the ssh and set `public_network.ipv4` to false
```yaml
networking:
  ssh:
    port: 22
    use_agent: false # set to true if your key has a passphrase
    public_key_path: "~/.ssh/id_rsa.pub"
    private_key_path: "~/.ssh/id_rsa"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api: # this will firewall port 6443 on the nodes
      - 0.0.0.0/0
  public_network:
    ipv4: false # issue
    ipv6: true
  private_network:
    enabled: true
    subnet: 10.0.0.0/16
    existing_network_name: ""
  cni:
    enabled: true
    encryption: false
    mode: flannel

```
Running the same with ipv4 boostrap successfull.
