### ISSUE TITLE
Nodes with custom node-role.kubernetes.io/* do not join cluster

### ISSUE THREAD

**Issue by arfath-linklet** [vitobotta/hetzner-k3s#609]
Issue: Using a Well-Known label for custom role (node-role.kubernetes.io/*) prevents it from being added to cluster

```
- name: postgres
    instance_type: cx32
    instance_count: 3
    location: nbg1
    labels:
      - key: node-role.kubernetes.io/cnpg
        value: "true"
    taints:
      - key: node-role.kubernetes.io/cnpg
        value: true:NoSchedule
```

Workaround:

```
- name: postgres
    instance_type: cx32
    instance_count: 3
    location: nbg1
    labels:
      - key: node-role/cnpg
        value: "true"
    taints:
      - key: node-role/cnpg
        value: true:NoSchedule
```
