### ISSUE TITLE
With docker version 0.5.2 load balancer of workers is not healthy (with v0.4.8 everything is ok).

### ISSUE THREAD

**Issue by TitanFighter** [vitobotta/hetzner-k3s#65]
Hi. That's me again :)

Finally Ive written all configs I need and wanted to install everything on fresh servers and decided to use 0.5.2, but found an issue that load balancer is not healthy. In 3+3 config API balancer always ok/green, but workers' health status changes like traffic light - the worst case I saw was all 3 red, the best - 1 green and 2 yellow. Status changes sometimes every 15 sec and sometimes every 30 sec.

I have installed 3 times 0.4.8 and 3 times 0.5.2 in order to be sure that this is not a co-incident. Before each installation I removed everything (servers, firewall rules, balancers, etc). Maybe you updated any dependencies, like Hetzner Cloud Controller Manager?

```
# k3s hetzner config
hetzner_token: TOKEN_HERE
cluster_name: us-east
kubeconfig_path: "/cluster/kubeconfig"
k3s_version: v1.23.3+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
ssh_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: ash
schedule_workloads_on_masters: false
masters:
  instance_type: cpx21
  instance_count: 3
worker_node_pools:
- name: cpx31
  instance_type: cpx31
  instance_count: 3
enable_ipsec_encryption: true
```

Nginx installation:
1. helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
2. helm repo update
3. helm upgrade --install \
4. ingress-nginx ingress-nginx/ingress-nginx \
-f ~/.kube/installation/ingress-controller-nginx-annotations.yaml \
--namespace ingress-nginx \
--create-namespace

```
# ingress-controller-nginx-annotations.yaml
controller:
  kind: DaemonSet
  service:
    annotations:
      load-balancer.hetzner.cloud/location: ash
      load-balancer.hetzner.cloud/name: us-east
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
      load-balancer.hetzner.cloud/hostname: "mysite.com"
      load-balancer.hetzner.cloud/http-redirect-https: "false"
```

These are the required steps to reproduce issue.

As a side effect I could not create Certification Issuer, because of the next error (with 0.4.8 everything is ok): 
> Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s: Service Unavailable
