### ISSUE TITLE
question: outbound ip of pods

### ISSUE THREAD

**Issue by marc0olo** [vitobotta/hetzner-k3s#67]
Hi,

I am really thankful for your contribution, helped me a lot to set up my cluster :-)

I am currently struggling to figure out which outbound ip my pods are using. If possible I'd like to have a static ip. I thought it would be the ip of the loadbalancer (ingress) - but it seems like it isn't.

Would appreciate your help!

Best regards
Marco

**Comment by vitobotta** [comment]
If you need a static IP outside the cluster then yes, the Load Balancer is what you need. How have you set up the deployment and the ingress?

**Comment by marc0olo** [comment]
interesting. so it should generally work already? what's the easiest way to check this if I don't have access to the firewall blocking the requests? would really like to see what outbound IP is being used.

for the ingress-controller I used following config:
```yaml
controller:
  kind: DaemonSet
  service:
    # LIST of all ANNOTATIONS: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/internal/annotation/load_balancer.go
    annotations:
      # Germany:
      # - nbg1 (Nuremberg)
      # - fsn1 (Falkensteing)
      # Finland:
      # - hel1 (Helsinki)
      # USA:
      # - ash (Ashburn, Virginia)
      load-balancer.hetzner.cloud/location: nbg1
      load-balancer.hetzner.cloud/name: ingress-nginx
      load-balancer.hetzner.cloud/use-private-ip: 'true'
      load-balancer.hetzner.cloud/uses-proxyprotocol: 'true'
      load-balancer.hetzner.cloud/hostname: my-hostname
      load-balancer.hetzner.cloud/http-redirect-https: 'false'
```

for the ingress of the service where I need a static IP I used following cfg:

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-service
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: my-hostname
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-service
            port:
              number: 80
  tls:
  - hosts:
    - my-hostname
    secretName: prod-certificate
```

for the deployment there is also nothing special

also I have set up hairpin-proxy due to problems with getting certificates via Let's Encrypt.
