### ISSUE TITLE
LoadBalancer fails to be created with v0.5.5

### ISSUE THREAD

**Issue by pysen** [vitobotta/hetzner-k3s#70]
Hi Vito,
There is an issue when I create a new cluster with the docker v0.5.5 image. Everything but the LoadBalancer object is created without issues.

```
/usr/local/bundle/gems/hetzner-k3s-0.5.5/lib/hetzner/k3s/cluster.rb:544:in `create_load_balancer': undefined local variable or method `location' for #<Cluster:XXXXXXXX_HUGE_OBJECT


Hetzner::LoadBalancer.new(hetzner_client:, cluster_name:).create(location:, network_id:)
                                                                     ^^^^^^^^^
	from /usr/local/bundle/gems/hetzner-k3s-0.5.5/lib/hetzner/k3s/cluster.rb:105:in `create_resources'
	from /usr/local/bundle/gems/hetzner-k3s-0.5.5/lib/hetzner/k3s/cluster.rb:49:in `create'
	from /usr/local/bundle/gems/hetzner-k3s-0.5.5/lib/hetzner/k3s/cli.rb:36:in `create_cluster'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/hetzner-k3s-0.5.5/exe/hetzner-k3s:4:in `<top (required)>'
	from /usr/local/bundle/bin/hetzner-k3s:25:in `load'
	from /usr/local/bundle/bin/hetzner-k3s:25:in `<main>'
```
The config used for this is:
```
---
cluster_name: CLUSTER_NAME
kubeconfig_path: "/cluster/kubeconfig"
k3s_version: v1.23.4+k3s1
public_ssh_key_path: "PUBLIC_SSH_KEY_PATH"
private_ssh_key_path: "PRIVATE_SSH_KEY_PATH"
ssh_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
schedule_workloads_on_masters: true
location: fsn1
masters:
  # Tried specifying the location here as well - still having same error with or without
  #location: fsn1
  instance_type: cpx41
  instance_count: 3
worker_node_pools: []
additional_packages: []
enable_encryption: true
```

**Comment by vitobotta** [comment]
Let me take a look. I must have missed something with the last update a few days ago.

**Comment by vitobotta** [comment]
Fixed in v0.5.6. Please try again and let me know.

**Comment by pysen** [comment]
@vitobotta A new error occured wit the same config:
```
/usr/local/bundle/gems/hetzner-k3s-0.5.6/lib/hetzner/infra/placement_group.rb:27:in `create': undefined method `[]' for nil:NilClass (NoMethodError)
      JSON.parse(response)['placement_group']['id']
                                             ^^^^^^
	from /usr/local/bundle/gems/hetzner-k3s-0.5.6/lib/hetzner/k3s/cluster.rb:462:in `placement_group_id'
	from /usr/local/bundle/gems/hetzner-k3s-0.5.6/lib/hetzner/k3s/cluster.rb:493:in `block in master_definitions_for_create'
	from /usr/local/bundle/gems/hetzner-k3s-0.5.6/lib/hetzner/k3s/cluster.rb:488:in `times'
	from /usr/local/bundle/gems/hetzner-k3s-0.5.6/lib/hetzner/k3s/cluster.rb:488:in `master_definitions_for_create'
	from /usr/local/bundle/gems/hetzner-k3s-0.5.6/lib/hetzner/k3s/cluster.rb:550:in `server_configs'
	from /usr/local/bundle/gems/hetzner-k3s-0.5.6/lib/hetzner/k3s/cluster.rb:562:in `create_servers'
	from /usr/local/bundle/gems/hetzner-k3s-0.5.6/lib/hetzner/k3s/cluster.rb:104:in `create_resources'
	from /usr/local/bundle/gems/hetzner-k3s-0.5.6/lib/hetzner/k3s/cluster.rb:49:in `create'
	from /usr/local/bundle/gems/hetzner-k3s-0.5.6/lib/hetzner/k3s/cli.rb:36:in `create_cluster'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/hetzner-k3s-0.5.6/exe/hetzner-k3s:4:in `<top (required)>'
	from /usr/local/bundle/bin/hetzner-k3s:25:in `load'
	from /usr/local/bundle/bin/hetzner-k3s:25:in `<main>'
Creating placement group CLUSTER_NAME...
...placement group CLUSTER_NAME created.
```

**Comment by vitobotta** [comment]
I cannot reproduce this issue. I have just created two clusters with your configuration without any issues.

Seems that the API call to create the placement group errored for some reason. Does it happen again if you re-run the create command?

What is the actual name of the cluster? - since it's used as name of the placement group for the masters. Maybe there is something wrong with the format of the name.

**Comment by pysen** [comment]
@vitobotta The issue was me using an old HCLOUD_TOKEN valid for the previous project. I made a new project forgot to update the runner variables. You can close this issue as the cluster creation now works as expected with valid api token set.

For anyone curious this is how I define it to be ran from gitlab-ci:

```
create-cluster:
  stage: create-cluster
  image:
    name: vitobotta/hetzner-k3s:v0.5.6
    entrypoint: ["/bin/sh", "-c"]
  variables:
    HCLOUD_TOKEN: $HCLOUD_TOKEN
    PUBLIC_SSH_KEY_PATH: $PUBLIC_SSH_KEY_PATH
    PRIVATE_SSH_KEY_PATH: $PRIVATE_SSH_KEY_PATH
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+\+k3s\d+/'
      when: manual
  script:
    - 'sed -i "s|PUBLIC_SSH_KEY_PATH|$PUBLIC_SSH_KEY_PATH|g" control_plane_config.yaml'
    - 'sed -i "s|PRIVATE_SSH_KEY_PATH|$PRIVATE_SSH_KEY_PATH|g" control_plane_config.yaml'
    - 'hetzner-k3s create-cluster --config-file cluster_config.yaml'
  artifacts:
    paths:
      - kubeconfig
    expire_in: 1 week
```
