### ISSUE TITLE
Getting HTTP 400 Bad Request when using Hetzner LB + Ingress nginx

### ISSUE THREAD

**Issue by xxavarlonxx** [vitobotta/hetzner-k3s#73]
Hi everyone,
i follow the Instructions on this Site by @TitanFighter. Everything seems to be working except all Request to the ingress controller get a HTTP 400 Bad request. I have no idea why.
That is my config.yaml 

```
hetzner_token: JvM6XjXH...
cluster_name: k3s-test
kubeconfig_path: "./kubeconfig"
k3s_version: v1.23.4+k3s1
public_ssh_key_path: "~/.ssh/ida_rsa_hetzner_k3s.pub"
private_ssh_key_path: "~/.ssh/ida_rsa_hetzner_k3s"
ssh_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: nbg1
schedule_workloads_on_masters: false
masters:
  instance_type: cx11
  image: debian
  instance_count: 1
worker_node_pools:
- name: extrasmall
  instance_type: cx11
  image: debian
  instance_count: 1
enable_encryption: true
```

After creating my cluster i installed ingress-nginx over helm directly with this commmand

helm upgrade --install \
ingress-nginx ingress-nginx/ingress-nginx \
-f ./ingress-nginx-annotations.yaml \
--namespace ingress-nginx \
--create-namespace

That is the content of my file ngress-nginx-annotations.yaml 

```
controller:
  kind: DaemonSet
  service:
    annotations:
      load-balancer.hetzner.cloud/location: nbg1
      load-balancer.hetzner.cloud/name: lb_k3s
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/uses-proxyprotocol: 'true'
      load-balancer.hetzner.cloud/http-redirect-https: 'false'
```

My ingress-controller looks fine after that and a new hetzner lb was deployed and both services Healthchecks are green. But they also getting a HTTP 400 all the time

k describe svc ingress-nginx-controller -n ingress-nginx

```
Name:                     ingress-nginx-controller
Namespace:                ingress-nginx
Labels:                   app.kubernetes.io/component=controller
                          app.kubernetes.io/instance=ingress-nginx
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=ingress-nginx
                          app.kubernetes.io/part-of=ingress-nginx
                          app.kubernetes.io/version=1.1.2
                          helm.sh/chart=ingress-nginx-4.0.18
Annotations:              load-balancer.hetzner.cloud/http-redirect-https: false
                          load-balancer.hetzner.cloud/location: nbg1
                          load-balancer.hetzner.cloud/name: lb_k3s
                          load-balancer.hetzner.cloud/use-private-ip: true
                          load-balancer.hetzner.cloud/uses-proxyprotocol: true
                          meta.helm.sh/release-name: ingress-nginx
                          meta.helm.sh/release-namespace: ingress-nginx
Selector:                 app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx
Type:                     LoadBalancer
IP:                       10.43.92.9
LoadBalancer Ingress:     <public ip4 of LB>, <public ipv6 of LB>, 10.0.0.4
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  30457/TCP
Endpoints:                10.244.1.33:80
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  30998/TCP
Endpoints:                10.244.1.33:443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

So and then i deployed the hello-world test deployment + service

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: rancher/hello-world
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: hello-world.<####>.nip.io => I put my public ip4 address of the lb inside
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world
            port:
              number: 80
```

But when i send a request to hello-world.<####>.nip.io i'm getting a HTTP 400 all the time. The HTTP 400 comes from the ingress-nginx pod. I checked the logs. But i have no idea why it is a Bad request. The Health checks from the lb also getting a HTTP 400, i can see it in the logs.

Any suggestion what I'M doing wrong?

Thanks

**Comment by xxavarlonxx** [comment]
Okay i fixed the error by myself. Here is the solution. The Problem was that the use_proxy_protocol option in the nginx.conf is 'false' by default. To change that option to true, you have to add this option to the config map of ingress nginx. You can do this also over the values.yaml
```

controller:
  kind: DaemonSet
  config:
    use-proxy-protocol: true
  service:
    annotations:
      load-balancer.hetzner.cloud/location: nbg1
      load-balancer.hetzner.cloud/name: lb_k3s
      load-balancer.hetzner.cloud/use-private-ip: "true"
      load-balancer.hetzner.cloud/uses-proxyprotocol: 'true'
      load-balancer.hetzner.cloud/http-redirect-https: 'false' 
```

Then the option in nginx.conf was true and everything works fine. Maybe you should update your instruction issue.
