### ISSUE TITLE
run apt/yum/etc update and upgrade (or any command) on creation & wireguard-kernel "issues"

### ISSUE THREAD

**Issue by Privatecoder** [vitobotta/hetzner-k3s#75]
Hi @vitobotta,

it's me again ;) I was just building another cluster using your tool and figured there are two things I'm missing:

1) if encryption with wireguard is enabled one should use kernel `>5.6`. Hetzner uses `5.4.0-105-generic` on a default install of 20.04

2) to fix that I am running

```
apt update \
&& apt upgrade -y \
&& apt autoremove -y \
&& reboot
```

on each node along with this in the cluster_config.yaml:

```
additional_packages:
  - "linux-generic-hwe-20.04"
  - "open-iscsi"
  - "jq"
 ```

The two other packages are required for longhorn so I figured I add them there too, however I need to run an `apt update` + `upgrade` along with a `reboot` for the hwe-kernel to load.

I also run `mount --make-rshared /` on worker nodes for longhorn.

Could you add a separate `additional_commands` along with a `additional_packages` on a _pool-level_  and a `additional_commands` on a _global-level_?

Like:

```
worker_node_pools:
- name: test
  instance_type: cpx21
  instance_count: 3
  location: nbg1
  additional_packages:
    - "open-iscsi"
    - "jq"
  additional_commands:
    - "mount --make-rshared /"
enable_encryption: true
additional_packages:
  - "linux-generic-hwe-20.04"
additional_commands:
    - "apt update && apt upgrade -y && apt autoremove -y && reboot"
```

Best regards
Max
