### ISSUE TITLE
Endless Waiting for server to be up...

### ISSUE THREAD

**Issue by wiemann** [vitobotta/hetzner-k3s#96]
Getting an endless "Waiting for server XY to be up" for all machines (master & workers) on 0.6.1 on Apple Silicon.

Config:
```
---
hetzner_token: XXX
cluster_name: cluster_XY
kubeconfig_path: "./kubeconfig"
k3s_version: v1.23.3+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: fsn1
schedule_workloads_on_masters: false
masters:
  instance_type: cpx11
  instance_count: 1
worker_node_pools:
  - name: small
    instance_type: cx31
    instance_count: 3
enable_encryption: true
```
